// This file contains Devanagari script — ensure UTF-8 encoding
import type { Writer } from '../types'

export const bachchanWriter: Writer = {
  slug: 'bachchan',
  name_english: 'Harivansh Rai Bachchan',
  name_hindi: 'हरिवंश राय बच्चन',
  era: '20th century (1907–2003)',
  language: 'Hindi / Awadhi',
  genre: 'Modern Hindi poetry, philosophical verse, Madhushala',
  short_bio_english:
    'Poet of Madhushala and voice of modern Hindi literature, Bachchan explored life, longing, and philosophy through verse that millions still recite by heart.',
  short_bio_hindi:
    'मधुशाला के कवि और आधुनिक हिंदी साहित्य की आवाज़, बच्चन ने जीवन, लालसा और दर्शन को ऐसे पदों में व्यक्त किया जिन्हें लाखों लोग आज भी सुनते हैं।',
  biography: {
    introduction_english:
      'Harivansh Rai Bachchan (1907–2003) was one of the towering figures of 20th-century Hindi literature. Born in Allahabad, he earned a doctorate at Cambridge and taught at Allahabad University before joining the Ministry of External Affairs. His early masterpiece Madhushala (1935), written in stanzas of bechaare metre, uses the metaphor of a tavern to explore life\'s thirst for meaning. Bachchan also translated Omar Khayyam\'s Rubaiyat and wrote the autobiographical quartet Kya Bhoolun Kya Yaad Karoon. Father of actor Amitabh Bachchan, he received the Sahitya Akademi Award and Padma Bhushan.',
    introduction_hindi:
      'हरिवंश राय बच्चन (१९०७–२००३) बीसवीं सदी के हिंदी साहित्य के सबसे महत्वपूर्ण कवियों में से एक थे। इलाहाबाद में जन्मे, उन्होंने कैम्ब्रिज से डॉक्टरेट की और इलाहाबाद विश्वविद्यालय में पढ़ाने के बाद विदेश मंत्रालय में कार्य किया। उनकी प्रारंभिक कृति मधुशाला (१९३५) बेचार छंद में लिखी गई, जिसमें सराय की रूपक के माध्यम से जीवन की अर्थ-प्यास का चित्रण है। बच्चन ने उमर खय्याम की रубाइयों का अनुवाद भी किया और आत्मकथात्मक चतुष्कंदी क्या भूलूँ क्या याद करूँ लिखी। अभिनेता अमिताभ बच्चन के पिता, उन्हें साहित्य अकादमी पुरस्कार और पद्म भूषण मिला।',
    timeline: [
      {
        year: '1907',
        title_english: 'Birth in Allahabad',
        title_hindi: 'इलाहाबाद में जन्म',
        content_english:
          'Bachchan was born on 27 November 1907 in a Kayastha family in Allahabad (Prayagraj). His early life was marked by financial hardship after his father\'s death, yet he pursued education with remarkable determination.',
        content_hindi:
          '२७ नवंबर १९०७ को इलाहाबाद (प्रयागराज) में एक कायस्थ परिवार में बच्चन का जन्म हुआ। पिता की मृत्यु के बाद आर्थिक कठिनाई रही, पर शिक्षा के प्रति उनका दृढ़ संकल्प अटूट रहा।',
      },
      {
        year: '1935',
        title_english: 'Madhushala Published',
        title_hindi: 'मधुशाला का प्रकाशन',
        content_english:
          'Madhushala brought Bachchan instant fame. Its recurring refrain — "Madhushala" — and rich metaphors of wine, cup, and tavern as symbols of life\'s quest made it one of the best-selling Hindi poetry books ever written.',
        content_hindi:
          'मधुशाला ने बच्चन को तुरंत ख्याति दिलाई। इसका "मधुशाला" की धुन और शराब, प्याला, सराय के प्रतीकों ने जीवन की खोज को अमर बना दिया — यह सबसे अधिक बिकने वाली हिंदी काव्य पुस्तकों में से एक है।',
      },
      {
        year: '1941–1955',
        title_english: 'Academic and Diplomatic Career',
        title_hindi: 'शैक्षणिक और राजनयिक करियर',
        content_english:
          'Bachchan completed his PhD at Cambridge on W.B. Yeats and occultism, taught at Allahabad University, and later served in the Ministry of External Affairs in Delhi, translating diplomatic correspondence while continuing to write poetry.',
        content_hindi:
          'बच्चन ने कैम्ब्रिज में W.B. Yeats और रहस्यवाद पर PhD की, इलाहाबाद विश्वविद्यालय में पढ़ाया, और बाद में दिल्ली में विदेश मंत्रालय में कार्य किया — कूटनीतिक पत्रों का अनुवाद करते हुए काव्य लिखते रहे।',
      },
      {
        year: '1970s',
        title_english: 'Autobiography and Recognition',
        title_hindi: 'आत्मकथा और सम्मान',
        content_english:
          'His four-part autobiography — Kya Bhoolun Kya Yaad Karoon, Need Ka Nirman Phir, Basere Se Door, and Dashdwar Se Sopan Tak — won the Sahitya Akademi Award in 1976. He was honored with the Padma Bhushan in 1976.',
        content_hindi:
          'उनकी चार-खंडीय आत्मकथा — क्या भूलूँ क्या याद करूँ, नीड़ का निर्माण फिर, बसेरे से दूर, और दशद्वार से सोपान तक — ने १९७६ में साहित्य अकादमी पुरस्कार जीता। १९७६ में पद्म भूषण से सम्मानित हुए।',
      },
      {
        year: 'Legacy',
        title_english: 'Living Voice of Hindi Poetry',
        title_hindi: 'हिंदी काव्य की जीवित आवाज़',
        content_english:
          'Bachchan died on 18 January 2003 in Mumbai. Madhushala continues to be recited at gatherings across India. His blend of classical form and modern sensibility shaped generations of Hindi poets and readers.',
        content_hindi:
          '१८ जनवरी २००३ को मुंबई में बच्चन का निधन हुआ। मधुशाला आज भी भारत भर में सुनाई जाती है। शास्त्रीय रूप और आधुनिक संवेदना का उनका मेल हिंदी कवियों और पाठकों की पीढ़ियों को प्रभावित करता रहा।',
      },
    ],
    facts: {
      born: '27 November 1907 — Allahabad (Prayagraj), Uttar Pradesh',
      died: '18 January 2003 — Mumbai (aged 95)',
      full_name_english: 'Harivansh Rai Bachchan',
      full_name_hindi: 'हरिवंश राय बच्चन',
      court: 'Independent modern poet; Allahabad University; Ministry of External Affairs',
      works: [
        'Madhushala — iconic philosophical poem (1935)',
        'Madhukalash and Madhubala — sequels to Madhushala',
        'Kya Bhoolun Kya Yaad Karoon — autobiography (1969)',
        'Need Ka Nirman Phir — autobiography volume II',
        'Rubaiyat-e-Omar Khayyam — Hindi translation',
        'Ekaant Sangeet — collected poems',
      ],
    },
  },
  dohe: [
    {
      id: 161,
      hindi: 'मधुबन की सुगंध है,\nमधुशाला की राह।',
      english: 'The fragrance of the wine-garden leads to the tavern\'s path.',
      meaning_hindi: 'मधुबन की खुशबू मधुशाला की ओर ले जाती है — जीवन की खोज का मार्ग।',
      explanation: 'From Madhushala — the tavern metaphor draws the seeker toward life\'s deeper intoxication of meaning and experience.',
      theme: 'Wisdom',
      author: 'Harivansh Rai Bachchan',
      authorSlug: 'bachchan',
      featured: true,
    },
    {
      id: 162,
      hindi: 'जीवन की अपारता में\nहम खो जाते हैं।',
      english: 'In the vastness of life, we lose ourselves — and find ourselves.',
      meaning_hindi: 'जीवन की विशालता में हम खो जाते हैं — और वहीं अपना सार पाते हैं।',
      explanation: 'Bachchan\'s poetry often celebrates surrender to life\'s immensity as the path to self-discovery.',
      theme: 'Acceptance',
      author: 'Harivansh Rai Bachchan',
      authorSlug: 'bachchan',
    },
    {
      id: 163,
      hindi: 'कोशिश करने वालों की\nहार नहीं होती।',
      english: 'Those who keep trying never truly fail.',
      meaning_hindi: 'कोशिश करने वालों की असली हार नहीं होती — प्रयास ही विजय है।',
      explanation: 'One of Bachchan\'s most quoted motivational lines, urging perseverance through adversity with quiet dignity.',
      theme: 'Character',
      author: 'Harivansh Rai Bachchan',
      authorSlug: 'bachchan',
      featured: true,
    },
    {
      id: 164,
      hindi: 'लहरों से डर कर\nनौका पार नहीं होती।',
      english: 'A boat cannot cross the river if it fears the waves.',
      meaning_hindi: 'लहरों से डरकर नाव पार नहीं होती — साहस ही मार्ग है।',
      explanation: 'Bachchan uses the boat-and-waves image to teach that fear of difficulty prevents all achievement.',
      theme: 'Wisdom',
      author: 'Harivansh Rai Bachchan',
      authorSlug: 'bachchan',
    },
    {
      id: 165,
      hindi: 'मन के हारे हार है,\nमन के जीते जीत।',
      english: 'Defeat and victory both begin in the mind.',
      meaning_hindi: 'मन हार मान ले तो हार है, मन जीत ले तो जीत — सब कुछ मन पर निर्भर।',
      explanation: 'A classic Bachchan couplet on mental attitude — the battlefield of life is first fought within consciousness.',
      theme: 'Character',
      author: 'Harivansh Rai Bachchan',
      authorSlug: 'bachchan',
      featured: true,
    },
    {
      id: 166,
      hindi: 'अकेले चलो,\nअगर कोई न मिले साथी।',
      english: 'Walk alone if no companion joins your path.',
      meaning_hindi: 'अगर कोई साथी न मिले तो अकेले चलो — सत्य का मार्ग अकेला भी चला जाता है।',
      explanation: 'Bachchan encourages independent moral courage — the right path must be walked even without popular support.',
      theme: 'Character',
      author: 'Harivansh Rai Bachchan',
      authorSlug: 'bachchan',
    },
    {
      id: 167,
      hindi: 'प्यास बढ़ति रहे\nतो प्याला भी बढ़ता है।',
      english: 'As thirst grows, so does the cup — desire shapes capacity.',
      meaning_hindi: 'प्यास बढ़ति रहे तो प्याला बढ़ता है — लालसा ही क्षमता बढ़ाति है।',
      explanation: 'From the Madhushala metaphor — human longing expands the vessel of experience; life responds to deep desire.',
      theme: 'Wisdom',
      author: 'Harivansh Rai Bachchan',
      authorSlug: 'bachchan',
    },
    {
      id: 168,
      hindi: 'समय कभी रुकता नहीं,\nहम रुक जाते हैं।',
      english: 'Time never stops — only we pause in regret.',
      meaning_hindi: 'समय कभी नहीं रुकता, हम ही रुक जाते हैं — आगे बढ़ते रहो।',
      explanation: 'Bachchan reflects on temporality — wasted moments are human choice, not fate\'s decree.',
      theme: 'Acceptance',
      author: 'Harivansh Rai Bachchan',
      authorSlug: 'bachchan',
    },
    {
      id: 169,
      hindi: 'जो बीत गई सो बात गई,\nआगे देखो।',
      english: 'What is past is past — look ahead.',
      meaning_hindi: 'जो बीत चुका वह बीत चुका — आगे देखो, पीछे मत मुड़ो।',
      explanation: 'A beloved line on letting go — Bachchan counsels release from regret to embrace the present and future.',
      theme: 'Acceptance',
      author: 'Harivansh Rai Bachchan',
      authorSlug: 'bachchan',
    },
    {
      id: 170,
      hindi: 'हिम्मत मारने वालों,\nतुम कहाँ हो?',
      english: 'Where are you, destroyers of courage?',
      meaning_hindi: 'हिम्मत मारने वालों, तुम कहाँ हो? — साहस को मत तोड़ो।',
      explanation: 'Bachchan challenges those who discourage others — a rallying cry to protect the spirit of endeavor in society.',
      theme: 'Friendship',
      author: 'Harivansh Rai Bachchan',
      authorSlug: 'bachchan',
    },
    {
      id: 171,
      hindi: 'कर्म कर,\nफल की आशा छोड़।',
      english: 'Act without clinging to the fruit of action.',
      meaning_hindi: 'कर्म करो, परिणाम की आशा छोड़ दो — यही शांति का मार्ग है।',
      explanation: 'Drawing on the Gita\'s ethos, Bachchan urges dedicated work free from anxious expectation of reward.',
      theme: 'Wisdom',
      author: 'Harivansh Rai Bachchan',
      authorSlug: 'bachchan',
    },
    {
      id: 172,
      hindi: 'प्रेम की भाषा\nसब समझते हैं।',
      english: 'The language of love is understood by all.',
      meaning_hindi: 'प्रेम की भाषा सब समझते हैं — प्रेम में कोई बाधा नहीं।',
      explanation: 'Bachchan believed poetry and love transcend barriers of class, language, and education.',
      theme: 'Love & Relationships',
      author: 'Harivansh Rai Bachchan',
      authorSlug: 'bachchan',
    },
    {
      id: 173,
      hindi: 'धन से बड़ा\nकोई धर्म नहीं।',
      english: 'No wealth is greater than righteousness.',
      meaning_hindi: 'धन से बड़ा कोई धन नहीं — नैतिकता ही असली संपत्ति है।',
      explanation: 'Bachchan contrasts material riches with moral integrity, placing character above accumulation.',
      theme: 'Wealth & Materialism',
      author: 'Harivansh Rai Bachchan',
      authorSlug: 'bachchan',
    },
    {
      id: 174,
      hindi: 'सेवा में\nही सार्थकता है।',
      english: 'Meaning is found in service to others.',
      meaning_hindi: 'सेवा में ही जीवन की सार्थकता है — दूसरों के लिए जीना ही जीवन है।',
      explanation: 'Beyond personal fame, Bachchan valued contribution to society — poetry as service, not mere self-expression.',
      theme: 'Service',
      author: 'Harivansh Rai Bachchan',
      authorSlug: 'bachchan',
    },
    {
      id: 175,
      hindi: 'कविता\nहृदय की आवाज़ है।',
      english: 'Poetry is the voice of the heart made audible.',
      meaning_hindi: 'कविता हृदय की आवाज़ है — जो मन कह न पाए, कवि कह देता है।',
      explanation: 'Bachchan defined poetry as honest emotion refined into language — the heart speaking when ordinary words fail.',
      theme: 'Love & Relationships',
      author: 'Harivansh Rai Bachchan',
      authorSlug: 'bachchan',
    },
  ],
}
