// This file contains Devanagari script — ensure UTF-8 encoding
import type { Writer } from '../types'

export const bhartrihariWriter: Writer = {
  slug: 'bhartrihari',
  name_english: 'Bhartrihari',
  name_hindi: 'भर्तृहरि',
  era: '7th century CE',
  language: 'Sanskrit',
  genre: 'Niti shastra, Vairagya poetry, Shringara shataka',
  short_bio_english:
    'A legendary Sanskrit poet-king who renounced worldly life, Bhartrihari composed three celebrated Shatakas on ethics, detachment, and love.',
  short_bio_hindi:
    'संस्कृत के महान कवि-राज भर्तृहरि ने नीति, वैराग्य और शृंगार पर तीन प्रसिद्ध शतक रचे, जो आज भी जीवन-मार्गदर्शक हैं।',
  biography: {
    introduction_english:
      'Bhartrihari (c. 7th century CE) is one of the most influential Sanskrit poets in Indian literary history. Tradition holds that he was a king who renounced the throne after profound disillusionment with worldly life. He is credited with three major works — the Niti Shataka (100 verses on ethics and statecraft), the Vairagya Shataka (100 verses on detachment), and the Shringara Shataka (100 verses on love). His poetry combines razor-sharp worldly wisdom with deep spiritual insight, making him equally beloved by scholars, rulers, and seekers.',
    introduction_hindi:
      'भर्तृहरि (लगभग 7वीं शताब्दी) भारतीय साहित्य के सबसे प्रभावशाली संस्कृत कवियों में से एक हैं। परंपरा के अनुसार वे एक राजा थे जिन्होंने संसार के प्रति गहरी निराशा के बाद राज-पाट त्याग दिया। उन्हें नीति शतक, वैराग्य शतक और शृंगार शतक — तीन प्रमुख रचनाओं का श्रेय मिलता है। उनकी कविता में व्यावहारिक बुद्धिमत्ता और आध्यात्मिक गहराई का अद्भुत संगम है, जिससे वे विद्वान, शासक और साधक — सभी के प्रिय बने रहे।',
    timeline: [
      {
        year: 'c. 7th century',
        title_english: 'Birth and Royal Lineage',
        title_hindi: 'जन्म और राजवंश',
        content_english:
          'Bhartrihari is traditionally identified with a king of Ujjain or Malwa belonging to the Shalivahana dynasty. Legend connects him to the grammarian Bhartrhari, though scholars debate whether they were the same person. His early life is shrouded in story — royal privilege, scholarly training, and exposure to courtly life shaped his worldview.',
        content_hindi:
          'परंपरा में भर्तृहरि को उज्जैन या मालव के शालिवाहन वंश के राजा के रूप में पहचाना जाता है। किंवदंती उन्हें व्याकरणकार भर्तृहरि से जोड़ती है, हालाँकि विद्वान इस पर विवाद करते हैं। उनका प्रारंभिक जीवन कथाओं में लिपटा है — राजसी सुविधाएँ, विद्वत्ता और दरबारी जीवन ने उनके संसार-दर्शन को आकार दिया।',
      },
      {
        year: 'Early adulthood',
        title_english: 'Life at Court',
        title_hindi: 'दरबार में जीवन',
        content_english:
          'As a ruler and court poet, Bhartrihari witnessed the vanity of power, the instability of fortune, and the fleeting nature of pleasure. These experiences would later crystallize into the Vairagya Shataka. Court life also exposed him to political intrigue and the burdens of kingship.',
        content_hindi:
          'शासक और दरबारी कवि के रूप में भर्तृहरि ने सत्ता की छलावट, भाग्य की अस्थिरता और सुख की क्षणभंगुरता को करीब से देखा। ये अनुभव बाद में वैराग्य शतक में झलकते हैं। दरबारी जीवन ने उन्हें राजनीतिक चाल-चलन और राज्य-भार की गहराई से भी परिचित कराया।',
      },
      {
        year: 'Mid-life',
        title_english: 'The Renunciation',
        title_hindi: 'वैराग्य और संन्यास',
        content_english:
          'According to legend, Bhartrihari discovered his queen\'s infidelity or received a transformative spiritual teaching, leading him to abandon his kingdom. He took sannyasa and wandered as an ascetic. This turning point gave birth to his most celebrated verses on detachment and the emptiness of worldly attachment.',
        content_hindi:
          'किंवदंती के अनुसार भर्तृहरि ने रानी के विश्वासघात का पता लगाया या कोई परिवर्तनकारी आध्यात्मिक उपदेश पाया, जिससे उन्होंने राज्य त्याग दिया। उन्होंने संन्यास लिया और तपस्वी के रूप में भ्रमण किया। इसी मोड़ से संसारिक मोह की निरर्थकता पर उनकी सर्वाधिक प्रसिद्ध कविताएँ जन्मीं।',
      },
      {
        year: 'c. 7th century',
        title_english: 'Composition of the Shatakas',
        title_hindi: 'शतकों की रचना',
        content_english:
          'Bhartrihari composed three collections of one hundred verses each. The Niti Shataka offers counsel on conduct, friendship, and governance. The Vairagya Shataka expresses profound weariness with material existence. The Shringara Shataka explores the psychology of love and separation with exquisite sensitivity.',
        content_hindi:
          'भर्तृहरि ने सौ-सौ श्लोक के तीन संग्रह रचे। नीति शतक में आचरण, मित्रता और शासन पर उपदेश हैं। वैराग्य शतक भौतिक जीवन के प्रति गहरी उकताहट व्यक्त करता है। शृंगार शतक प्रेम और वियोग की मनोवृत्ति को अत्यंत सूक्ष्मता से उकेरता है।',
      },
      {
        year: 'Legacy',
        title_english: 'Enduring Influence',
        title_hindi: 'शाश्वत प्रभाव',
        content_english:
          'Bhartrihari\'s verses have been quoted, translated, and memorized across India for over thirteen centuries. Medieval poets, modern writers, and everyday speakers still draw on his maxims. His blend of worldly pragmatism and spiritual depth makes him uniquely accessible across cultures and eras.',
        content_hindi:
          'भर्तृहरि के श्लोक तेरह सदियों से भारत में उद्धृत, अनुवादित और याद किए जाते रहे हैं। मध्यकालीन कवियों से लेकर आधुनिक लेखकों और आम बोलचाल तक — उनके सूक्ति-वाक्य जीवित हैं। व्यावहारिक बुद्धि और आध्यात्मिक गहराई का उनका संगम उन्हें युगों-युगों में सुलभ बनाता है।',
      },
    ],
    facts: {
      born: 'c. 7th century — Ujjain / Malwa (traditional)',
      died: 'Unknown — likely c. 7th century',
      full_name_english: 'Bhartrihari',
      full_name_hindi: 'भर्तृहरि',
      court: 'King of Ujjain / Malwa (traditional); later independent ascetic-poet',
      works: [
        'Niti Shataka — 100 verses on ethics and wisdom',
        'Vairagya Shataka — 100 verses on detachment',
        'Shringara Shataka — 100 verses on love',
        'Vakyapadiya — treatise on grammar and philosophy of language (attributed)',
      ],
    },
  },
  dohe: [
    {
      id: 86,
      hindi: 'उद्योगिनं पुरुषसिंहमुपैति लक्ष्मीः\nदैवमिहापि नृणां मोहमात्रम्।\nअलसस्य कुतो वित्तं निद्रया शशवत्\nक्षणमपि न प्रभाति नष्टं दिनम्।।',
      english: 'Fortune favors the diligent man who works like a lion — fate here is merely delusion for humans. What wealth comes to the lazy? Like a rabbit sleeping through the day, not even a moment of dawn returns once lost.',
      meaning_hindi: 'मेहनती और साहसी व्यक्ति पर ही लक्ष्मी मुस्कुराती है; भाग्य अक्सर बहाना मात्र है। आलसी को धन कहाँ? जैसे खरगोश दिन भर सोता रहे, बीता हुआ समय कभी वापस नहीं आता।',
      explanation: 'From Niti Shataka. A classic exhortation to self-reliance and hard work over fatalism. The Sanskrit original appears in Devanagari above.',
      theme: 'Wealth & Materialism',
      author: 'Bhartrihari',
      authorSlug: 'bhartrihari',
      featured: true,
    },
    {
      id: 87,
      hindi: 'यावद्वित्तोपार्जनसकस्तावन्निजपर्वतो\nवासः। तदैव च निजभृत्यवर्गः\nततो भिक्षाशनं तत्र तथा वसितं\nजीर्णानि वस्त्राणि।।',
      english: 'As long as you can earn wealth, live in your own home with your own servants. When that ceases — eat alms, wear tattered clothes, and dwell wherever you must.',
      meaning_hindi: 'जब तक कमाई हो, अपने घर में अपने सेवकों संग रहो। जब वह समय बीत जाए — भिक्षा खाओ, फटे कपड़े पहनो, जहाँ हो सको वहीं रहो।',
      explanation: 'From Vairagya Shataka, verse 13. One of Bhartrihari\'s most quoted verses on the impermanence of prosperity and the dignity of accepting change.',
      theme: 'Acceptance',
      author: 'Bhartrihari',
      authorSlug: 'bhartrihari',
      featured: true,
    },
    {
      id: 88,
      hindi: 'संसारः सरः सत्यतुल्यनिःश्रेणी\nमत्स्याः क्षुद्राः क्षुद्राः क्षुद्राः।\nमज्जन्ति पतन्ति च पतन्ति च\nपतन्ति च।।',
      english: 'The world is like a lake with a steep, slippery bank. Small fish keep slipping, falling, falling, and falling again — unable to climb out.',
      meaning_hindi: 'संसार एक झील है जिसके किनारे फिसलन भरे हैं। छोटी मछलियाँ बार-बार फिसलकर गिरती रहती हैं — बाहर निकल नहीं पातीं।',
      explanation: 'From Vairagya Shataka. A vivid metaphor for samsara — the cycle of worldly entanglement from which ordinary beings struggle to escape.',
      theme: 'Wisdom',
      author: 'Bhartrihari',
      authorSlug: 'bhartrihari',
    },
    {
      id: 89,
      hindi: 'भिक्षाशनं तत्र तथा वसितं जीर्णानि\nवस्त्राणि। तदपि न मुह्यति यः\nस एव धन्यः कुलजनो नृपतिः\nस एव पण्डितः।।',
      english: 'He who is not deluded even while eating alms, dwelling anywhere, and wearing worn-out clothes — he alone is truly noble, a true king, a true scholar.',
      meaning_hindi: 'जो भिक्षा, जीर्ण वस्त्र और कहीं भी निवास के बावजूद मोह में नहीं फँसता — वही सच्चा कुलीन, राजा और पंडित है।',
      explanation: 'From Vairagya Shataka, verse 7. Defines true nobility not by birth or wealth but by freedom from worldly delusion.',
      theme: 'Character',
      author: 'Bhartrihari',
      authorSlug: 'bhartrihari',
      featured: true,
    },
    {
      id: 90,
      hindi: 'चञ्चलं हि मनः कामो बलवान्\nवातो वृक्षान् इव।\nतस्मात्सर्वप्रयत्नेन\nग्राह्यं मनः शान्तम्।।',
      english: 'The mind is restless and desire is powerful — like wind shaking trees. Therefore, with every effort, one must grasp and steady the mind toward peace.',
      meaning_hindi: 'मन चंचल है और कामना बलवान — जैसे वायु वृक्षों को हिलाती है। इसलिए पूरे प्रयास से मन को शांत और स्थिर करना चाहिए।',
      explanation: 'From Niti Shataka. Emphasizes mental discipline as the foundation of ethical and spiritual life.',
      theme: 'Wisdom',
      author: 'Bhartrihari',
      authorSlug: 'bhartrihari',
    },
    {
      id: 91,
      hindi: 'अजरामरवत् प्राज्ञो विद्वान्\nसर्वत्र पूज्यते।\nज्ञानं सर्वस्य धनम्\nयत् कस्यचित् नापह्रियते।।',
      english: 'The wise scholar is honored everywhere as though ageless and immortal. Knowledge is the one wealth that no one can steal from you.',
      meaning_hindi: 'ज्ञानी विद्वान सर्वत्र ऐसे पूजा जाता है जैसे वह अजर-अमर हो। ज्ञान वह धन है जिसे कोई छीन नहीं सकता।',
      explanation: 'From Niti Shataka. Celebrates learning as the only imperishable and inalienable form of wealth.',
      theme: 'Wealth & Materialism',
      author: 'Bhartrihari',
      authorSlug: 'bhartrihari',
    },
    {
      id: 92,
      hindi: 'माता यस्य गृहे नास्ति भार्या\nचाप्रिया।\nसुखं तस्य कुतः\nसिंहस्येव मृगे।।',
      english: 'He who has no mother at home and no beloved wife — where is his happiness? Like a lion among deer, he lives in constant unease.',
      meaning_hindi: 'जिसके घर में माँ नहीं और प्रिय पत्नी भी नहीं — उसे सुख कहाँ? जैसे मृगों में सिंह, वह असहज रहता है।',
      explanation: 'From Shringara Shataka. Explores how love and familial bonds anchor human happiness — a rare tender note in Bhartrihari\'s corpus.',
      theme: 'Love & Relationships',
      author: 'Bhartrihari',
      authorSlug: 'bhartrihari',
    },
    {
      id: 93,
      hindi: 'मित्रं मुखप्रसादेन लभ्यते\nक्रोधेन न।\nस्नेहेन मधुरं वाक्यं\nमित्रं दीर्घकालम्।।',
      english: 'Friendship is gained through a pleasant face, not through anger. Sweet words spoken with affection sustain friendship for a long time.',
      meaning_hindi: 'मित्रता प्रसन्न मुख से मिलती है, क्रोध से नहीं। स्नेह भरे मधुर वचन मित्रता को दीर्घकाल तक बनाए रखते हैं।',
      explanation: 'From Niti Shataka. Practical counsel on maintaining friendships through warmth and gentle speech.',
      theme: 'Friendship',
      author: 'Bhartrihari',
      authorSlug: 'bhartrihari',
    },
    {
      id: 94,
      hindi: 'त्यजेदेकं कुलस्यार्थे\nग्रामस्यार्थे कुलं त्यजेत्।\nत्यजेदर्थं सुरक्षितं\nआत्मार्थे पृथिवीं त्यजेत्।।',
      english: 'Sacrifice one person for the family, the family for the village, secure wealth for a greater cause — and for the sake of the soul, renounce the entire world.',
      meaning_hindi: 'कुल के लिए एक को, गाँव के लिए कुल को त्यागो; बड़े उद्देश्य के लिए संपत्ति छोड़ो — और आत्मा के लिए सारा संसार त्याग दो।',
      explanation: 'From Niti Shataka. A hierarchy of sacrifice culminating in spiritual renunciation — one of the most cited Sanskrit ethical maxims.',
      theme: 'Service',
      author: 'Bhartrihari',
      authorSlug: 'bhartrihari',
    },
    {
      id: 95,
      hindi: 'न चिन्त्यं न चिन्त्यं न चिन्त्यं\nपुनः पुनः।\nयदि चिन्त्यं तदा\nत्यज्यतां भोगः।।',
      english: 'Do not worry, do not worry, do not worry again and again. If you must worry at all — then abandon indulgence in pleasures.',
      meaning_hindi: 'चिंता मत करो, मत करो, बार-बार मत करो। अगर फिर भी चिंता करनी हो — तो भोग-विलास त्याग दो।',
      explanation: 'From Vairagya Shataka. Witty repetition drives home the futility of anxiety and links worry to attachment to sensory pleasure.',
      theme: 'Acceptance',
      author: 'Bhartrihari',
      authorSlug: 'bhartrihari',
    },
    {
      id: 96,
      hindi: 'वयसि गते कः कामविकारः\nशुष्के नीरे कः कासारः।\nक्षीणे वित्ते कः परिवारः\nज्ञाते तत्त्वे कः संसारः।।',
      english: 'When youth is gone, what passion remains? In a dried-up pond, what lake? When wealth is spent, what family stays? When truth is known, what world exists?',
      meaning_hindi: 'जवानी बीत जाए तो कामना क्या? सूखे तालाब में सरोवर कैसा? धन खत्म हो तो परिवार क्या? सत्य जान लिया तो संसार क्या?',
      explanation: 'From Vairagya Shataka, verse 84. A chain of rhetorical questions dismantling attachment to body, wealth, and worldly relationships.',
      theme: 'Wisdom',
      author: 'Bhartrihari',
      authorSlug: 'bhartrihari',
    },
    {
      id: 97,
      hindi: 'सतां सङ्गः स्वर्गे लोकः\nसतां सङ्गः परं सुखम्।\nसतां सङ्गात् प्रवर्तते\nसर्वं शुभम्।।',
      english: 'The company of the good is heaven itself; the company of the good is supreme bliss. From the company of the good, all auspiciousness flows.',
      meaning_hindi: 'सज्जनों का संग स्वर्ग है; सज्जनों का संग परम सुख है। सत्संग से ही सारी शुभता प्रवाहित होती है।',
      explanation: 'From Niti Shataka. Affirms that noble companionship is the highest spiritual and worldly good.',
      theme: 'Friendship',
      author: 'Bhartrihari',
      authorSlug: 'bhartrihari',
    },
    {
      id: 98,
      hindi: 'अहो बत विचित्रं मतिरायं\nबालानाम्।\nधनं च यौवनं च\nसर्वं क्षणभङ्गुरम्।।',
      english: 'How strange is the mind of the young! Wealth and youth — everything is momentary and perishable.',
      meaning_hindi: 'बालकों का मन कितना विचित्र है! धन और जवानी — सब कुछ क्षणभंगुर है।',
      explanation: 'From Vairagya Shataka. Reflects on the folly of youth chasing impermanent pleasures without awareness of mortality.',
      theme: 'Wealth & Materialism',
      author: 'Bhartrihari',
      authorSlug: 'bhartrihari',
    },
    {
      id: 99,
      hindi: 'शान्तं पदं न प्राप्नोति\nसंसारे।\nयावद् भोगेषु मनो\nनिविष्टम्।।',
      english: 'One cannot attain the state of peace in this world as long as the mind remains immersed in pleasures.',
      meaning_hindi: 'जब तक मन भोगों में लगा रहे, संसार में शांति की अवस्था प्राप्त नहीं हो सकती।',
      explanation: 'From Vairagya Shataka. Links inner tranquility directly to withdrawal from sensory indulgence.',
      theme: 'Acceptance',
      author: 'Bhartrihari',
      authorSlug: 'bhartrihari',
    },
    {
      id: 100,
      hindi: 'सत्यं ब्रूयात् प्रियं ब्रूयात्\nन ब्रूयात् सत्यमप्रियम्।\nप्रियं च नानृतं ब्रूयात्\nएष धर्मः सनातनः।।',
      english: 'Speak the truth, speak what is pleasant — but do not speak truth that is unpleasant. Do not speak what is pleasant but false. This is the eternal dharma.',
      meaning_hindi: 'सत्य बोलो, प्रिय बोलो — पर सत्य जो अप्रिय हो वह मत बोलो। प्रिय लेकिन असत्य भी मत बोलो। यही सनातन धर्म है।',
      explanation: 'From Niti Shataka. A nuanced ethic of speech balancing honesty, kindness, and social harmony — widely quoted in Indian tradition.',
      theme: 'Character',
      author: 'Bhartrihari',
      authorSlug: 'bhartrihari',
    },
  ],
}
