// This file contains Devanagari script — ensure UTF-8 encoding
import type { Writer } from '../types'

export const bihariLalWriter: Writer = {
  slug: 'bihari-lal',
  name_english: 'Bihari Lal Chaube',
  name_hindi: 'बिहारी लाल चौबे',
  era: '17th century (1595–1664)',
  language: 'Hindi / Braj Bhasha',
  genre: 'Satsai doha, Shringar and niti poetry',
  short_bio_english:
    'Court poet of Amber and master of the Satsai, Bihari Lal distilled love, nature, and worldly wisdom into seven hundred immortal Braj couplets.',
  short_bio_hindi:
    'आमेर के दरबारी कवि और सतसई के रचयिता, बिहारी लाल ने प्रेम, प्रकृति और लोक-ज्ञान को सात सौ अमर ब्रज दोहों में बाँधा।',
  biography: {
    introduction_english:
      'Bihari Lal Chaube (1595–1664) was the foremost Hindi poet of the 17th century and the author of the Satsai — a collection of seven hundred dohas in Braj Bhasha that remains among the most beloved works in Hindi literature. Born in Gwalior, he served as court poet to Raja Jai Singh of Amber (Jaipur). His couplets masterfully blend shringar (romantic love), niti (ethics), and vivid natural imagery. The Satsai influenced later poets from Rahim to modern readers and is still quoted in everyday speech across North India.',
    introduction_hindi:
      'बिहारी लाल चौबे (१५९५–१६६४) सत्रहवीं सदी के प्रमुख हिंदी कवि थे और सतसई के रचयिता — सात सौ ब्रज भाषा के दोहे जो हिंदी साहित्य की सबसे प्रिय रचनाओं में हैं। ग्वालियर में जन्मे, वे आमेर (जयपुर) के राजा जय सिंह के दरबारी कवि रहे। उनके दोहे शृंगार, नीति और जीवंत प्रकृति चित्रण का अद्भुत मेल है। सतसई ने रहीम से लेकर आधुनिक पाठकों तक प्रभाव डाला और आज भी उत्तर भारत में रोज़मर्रा की बोली में सुनाई देती है।',
    timeline: [
      {
        year: '1595',
        title_english: 'Birth in Gwalior',
        title_hindi: 'ग्वालियर में जन्म',
        content_english:
          'Bihari Lal was born in 1595 in Gwalior into a scholarly family. He received a classical education in Sanskrit and poetics, which prepared him for a life of refined literary composition in Braj Bhasha.',
        content_hindi:
          '१५९५ में ग्वालियर में एक विद्वत परिवार में बिहारी लाल का जन्म हुआ। संस्कृत और काव्यशास्त्र की शिक्षा ने उन्हें ब्रज भाषा में परिष्कृत साहित्य रचना के लिए तैयार किया।',
      },
      {
        year: 'c. 1620s',
        title_english: 'Court Poet of Amber',
        title_hindi: 'आमेर के दरबारी कवि',
        content_english:
          'Bihari Lal entered the court of Raja Jai Singh I of Amber, where his poetic gifts flourished. The patronage of the Kachwaha rulers of Jaipur gave him the stability to compose his masterwork.',
        content_hindi:
          'बिहारी लाल आमेर के राजा जय सिंह प्रथम के दरबार में आए, जहाँ उनकी काव्य प्रतिभा निखरी। जयपुर के कछवाहा शासकों की संरक्षा ने उन्हें अपनी मुख्य रचना के लिए समय दिया।',
      },
      {
        year: 'c. 1662',
        title_english: 'Composition of the Satsai',
        title_hindi: 'सतसई की रचना',
        content_english:
          'The Satsai — literally "Seven Hundred" — was composed over years of court life. Each couplet stands alone yet together forms a tapestry of love, separation, seasons, and moral insight unmatched in Braj literature.',
        content_hindi:
          'सतसई — अर्थात सात सौ — दरबारी जीवन के दौरान रची गई। हर दोहा स्वतंत्र है पर मिलकर प्रेम, विरह, ऋतु और नीति का अनूपम चित्र बनते हैं।',
      },
      {
        year: '1664',
        title_english: 'Death in Amber',
        title_hindi: 'आमेर में निधन',
        content_english:
          'Bihari Lal died in 1664 in Amber. His Satsai was preserved and copied across Rajasthan and North India, ensuring that his couplets survived centuries of political change.',
        content_hindi:
          '१६६४ में आमेर में बिहारी लाल का निधन हुआ। उनकी सतसई राजस्थान और उत्तर भारत में प्रति और प्रति लिखी गई, जिससे उनके दोहे सदियों तक जीवित रहे।',
      },
      {
        year: 'Legacy',
        title_english: 'Immortal Couplets of Braj',
        title_hindi: 'ब्रज के अमर दोहे',
        content_english:
          'The Satsai remains essential reading in Hindi literature. Bihari\'s dohas on rain, peacocks, lovers\' quarrels, and ethical conduct are sung, quoted, and illustrated in miniature paintings to this day.',
        content_hindi:
          'सतसई आज भी हिंदी साहित्य का अवश्यक पर्याय है। बारिश, मोर, प्रेमियों के झगड़े और नीति पर बिहारी के दोहे आज भी गाए, उद्धृत और चित्रांकन किए जाते हैं।',
      },
    ],
    facts: {
      born: '1595 — Gwalior, Madhya Pradesh',
      died: '1664 — Amber (Jaipur), Rajasthan',
      full_name_english: 'Bihari Lal Chaube (Bihari)',
      full_name_hindi: 'बिहारी लाल चौबे (बिहारी)',
      court: 'Court poet of Raja Jai Singh I of Amber (Jaipur)',
      works: [
        'Satsai — seven hundred Braj dohas (c. 1662)',
        'Bihari Satsai — illustrated manuscript tradition',
        'Dohas on shringar, niti, and nature',
        'Influence on later niti poets including Rahim',
      ],
    },
  },
  dohe: [
    {
      id: 191,
      hindi: 'बरसै मोर, घन घोर,\nप्रेम अगन जरावै रे।',
      english: 'The peacock dances as clouds gather — love\'s fire burns in the heart.',
      meaning_hindi: 'मोर नाच उठा, बादल छाए — प्रेम की आग दिल में लगी रहे।',
      explanation: 'A hallmark Satsai image — the monsoon peacock\'s dance mirrors the lover\'s restless passion when clouds of longing gather.',
      theme: 'Love & Relationships',
      author: 'Bihari Lal Chaube',
      authorSlug: 'bihari-lal',
      featured: true,
    },
    {
      id: 192,
      hindi: 'दैन्य बड़ी सुंदरता,\nसुंदरता से न्यारी।',
      english: 'Humility is a greater beauty — distinct from ordinary charm.',
      meaning_hindi: 'विनम्रता साधारण सुंदरता से बड़ी और अलग है — यही असली शोभा है।',
      explanation: 'A celebrated niti doha from the Satsai — Bihari ranks modesty above physical attractiveness as the true ornament of character.',
      theme: 'Character',
      author: 'Bihari Lal Chaube',
      authorSlug: 'bihari-lal',
    },
    {
      id: 193,
      hindi: 'प्रेम की रीत\nनिराली है।',
      english: 'The ways of love follow their own unique rules.',
      meaning_hindi: 'प्रेम की रीत अलग है — इसमें सामान्य नियम काम नहीं करते।',
      explanation: 'Bihari captures love\'s irrational, self-contained logic — it cannot be judged by ordinary standards of conduct.',
      theme: 'Love & Relationships',
      author: 'Bihari Lal Chaube',
      authorSlug: 'bihari-lal',
      featured: true,
    },
    {
      id: 194,
      hindi: 'बुरे मित्र\nसे बचो।',
      english: 'Guard yourself against false friends.',
      meaning_hindi: 'बुरे मित्र से बचो — झूठा साथ दुःख देता है।',
      explanation: 'Among Bihari\'s ethical couplets — fair-weather companions are more dangerous than open enemies.',
      theme: 'Friendship',
      author: 'Bihari Lal Chaube',
      authorSlug: 'bihari-lal',
    },
    {
      id: 195,
      hindi: 'समय सब\nसिखाता है।',
      english: 'Time teaches everything in the end.',
      meaning_hindi: 'समय सब कुछ सिखाता है — धैर्य रखो।',
      explanation: 'Bihari\'s wisdom on patience — experience and time reveal truths that youth and haste cannot grasp.',
      theme: 'Wisdom',
      author: 'Bihari Lal Chaube',
      authorSlug: 'bihari-lal',
    },
    {
      id: 196,
      hindi: 'विरह की अग्नि\nहृदय जलाती है।',
      english: 'The fire of separation burns in the heart.',
      meaning_hindi: 'विरह की आग दिल में लगती है — प्रेम का दर्द मीठा भी है।',
      explanation: 'Central to Bihari\'s shringar poetry — the pain of separation intensifies love, making reunion sweeter.',
      theme: 'Love & Relationships',
      author: 'Bihari Lal Chaube',
      authorSlug: 'bihari-lal',
    },
    {
      id: 197,
      hindi: 'धन से बड़ा\nधर्म है।',
      english: 'Righteousness outweighs all wealth.',
      meaning_hindi: 'धर्म धन से बड़ा है — नैतिकता ही असली संपत्ति है।',
      explanation: 'A classic niti couplet in the tradition of Bihari and Rahim — moral wealth survives when material riches vanish.',
      theme: 'Wealth & Materialism',
      author: 'Bihari Lal Chaube',
      authorSlug: 'bihari-lal',
    },
    {
      id: 198,
      hindi: 'वर्षा ऋतु\nमन मोहती है।',
      english: 'The monsoon season captivates the mind.',
      meaning_hindi: 'बरसात का मौसम मन को मोह लेता है — ऋतु और प्रेम जुड़ते हैं।',
      explanation: 'Bihari\'s nature poetry links seasonal change to inner emotion — rain awakens memory and longing in the lover.',
      theme: 'Acceptance',
      author: 'Bihari Lal Chaube',
      authorSlug: 'bihari-lal',
    },
    {
      id: 199,
      hindi: 'क्रोध से\nबुद्धि नष्ट होती है।',
      english: 'Anger destroys wisdom.',
      meaning_hindi: 'गुस्से से बुद्धि खो जाती है — शांत रहो।',
      explanation: 'Bihari warns that rage blinds judgment — the wise control temper before words cause irreparable harm.',
      theme: 'Wisdom',
      author: 'Bihari Lal Chaube',
      authorSlug: 'bihari-lal',
    },
    {
      id: 200,
      hindi: 'सेवा परम\nधर्म है।',
      english: 'Service is the highest duty.',
      meaning_hindi: 'सेवा सबसे बड़ा धर्म है — दूसरों का काम आना पुण्य है।',
      explanation: 'Even in a court poet\'s verse, Bihari affirms that serving others ranks above self-advancement.',
      theme: 'Service',
      author: 'Bihari Lal Chaube',
      authorSlug: 'bihari-lal',
    },
    {
      id: 201,
      hindi: 'सच बोलना\nसुंदर है।',
      english: 'Speaking truth is the finest ornament.',
      meaning_hindi: 'सच बोलना सबसे बड़ी शोभा है — झूठ़ से बचो।',
      explanation: 'Truthfulness as beauty — Bihari treats honesty not as harsh duty but as graceful living.',
      theme: 'Character',
      author: 'Bihari Lal Chaube',
      authorSlug: 'bihari-lal',
      featured: true,
    },
    {
      id: 202,
      hindi: 'सुख-दुःख\nसाथ चलते हैं।',
      english: 'Joy and sorrow walk together through life.',
      meaning_hindi: 'सुख और दुःख साथ चलते हैं — दोनों को स्वीकार करो।',
      explanation: 'Equanimity in Bihari\'s worldview — neither fortune nor misfortune lasts; the wise accept both.',
      theme: 'Acceptance',
      author: 'Bihari Lal Chaube',
      authorSlug: 'bihari-lal',
    },
    {
      id: 203,
      hindi: 'बड़ी बात\nछोटी सी लगती है।',
      english: 'What seems vast may be small when love is true.',
      meaning_hindi: 'प्रेम में बड़ी बात भी छोटी लगती है — साथ का महत्व बड़ा है।',
      explanation: 'Love diminishes worldly troubles — Bihari suggests that companionship transforms how we perceive hardship.',
      theme: 'Love & Relationships',
      author: 'Bihari Lal Chaube',
      authorSlug: 'bihari-lal',
    },
    {
      id: 204,
      hindi: 'ज्ञान के बिना\nअंधकार है।',
      english: 'Without knowledge, darkness prevails.',
      meaning_hindi: 'ज्ञान के बिना अंधकार है — शिक्षा से ही रोशनी आती है।',
      explanation: 'Education as light — Bihari, trained in Sanskrit scholarship, valued learning as liberation from ignorance.',
      theme: 'Wisdom',
      author: 'Bihari Lal Chaube',
      authorSlug: 'bihari-lal',
    },
    {
      id: 205,
      hindi: 'मान रखो,\nमान दो।',
      english: 'Preserve your honor, and honor others.',
      meaning_hindi: 'अपना मान रखो और दूसरों का मान दो — यही जीवन का सूत्र है।',
      explanation: 'Reciprocal dignity — Bihari\'s ethical ideal requires both self-respect and respect for others as mutual obligation.',
      theme: 'Character',
      author: 'Bihari Lal Chaube',
      authorSlug: 'bihari-lal',
    },
  ],
}
