// This file contains Devanagari script — ensure UTF-8 encoding
import type { Writer } from '../types'

export const dinkarWriter: Writer = {
  slug: 'dinkar',
  name_english: 'Ramdhari Singh Dinkar',
  name_hindi: 'रामधारी सिंह दिनकर',
  era: '20th century (1908–1974)',
  language: 'Hindi',
  genre: 'Epic poetry, nationalist verse, philosophical kavya',
  short_bio_english:
    'National poet of India and author of Rashmirathi and Urvashi, Dinkar fused Sanskrit gravitas with modern Hindi to celebrate heroism, justice, and human dignity.',
  short_bio_hindi:
    'भारत के राष्ट्रकवि और रश्मिरथी, उर्वशी के रचयिता, दिनकर ने संस्कृत की गंभीरता को आधुनिक हिंदी से मिलाकर वीरता, न्याय और मानव गरिमा का गुणगान किया।',
  biography: {
    introduction_english:
      'Ramdhari Singh Dinkar (1908–1974) was one of the greatest Hindi poets of the 20th century and a leading voice of the Chhayavad and post-Chhayavad eras. Born in a poor family in Simaria, Bihar, he overcame hardship through education and became a professor of Hindi at Patna University. His epic Rashmirathi reimagines Karna from the Mahabharata as a symbol of dignity denied; Urvashi won the Jnanpith Award in 1972. Dinkar also wrote powerful nationalist poems during the freedom struggle. He received the Padma Bhushan and is widely honored as Rashtrakavi — the national poet.',
    introduction_hindi:
      'रामधारी सिंह दिनकर (१९०८–१९७४) बीसवीं सदी के महानतम हिंदी कवियों में से एक थे और छायावाद व उत्तर-छायावाद के प्रमुख स्वर थे। बिहार के सिमरिया में गरीब परिवार में जन्मे, उन्होंने कठिनाइयों को शिक्षा से पार किया और पटना विश्वविद्यालय में हिंदी के प्रोफेसर बने। उनकी महाकाव्य रश्मिरथी महाभारत के कर्ण को अपमानित गरिमा के प्रतीक के रूप में प्रस्तुत करती है; उर्वशी ने १९७२ में ज्ञानपीठ पुरस्कार जीता। दिनकर ने स्वतंत्रता संग्राम में प्रभावशाली राष्ट्रवादी कविताएँ भी लिखीं। उन्हें पद्म भूषण मिला और राष्ट्रकवि के रूप में सम्मानित किया जाता है।',
    timeline: [
      {
        year: '1908',
        title_english: 'Birth in Simaria, Bihar',
        title_hindi: 'बिहार के सिमरिया में जन्म',
        content_english:
          'Dinkar was born on 23 September 1908 in Simaria village, Begusarai district, Bihar, into a poor tenant-farming family. Poverty and social inequality he witnessed in childhood deeply shaped his poetry of justice and rebellion.',
        content_hindi:
          '२३ सितंबर १९०८ को बिहार के बेगूसराय जिले के सिमरिया गाँव में एक गरीब बटाईदार परिवार में दिनकर का जन्म हुआ। बचपन में देखी गरीबी और सामाजिक असमानता ने न्याय और विद्रोह की उनकी कविता को गहराई दी।',
      },
      {
        year: '1920s–1930s',
        title_english: 'Education and Freedom Struggle',
        title_hindi: 'शिक्षा और स्वतंत्रता संग्राम',
        content_english:
          'Dinkar studied at Mokama High School and Patna College, writing nationalist verse that led to brief imprisonment. Poems like "Singhasan Khaali Karo" voiced the people\'s demand for freedom with thunderous clarity.',
        content_hindi:
          'दिनकर ने मोकामा हाई स्कूल और पटना कॉलेज में पढ़ाई की, राष्ट्रवादी कविताएँ लिखीं और कुछ समय के लिए जेल भी गए। "सिंहासन खाली करो" जैसी कविताओं ने स्वतंत्रता की माँग को गर्जना से व्यक्त किया।',
      },
      {
        year: '1952',
        title_english: 'Rashmirathi Published',
        title_hindi: 'रश्मिरथी का प्रकाशन',
        content_english:
          'Rashmirathi, Dinkar\'s masterwork on Karna, became one of the most celebrated Hindi epics. Its portrayal of a hero wronged by birth but undefeated in spirit moved generations of readers and listeners.',
        content_hindi:
          'कर्ण पर दिनकर की कृति रश्मिरथी हिंदी के सबसे प्रसिद्ध महाकाव्यों में से एक बनी। जन्म से अपमानित पर आत्मा से अजेय नायक का चित्रण पीढ़ियों को छूता रहा।',
      },
      {
        year: '1961–1972',
        title_english: 'Urvashi and Jnanpith Award',
        title_hindi: 'उर्वशी और ज्ञानपीठ पुरस्कार',
        content_english:
          'Urvashi, a philosophical lyric epic exploring love and the human condition, was published in 1961. Dinkar received the Jnanpith Award in 1972 — the highest literary honor in India — for this work.',
        content_hindi:
          'प्रेम और मानव अस्तित्व पर दार्शनिक खंडकाव्य उर्वशी १९६१ में प्रकाशित हुआ। १९७२ में दिनकर को इस कृति के लिए भारत का सर्वोच्च साहित्यिक सम्मान ज्ञानपीठ पुरस्कार मिला।',
      },
      {
        year: 'Legacy',
        title_english: 'Rashtrakavi — Voice of the Nation',
        title_hindi: 'राष्ट्रकवि — राष्ट्र की आवाज़',
        content_english:
          'Dinkar died on 24 April 1974 in Begusarai. His poems remain central to Hindi curricula and public recitation. He is remembered as a poet who united classical dignity with modern democratic passion.',
        content_hindi:
          '२४ अप्रैल १९७४ को बेगूसराय में दिनकर का निधन हुआ। उनकी कविताएँ आज भी हिंदी पाठ्यक्रम और सार्वजनिक पाठ का अंग हैं। शास्त्रीय गरिमा और आधुनिक लोकतांत्रिक जोश को मिलाने वाले कवि के रूप में याद किए जाते हैं।',
      },
    ],
    facts: {
      born: '23 September 1908 — Simaria, Begusarai, Bihar',
      died: '24 April 1974 — Begusarai, Bihar (aged 65)',
      full_name_english: 'Ramdhari Singh Dinkar',
      full_name_hindi: 'रामधारी सिंह दिनकर',
      court: 'Independent poet; Patna University; Rashtrakavi (National Poet of India)',
      works: [
        'Rashmirathi — epic on Karna from the Mahabharata (1952)',
        'Urvashi — philosophical lyric epic (1961); Jnanpith Award 1972',
        'Kurukshetra — epic on the Mahabharata war',
        'Parashuram ki Prateeksha — narrative poetry',
        'Neem ke Patte — collected poems',
        'Hunkar — nationalist poetry of the freedom era',
      ],
    },
  },
  dohe: [
    {
      id: 176,
      hindi: 'सिंहासन खाली करो,\nकि जनता आती है।',
      english: 'Vacate the throne — the people are coming.',
      meaning_hindi: 'सिंहासन खाली करो — जनता आ रही है; सत्ता जनता की है।',
      explanation: 'Dinkar\'s iconic nationalist line from the freedom struggle — power belongs to the people, not to rulers who hoard it.',
      theme: 'Service',
      author: 'Ramdhari Singh Dinkar',
      authorSlug: 'dinkar',
      featured: true,
    },
    {
      id: 177,
      hindi: 'कर कल्पना,\nकर कर्म, कर जीवन।',
      english: 'Imagine, act, and live fully.',
      meaning_hindi: 'कल्पना करो, कर्म करो, जीवन जियो — तीनों मिलकर पूर्णता बनाते हैं।',
      explanation: 'Dinkar urges a life of vision combined with action — dreams without deeds remain empty, deeds without dreams lack direction.',
      theme: 'Wisdom',
      author: 'Ramdhari Singh Dinkar',
      authorSlug: 'dinkar',
    },
    {
      id: 178,
      hindi: 'जीवन की राह में\nधूप-छाँव दोनों हैं।',
      english: 'On life\'s path, both sunshine and shadow await.',
      meaning_hindi: 'जीवन के मार्ग पर धूप भी है, छाँव भी — दोनों स्वीकार करो।',
      explanation: 'A recurring Dinkar theme — life\'s alternating joy and sorrow must both be embraced with equal courage.',
      theme: 'Acceptance',
      author: 'Ramdhari Singh Dinkar',
      authorSlug: 'dinkar',
    },
    {
      id: 179,
      hindi: 'वीरता\nमृत्यु से नहीं डरती।',
      english: 'True valor does not fear death.',
      meaning_hindi: 'सच्ची वीरता मृत्यु से नहीं डरती — कर्तव्य सर्वोपरि है।',
      explanation: 'From his epic portraits of Karna and warriors — Dinkar celebrates courage that chooses duty over self-preservation.',
      theme: 'Character',
      author: 'Ramdhari Singh Dinkar',
      authorSlug: 'dinkar',
      featured: true,
    },
    {
      id: 180,
      hindi: 'न्याय का सूर्य\nकभी अस्त नहीं होता।',
      english: 'The sun of justice never sets.',
      meaning_hindi: 'न्याय का सूर्य कभी अस्त नहीं होता — अंत में सत्य की जीत होती है।',
      explanation: 'Dinkar\'s faith in eventual justice runs through Rashmirathi and his nationalist verse — oppression cannot endure forever.',
      theme: 'Wisdom',
      author: 'Ramdhari Singh Dinkar',
      authorSlug: 'dinkar',
    },
    {
      id: 181,
      hindi: 'गरिमा\nजन्म से नहीं, कर्म से।',
      english: 'Dignity comes from deeds, not from birth.',
      meaning_hindi: 'गरिमा जन्म से नहीं, कर्म से मिलती है — यही कर्ण का संदेश है।',
      explanation: 'The central message of Rashmirathi — Karna\'s nobility despite social rejection embodies Dinkar\'s democratic humanism.',
      theme: 'Character',
      author: 'Ramdhari Singh Dinkar',
      authorSlug: 'dinkar',
      featured: true,
    },
    {
      id: 182,
      hindi: 'राष्ट्र\nप्रेम से बनता है।',
      english: 'A nation is built through love, not hatred.',
      meaning_hindi: 'राष्ट्र प्रेम से बनता है, घृणा से नहीं — एकता ही शक्ति है।',
      explanation: 'Dinkar\'s nationalism was inclusive — he believed India\'s strength lay in unity across diversity, not in division.',
      theme: 'Love & Relationships',
      author: 'Ramdhari Singh Dinkar',
      authorSlug: 'dinkar',
    },
    {
      id: 183,
      hindi: 'कवि\nसमय का दर्पण है।',
      english: 'The poet is the mirror of the age.',
      meaning_hindi: 'कवि अपने युग का दर्पण है — समाज की आत्मा कविता में दिखती है।',
      explanation: 'Dinkar saw poetry as social testimony — the poet must speak truth to power and reflect the people\'s aspirations.',
      theme: 'Wisdom',
      author: 'Ramdhari Singh Dinkar',
      authorSlug: 'dinkar',
    },
    {
      id: 184,
      hindi: 'संघर्ष\nही जीवन का नाम है।',
      english: 'Struggle is the very name of life.',
      meaning_hindi: 'संघर्ष ही जीवन का नाम है — बिना संघर्ष के कोई उपलब्धि नहीं।',
      explanation: 'Dinkar\'s own life of poverty and perseverance informs this belief — achievement demands sustained effort against odds.',
      theme: 'Character',
      author: 'Ramdhari Singh Dinkar',
      authorSlug: 'dinkar',
    },
    {
      id: 185,
      hindi: 'धन\nसब कुछ नहीं है।',
      english: 'Wealth is not everything.',
      meaning_hindi: 'धन सब कुछ नहीं है — चरित्र और ज्ञान अधिक मूल्यवान हैं।',
      explanation: 'While not rejecting material need, Dinkar consistently placed moral and intellectual riches above mere accumulation.',
      theme: 'Wealth & Materialism',
      author: 'Ramdhari Singh Dinkar',
      authorSlug: 'dinkar',
    },
    {
      id: 186,
      hindi: 'मित्र\nविपत्ति में पहचाने जाते हैं।',
      english: 'Friends are known in adversity.',
      meaning_hindi: 'मित्र विपत्ति में पहचाने जाते हैं — सुख में तो सब पास होते हैं।',
      explanation: 'Drawing on classical wisdom, Dinkar applied the test of friendship to political alliances and personal loyalty alike.',
      theme: 'Friendship',
      author: 'Ramdhari Singh Dinkar',
      authorSlug: 'dinkar',
    },
    {
      id: 187,
      hindi: 'प्रकृति\nसबकी माँ है।',
      english: 'Nature is the mother of all.',
      meaning_hindi: 'प्रकृति सबकी माँ है — इसका सम्मान करना हमारा कर्तव्य है।',
      explanation: 'Dinkar\'s pastoral imagery in many poems reflects reverence for the land and seasons as sources of renewal and wisdom.',
      theme: 'Acceptance',
      author: 'Ramdhari Singh Dinkar',
      authorSlug: 'dinkar',
    },
    {
      id: 188,
      hindi: 'ज्ञान\nअंधकार में दीपक है।',
      english: 'Knowledge is the lamp in darkness.',
      meaning_hindi: 'ज्ञान अंधकार में दीपक है — शिक्षा से ही मुक्ति मिलती है।',
      explanation: 'Education lifted Dinkar from poverty — he championed learning as the path to individual and national liberation.',
      theme: 'Wisdom',
      author: 'Ramdhari Singh Dinkar',
      authorSlug: 'dinkar',
    },
    {
      id: 189,
      hindi: 'सेवा\nही उपासना है।',
      english: 'Service is the highest worship.',
      meaning_hindi: 'जनता की सेवा ही सच्ची उपासना है — कवि भी समाज का सेवक है।',
      explanation: 'Dinkar believed poets serve the nation by giving voice to the voiceless — art in service of the people, not the elite.',
      theme: 'Service',
      author: 'Ramdhari Singh Dinkar',
      authorSlug: 'dinkar',
    },
    {
      id: 190,
      hindi: 'स्वतंत्रता\nअमूल्य है।',
      english: 'Freedom is priceless — guard it with your life.',
      meaning_hindi: 'स्वतंत्रता अमूल्य है — इसे जीवन की कीमत पर भी सुरक्षित रखो।',
      explanation: 'Having lived through colonial rule, Dinkar knew freedom\'s cost — his poetry warns against taking liberty for granted.',
      theme: 'Character',
      author: 'Ramdhari Singh Dinkar',
      authorSlug: 'dinkar',
    },
  ],
}
