// This file contains Devanagari script — ensure UTF-8 encoding
import type { Writer } from '../types'

export const gandhiWriter: Writer = {
  slug: 'gandhi',
  name_english: 'Mahatma Gandhi',
  name_hindi: 'महात्मा गांधी',
  era: '19th–20th century (1869–1948)',
  language: 'Hindi / Gujarati / English',
  genre: 'Political philosophy, spiritual teachings, aphorisms',
  short_bio_english:
    'Leader of India\'s nonviolent independence movement, Gandhi lived and taught truth, ahimsa, and service — his words remain guides for conscience worldwide.',
  short_bio_hindi:
    'भारत के अहिंसक स्वतंत्रता आंदोलन के नेता, गांधी ने सत्य, अहिंसा और सेवा का जीवन जिया — उनके वचन आज भी विश्व की अंतरात्मा के मार्गदर्शक हैं।',
  biography: {
    introduction_english:
      'Mohandas Karamchand Gandhi (1869–1948), known as Mahatma Gandhi, was a lawyer, activist, and spiritual leader who led India to independence through nonviolent resistance (Satyagraha). Born in Porbandar, Gujarat, he studied law in London and practiced in South Africa, where he first developed his methods of civil disobedience against racial injustice. Returning to India in 1915, he championed swadeshi, khadi, Hindu-Muslim unity, and the dignity of the poorest. Assassinated in 1948, Gandhi left a legacy of moral courage that shaped civil rights movements across the globe.',
    introduction_hindi:
      'मोहनदास करमचंद गांधी (१८६९–१९४८), जिन्हें महात्मा गांधी कहा जाता है, एक वकील, सक्रिय नेता और आध्यात्मिक व्यक्ति थे जिन्होंने सत्याग्रह — अहिंसक प्रतिरोध — के माध्यम से भारत को स्वतंत्रता दिलाई। पोरबंदर, गुजरात में जन्मे, उन्होंने लंदन में विधि की पढ़ाई की और दक्षिण अफ्रीका में वकालत की, जहाँ उन्होंने नस्लीय असमानता के खिलाफ नागरिक असहयोग के तरीके विकसित किए। १९१५ में भारत लौटकर उन्होंने स्वदेशी, खादी, हिंदू-मुस्लिम एकता और गरीबों की गरिमा का प्रचार किया। १९४८ में हत्या कर दी गई, लेकिन उनकी नैतिक साहस ने पूरे विश्व के नागरिक अधिकार आंदोलनों को प्रेरित किया।',
    timeline: [
      {
        year: '1869',
        title_english: 'Birth in Porbandar',
        title_hindi: 'पोरबंदर में जन्म',
        content_english:
          'Gandhi was born into a Hindu Modh Baniya family in Porbandar, Gujarat. His mother Putlibai\'s deep religiosity and his father Karamchand\'s integrity as diwan shaped his early moral sensibility.',
        content_hindi:
          'गांधी का जन्म गुजरात के पोरबंदर में हिंदू मोध बनिया परिवार में हुआ। माता पुतलीबाई की गहरी धार्मिकता और पिता करमचंद की नैतिकता ने उनके बचपन के मूल्य बनाए।',
      },
      {
        year: '1893–1914',
        title_english: 'South Africa and Satyagraha',
        title_hindi: 'दक्षिण अफ्रीका और सत्याग्रह',
        content_english:
          'In South Africa, Gandhi faced racial discrimination and organized the Indian community in nonviolent protest. He coined the term Satyagraha — holding firmly to truth — which became the cornerstone of his philosophy.',
        content_hindi:
          'दक्षिण अफ्रीका में गांधी को नस्लीय भेदभाव का सामना करना पड़ा और उन्होंने भारतीय समुदाय को अहिंसक प्रतिरोध में संगठित किया। उन्होंने सत्याग्रह शब्द गढ़ा — सत्य पर दृढ़ रहना — जो उनके दर्शन का आधार बना।',
      },
      {
        year: '1915–1942',
        title_english: 'Leadership of Indian Independence',
        title_hindi: 'भारतीय स्वतंत्रता के नेतृत्व',
        content_english:
          'After returning to India, Gandhi led campaigns against the Rowlatt Act, for Khilafat unity, the Salt March (Dandi), Quit India, and countless local struggles. He lived simply, spinning khadi, and fasting for communal harmony.',
        content_hindi:
          'भारत लौटने के बाद गांधी ने रॉलेट कानून, खिलाफत एकता, दांडी यात्रा, भारत छोड़ो और अनेक स्थानीय संघर्षों का नेतृत्व किया। वे सरल जीवन जीते, खादी काते और सांप्रदायिक अमन के लिए उपवास करते थे।',
      },
      {
        year: '1947–1948',
        title_english: 'Partition and Final Fast',
        title_hindi: 'विभाजन और अंतिम उपवास',
        content_english:
          'Gandhi opposed Partition but worked tirelessly to stop communal violence in Bengal and Delhi. His final fast in January 1948 was for Hindu-Muslim peace. He was assassinated on 30 January 1948 in New Delhi.',
        content_hindi:
          'गांधी ने विभाजन का विरोध किया पर बंगाल और दिल्ली में सांप्रदायिक हिंसा रोकने के लिए अपार थक नहीं मानी। जनवरी १९४८ का अंतिम उपवास हिंदू-मुस्लिम शांति के लिए था। ३० जनवरी १९४८ को नई दिल्ली में उनकी हत्या कर दी गई।',
      },
      {
        year: 'Legacy',
        title_english: 'Global Icon of Nonviolence',
        title_hindi: 'अहिंसा का विश्व प्रतीक',
        content_english:
          'Gandhi influenced Martin Luther King Jr., Nelson Mandela, and countless peace movements. His collected writings span 100 volumes. "My life is my message" remains his most enduring testament.',
        content_hindi:
          'गांधी ने मार्टिन लूथर किंग, नेल्सन मंडेला और अनेक शांति आंदोलनों को प्रेरित किया। उनकी लिखी हुई रचनाएँ सौ खंडों में संग्रहित हैं। "मेरा जीवन ही मेरा संदेश है" उनका सर्वाधिक जीवन्त वचन है।',
      },
    ],
    facts: {
      born: '2 October 1869 — Porbandar, Gujarat',
      died: '30 January 1948 — New Delhi (assassinated)',
      full_name_english: 'Mohandas Karamchand Gandhi (Mahatma Gandhi)',
      full_name_hindi: 'मोहनदास करमचंद गांधी (महात्मा गांधी)',
      court: 'Independent political and spiritual leader; Indian National Congress',
      works: [
        'Hind Swaraj — Indian self-rule and critique of modern civilization',
        'My Experiments with Truth — autobiography',
        'Young India and Harijan — journals and essays',
        'Collected Works of Mahatma Gandhi — 100 volumes',
        'Constructive Programme — blueprint for village India',
      ],
    },
  },
  dohe: [
    {
      id: 131,
      hindi: 'जो परिवर्तन तुम दुनिया में देखना चाहते हो,\nवह स्वयं बनो।',
      english: 'Be the change you wish to see in the world.',
      meaning_hindi: 'जो बदलाव तुम संसार में चाहते हो, पहले खुद वह बनो।',
      explanation: 'Gandhi\'s most quoted teaching on personal responsibility. Transformation begins with oneself, not with blaming others or waiting for leaders.',
      theme: 'Character',
      author: 'Mahatma Gandhi',
      authorSlug: 'gandhi',
      featured: true,
    },
    {
      id: 132,
      hindi: 'आँख के बदले आँख लेने से\nपूरा संसार अंधा हो जाएगा।',
      english: 'An eye for an eye only ends up making the whole world blind.',
      meaning_hindi: 'प्रतिशोध की भावना से सारा संसार अंधा हो जाएगा — बदला कभी न्याय नहीं लाता।',
      explanation: 'Gandhi\'s famous rejection of revenge as justice. Cycles of retaliation destroy both victim and perpetrator without restoring harmony.',
      theme: 'Wisdom',
      author: 'Mahatma Gandhi',
      authorSlug: 'gandhi',
      featured: true,
    },
    {
      id: 133,
      hindi: 'वैष्णव जन तो तेने कहिए,\nजे पीड़ पराई जाणे रे।',
      english: 'Call him a Vaishnav who feels the pain of others.',
      meaning_hindi: 'वैष्णव वही है जो दूसरों के दुख को अपना समझे।',
      explanation: 'Gandhi cherished this bhajan by Narsinh Mehta as his moral ideal — true devotion is measured by empathy for the suffering of others.',
      theme: 'Character',
      author: 'Mahatma Gandhi',
      authorSlug: 'gandhi',
      featured: true,
    },
    {
      id: 134,
      hindi: 'सत्य ही हमेशा जीतता है,\nअसत्य कभी स्थायी विजय नहीं पाता।',
      english: 'Truth alone triumphs; untruth never wins in the end.',
      meaning_hindi: 'अंत में सत्य की ही जीत होती है; असत्य कभी स्थायी विजय नहीं पाता।',
      explanation: 'Gandhi\'s lifelong faith in Satya — drawn from the Upanishadic motto Satyameva Jayate — underpinned every Satyagraha campaign.',
      theme: 'Wisdom',
      author: 'Mahatma Gandhi',
      authorSlug: 'gandhi',
    },
    {
      id: 135,
      hindi: 'मेरा जीवन ही मेरा संदेश है।',
      english: 'My life is my message.',
      meaning_hindi: 'मेरा जीवन ही मेरा संदेश है — शब्दों से अधिक कर्म बोलते हैं।',
      explanation: 'Gandhi\'s reply when asked to summarize his teachings. He insisted that how one lives matters more than what one professes.',
      theme: 'Character',
      author: 'Mahatma Gandhi',
      authorSlug: 'gandhi',
    },
    {
      id: 136,
      hindi: 'अहिंसा परमो धर्मः।',
      english: 'Nonviolence is the highest duty.',
      meaning_hindi: 'अहिंसा सर्वोच्च धर्म है — हिंसा से कुछ भी शुद्ध नहीं बनता।',
      explanation: 'The principle at the heart of Gandhian ethics. Ahimsa is not weakness but the courage to resist injustice without harming the opponent.',
      theme: 'Acceptance',
      author: 'Mahatma Gandhi',
      authorSlug: 'gandhi',
    },
    {
      id: 137,
      hindi: 'सर्वोदय का मार्ग —\nसबका उत्थान, किसी का पतन नहीं।',
      english: 'The path of Sarvodaya — uplift of all, downfall of none.',
      meaning_hindi: 'सर्वोदय का मार्ग — सबका उत्थान, किसी का पतन नहीं।',
      explanation: 'Gandhi\'s economic and social vision drawn from Ruskin and Tolstoy — true progress means the welfare of the weakest, not the richest.',
      theme: 'Service',
      author: 'Mahatma Gandhi',
      authorSlug: 'gandhi',
    },
    {
      id: 138,
      hindi: 'स्वदेशी अपनाओ,\nविदेशी शोषण त्यागो।',
      english: 'Embrace what is your own; renounce what is foreign exploitation.',
      meaning_hindi: 'स्वदेशी अपनाओ — अपनी शक्ति और अपने उत्पाद का सम्मान करो।',
      explanation: 'Central to the Swadeshi movement — economic self-reliance through local production (especially khadi) as an act of freedom and dignity.',
      theme: 'Wealth & Materialism',
      author: 'Mahatma Gandhi',
      authorSlug: 'gandhi',
    },
    {
      id: 139,
      hindi: 'पाप से घृणा करो,\nपापी से नहीं।',
      english: 'Hate the sin, love the sinner.',
      meaning_hindi: 'पाप से घृणा करो, पापी से नहीं — हर व्यक्ति में दिव्य का अंश है।',
      explanation: 'Gandhi\'s approach to opponents in Satyagraha — resist wrong actions fiercely while recognizing the humanity of those who commit them.',
      theme: 'Love & Relationships',
      author: 'Mahatma Gandhi',
      authorSlug: 'gandhi',
    },
    {
      id: 140,
      hindi: 'स्वच्छता से बड़ा\nकोई धर्म नहीं।',
      english: 'Cleanliness is next to godliness — no religion is greater than cleanliness.',
      meaning_hindi: 'स्वच्छता बड़ी पूजा है — शरीर, मन और समाज की सफाई धर्म का अंग है।',
      explanation: 'Gandhi personally cleaned latrines to break caste taboos and taught that physical cleanliness reflects and supports spiritual purity.',
      theme: 'Service',
      author: 'Mahatma Gandhi',
      authorSlug: 'gandhi',
    },
    {
      id: 141,
      hindi: 'स्वतंत्रता का अर्थ है\nअपनी जिम्मेदारी।',
      english: 'Freedom means responsibility — freedom without discipline is license.',
      meaning_hindi: 'स्वतंत्रता का मतलब अपनी जिम्मेदारी लेना है — बिना अनुशासन के स्वतंत्रता अनर्थ है।',
      explanation: 'Gandhi warned that political independence without moral self-governance would fail. True freedom requires duty to others.',
      theme: 'Wisdom',
      author: 'Mahatma Gandhi',
      authorSlug: 'gandhi',
    },
    {
      id: 142,
      hindi: 'साधन और लक्ष्य\nदोनों शुद्ध होने चाहिए।',
      english: 'The means must be as pure as the end.',
      meaning_hindi: 'लक्ष्य जितना पवित्र हो, साधन भी उतना ही पवित्र होना चाहिए।',
      explanation: 'A core Gandhian principle — ends never justify violent or dishonest means. How you struggle defines what you become.',
      theme: 'Character',
      author: 'Mahatma Gandhi',
      authorSlug: 'gandhi',
    },
    {
      id: 143,
      hindi: 'कमजोर दुश्मन से डरो,\nमित्र से नहीं।',
      english: 'Fear the enemy who is weak — not the friend who is strong.',
      meaning_hindi: 'कमजोर दुश्मन से सावधान रहो — सच्चे मित्र से कभी न डरो।',
      explanation: 'Gandhi valued honest friendship and frank counsel. True friends strengthen us; only the insecure fear those who speak truth.',
      theme: 'Friendship',
      author: 'Mahatma Gandhi',
      authorSlug: 'gandhi',
    },
    {
      id: 144,
      hindi: 'क्षमा वीर का शस्त्र है,\nक्रोध का नहीं।',
      english: 'Forgiveness is the weapon of the strong, not the weak.',
      meaning_hindi: 'क्षमा साहसी का शस्त्र है — क्रोध से कुछ भी सुधार नहीं होता।',
      explanation: 'Gandhi practiced forgiveness toward opponents and taught that letting go of hatred requires greater courage than retaliation.',
      theme: 'Acceptance',
      author: 'Mahatma Gandhi',
      authorSlug: 'gandhi',
    },
    {
      id: 145,
      hindi: 'विश्वास खोने पर\nसब कुछ खोता है।',
      english: 'When faith is lost, everything is lost.',
      meaning_hindi: 'आप विश्वास खो देंगे तो दुनिया खो देंगे — विश्वास ही जीवन का आधार है।',
      explanation: 'Gandhi\'s faith in humanity and divine justice sustained decades of struggle. Trust in people and in truth was his spiritual foundation.',
      theme: 'Love & Relationships',
      author: 'Mahatma Gandhi',
      authorSlug: 'gandhi',
    },
  ],
}
