// This file contains Devanagari script — ensure UTF-8 encoding
import type { Writer } from '../types'

export const guruNanakWriter: Writer = {
  slug: 'guru-nanak',
  name_english: 'Guru Nanak',
  name_hindi: 'गुरु नानक',
  era: '15th–16th century (1469–1539)',
  language: 'Punjabi / Gurmukhi / Braj Bhasha',
  genre: 'Gurbani, Japji Sahib, Asa di Vaar, Shabad',
  short_bio_english:
    'Founder of Sikhism and first of the ten Sikh Gurus, Guru Nanak preached one formless God, honest living, and service to humanity through timeless shabads.',
  short_bio_hindi:
    'सिख धर्म के संस्थापक और दस गुरुओं में प्रथम, गुरु नानक ने एक निराकार ईश्वर, ईमानदार जीवन और मानवता की सेवा का संदेश गुरबानी के शब्दों में दिया।',
  biography: {
    introduction_english:
      'Guru Nanak Dev (1469–1539) was born in Talwandi (now Nankana Sahib, Pakistan) and became the founder of Sikhism — one of the world\'s great monotheistic faiths. After a transformative spiritual experience, he embarked on four major udasis (journeys) across India, Arabia, and Central Asia, preaching Ik Onkar — the One Creator. His compositions, including Japji Sahib and Asa di Vaar, form the opening sections of the Guru Granth Sahib. Nanak rejected caste, empty ritual, and religious division, insisting that truth, honest work, and sharing are the path to liberation.',
    introduction_hindi:
      'गुरु नानक देव (१४६९–१५३९) का जन्म तलवंडी (अब ननकाना साहिब, पाकिस्तान) में हुआ और वे सिख धर्म के संस्थापक बने। आध्यात्मिक अनुभव के बाद उन्होंने भारत, अरब और मध्य एशिया में चार बड़ी उदासियाँ कीं और एक ओंकार — एक सृष्टिकर्ता — का उपदेश दिया। जपुजी साहिब और आसा की वार सहित उनकी रचनाएँ गुरु ग्रंथ साहिब का आरंभिक भाग हैं। नानक ने जाति, खोखले कर्मकांड और धार्मिक विभाजन का विरोध किया और कहा कि सत्य, ईमानदार कर्म और साझा करना ही मुक्ति का मार्ग हैं।',
    timeline: [
      {
        year: '1469',
        title_english: 'Birth in Talwandi',
        title_hindi: 'तलवंडी में जन्म',
        content_english:
          'Nanak was born to Mehta Kalu and Mata Tripta in Rai Bhoi di Talwandi. Even as a child he showed contemplative nature and questioned conventional religious practice, preferring silent meditation to formal ritual.',
        content_hindi:
          'नानक का जन्म मेहता कालू और माता त्रिपता के घर राय भोई दी तलवंडी में हुआ। बचपन से ही वे चिंतनशील थे और औपचारिक कर्मकांड की बजाय मौन ध्यान को प्राथमिकता देते थे।',
      },
      {
        year: 'c. 1499',
        title_english: 'The Enlightenment at the River',
        title_hindi: 'नदी पर ज्योत',
        content_english:
          'Tradition records that Nanak disappeared for three days while bathing in the Vein River near Sultanpur. He returned proclaiming that there is no Hindu, no Muslim — only humanity before God.',
        content_hindi:
          'परंपरा के अनुसार नानक सुल्तानपुर के पास वेइन नदी में स्नान करते समय तीन दिन लापता रहे। लौटकर उन्होंने घोषणा की — न कोई हिंदू, न कोई मुसलमान; ईश्वर के समक्ष सभी मनुष्य समान हैं।',
      },
      {
        year: '1499–1521',
        title_english: 'Four Udasis (Journeys)',
        title_hindi: 'चार उदासियाँ',
        content_english:
          'Nanak traveled extensively — east to Assam, south to Sri Lanka, north to Tibet, and west to Mecca and Baghdad. At each stop he sang shabads, debated with priests and scholars, and taught that God dwells in every heart.',
        content_hindi:
          'नानक ने व्यापक यात्राएँ कीं — पूर्व में असम, दक्षिण में श्रीलंका, उत्तर में तिब्बत और पश्चिम में मक्का-बगदाद तक। हर स्थान पर उन्होंने शबद गाए, विद्वानों से वार्ता की और कहा कि ईश्वर हर हृदय में निवास करता है।',
      },
      {
        year: '1521–1539',
        title_english: 'Kartarpur and Community Life',
        title_hindi: 'करतारपुर और संघ जीवन',
        content_english:
          'Nanak settled at Kartarpur on the Ravi river and established a community based on honest labor, shared meals (langar), and collective worship. He appointed Guru Angad as his successor before passing away in 1539.',
        content_hindi:
          'नानक ने रावी नदी के किनारे करतारपुर बसकर ईमानदार श्रम, सामूहिक भोज (लंगर) और सामूहिक उपासना पर आधारित समुदाय स्थापित किया। १५३९ में शरीर त्यागने से पहले उन्होंने गुरु अंगद को अपना उत्तराधिकारी नियुक्त किया।',
      },
      {
        year: 'Legacy',
        title_english: 'Guru Granth Sahib and Sikh Tradition',
        title_hindi: 'गुरु ग्रंथ साहिब और सिख परंपरा',
        content_english:
          'Guru Nanak\'s 974 hymns in the Guru Granth Sahib remain central to Sikh worship worldwide. His message of one God, equality, and seva continues to inspire millions across faiths and nations.',
        content_hindi:
          'गुरु ग्रंथ साहिब में गुरु नानक के ९७४ शबद आज भी विश्व भर में सिख उपासना का केंद्र हैं। एक ईश्वर, समानता और सेवा का उनका संदेश धर्म और राष्ट्रों के पार लाखों लोगों को प्रेरित करता है।',
      },
    ],
    facts: {
      born: '15 April 1469 — Rai Bhoi di Talwandi (Nankana Sahib)',
      died: '22 September 1539 — Kartarpur, Punjab',
      full_name_english: 'Guru Nanak Dev Ji',
      full_name_hindi: 'गुरु नानक देव जी',
      court: 'Independent spiritual teacher; founder of Sikh Panth',
      works: [
        'Japji Sahib — morning prayer, opening of Guru Granth Sahib',
        'Asa di Vaar — ballad of hope and social justice',
        'Sidh Gosht — dialogue with Nath yogis',
        '974 hymns (shabads) in Guru Granth Sahib',
        'Onkar, Sodar, and other compositions',
      ],
    },
  },
  dohe: [
    {
      id: 116,
      hindi: 'ੴ\nसति नामु करता पुरखु निरभउ निरवैरु।\nअकाल मूरति अजूनी सैभं गुर प्रसादि।।',
      english: 'One Universal Creator, Truth is the Name, Creative Power, Without Fear, Without Enmity. Timeless Form, Unborn, Self-Existent, By the Guru\'s Grace.',
      meaning_hindi: 'एक सृष्टिकर्ता, सत्य ही नाम, कर्ता पुरुष, निर्भय और निर्वैर। कालातीत रूप, अजन्म और स्वयंभू — गुरु की कृपा से जाना जाता है।',
      explanation: 'The Mool Mantar — opening verse of Japji Sahib and the foundational creed of Sikhism. Every Sikh prayer begins with this declaration of the One Divine.',
      theme: 'Wisdom',
      author: 'Guru Nanak',
      authorSlug: 'guru-nanak',
      featured: true,
    },
    {
      id: 117,
      hindi: 'आदि सचु जुगादि सचु।\nहै भी सचु नानक होसी भी सचु।।',
      english: 'True in the beginning, true through the ages. True now, O Nanak, and forever true.',
      meaning_hindi: 'आदि में सत्य, युगों से सत्य। अब भी सत्य है, हे नानक, और आगे भी सत्य रहेगा।',
      explanation: 'From Japji Sahib, Pauri 1. Affirms the eternal, unchanging nature of Truth — the Divine reality that transcends time.',
      theme: 'Acceptance',
      author: 'Guru Nanak',
      authorSlug: 'guru-nanak',
      featured: true,
    },
    {
      id: 118,
      hindi: 'सो किउं मंदा आखीऐ जितु जम्महि राजान।\nजे लोक मुहि बोलन्दे, पीछै अति दुख पावहि।।',
      english: 'How can we call her bad from whose womb kings are born? How can we call the vessel bad when it holds contentment?',
      meaning_hindi: 'जिसके गर्भ से राजा जन्मते हैं, उसे बुरा कैसे कह सकते हैं? जो भांडा संतोष धारे, उसे बुरा कैसे कहें?',
      explanation: 'From Asa di Vaar. A powerful egalitarian statement — Nanak challenges the denigration of women in medieval society.',
      theme: 'Character',
      author: 'Guru Nanak',
      authorSlug: 'guru-nanak',
      featured: true,
    },
    {
      id: 119,
      hindi: 'भांडा धोंढि फिरै सभि कोई।\nनानका सचा साहिबु सचु टेक।।',
      english: 'Everyone searches for the Lord outside. Nanak says: the True Master is the True Support within.',
      meaning_hindi: 'सभी बाहर ईश्वर को ढूँढ़ते फिरते हैं। नानक कहते हैं — सच्चा स्वामी भीतर ही सच्चा आधार है।',
      explanation: 'From Asa di Vaar. Critiques outward ritual while pointing to inner realization — the Divine is not found by external searching alone.',
      theme: 'Wisdom',
      author: 'Guru Nanak',
      authorSlug: 'guru-nanak',
    },
    {
      id: 120,
      hindi: 'पत्ति तोरी न पाइओ, पेखि पेखि सभि लोच।\nनानक सो पति मिलै जि तिसु भावै सो नाच।।',
      english: 'The veil of illusion is not torn by staring again and again. Nanak says: union comes when one dances to the Beloved\'s will.',
      meaning_hindi: 'बार-बार देखने से मोह का पर्दा नहीं फटता। नानक कहते हैं — मिलन तब होता है जब प्रिय की इच्छा पर नाचो।',
      explanation: 'From Asa di Vaar. Surrender to Divine will, not intellectual striving, opens the path to union with the Beloved Lord.',
      theme: 'Love & Relationships',
      author: 'Guru Nanak',
      authorSlug: 'guru-nanak',
    },
    {
      id: 121,
      hindi: 'सुननै से सभु को उपाए।\nनानक सचे की सची काई।।',
      english: 'By listening, all creatures are created. Nanak — the True Lord\'s creation is true.',
      meaning_hindi: 'श्रवण से सब प्राणी उत्पन्न होते हैं। नानक — सच्चे की रचना भी सच्ची है।',
      explanation: 'From Japji Sahib, Pauri 8. Listening to the Divine Word is the creative force behind all existence.',
      theme: 'Wisdom',
      author: 'Guru Nanak',
      authorSlug: 'guru-nanak',
    },
    {
      id: 122,
      hindi: 'क्षत्री ब्राह्मणु थाकुरु उपदेशु चहु वर्णि।\nकोउ राजा बाहु चतुर सुजान।।',
      english: 'The Kshatriya, Brahmin, merchant, and laborer — all four castes must be guided. Some are kings, some wise with arms.',
      meaning_hindi: 'क्षत्रिय, ब्राह्मण, वैश्य और शूद्र — चारों वर्णों को मार्गदर्शन चाहिए। कोई राजा, कोई बुद्धिमान योद्धा है।',
      explanation: 'From Asa di Vaar. Acknowledges social roles while insisting all need spiritual guidance — a call for righteous leadership across society.',
      theme: 'Service',
      author: 'Guru Nanak',
      authorSlug: 'guru-nanak',
    },
    {
      id: 123,
      hindi: 'अवलि अल्लाह नूर उपाइआ, कुदरति दे सभ बंदे।\nएक नूर ते सभ जग उपजिआ, कउ भले कउ मंदे।।',
      english: 'First Allah created Light; from it all beings arose. From one Light the whole world sprang — who is good, who is bad?',
      meaning_hindi: 'पहले अल्लाह ने नूर पैदा किया, जिससे सब मनुष्य हुए। एक नूर से सारा जगत उत्पन्न — भला कौन, बुरा कौन?',
      explanation: 'From Aarti in Guru Granth Sahib. A vision of religious unity — all faiths and peoples share one Divine Light.',
      theme: 'Friendship',
      author: 'Guru Nanak',
      authorSlug: 'guru-nanak',
    },
    {
      id: 124,
      hindi: 'मन तू मंदर, तन है बाजी।\nहरि के नाम के लागे, ताहि सुहावे साजी।।',
      english: 'Mind, you are the temple; body is the musical instrument. Adorned with the Lord\'s Name, you become beautiful.',
      meaning_hindi: 'हे मन! तू मंदिर है, शरीर बाजी है — हरि के नाम से सजे तो सुंदर बनता है।',
      explanation: 'From Guru Granth Sahib. The body-mind is a sacred instrument for worship — no external temple is needed when the Name fills the heart.',
      theme: 'Character',
      author: 'Guru Nanak',
      authorSlug: 'guru-nanak',
    },
    {
      id: 125,
      hindi: 'जे को खोजै सिख, ताम नाल गुवारा।\nहरि के नाम बिनु, जिउ खारा खारा।।',
      english: 'Whoever seeks the Guru\'s teaching — be at peace with them. Without the Lord\'s Name, life is bitter as salt.',
      meaning_hindi: 'जो गुरु की शिक्षा खोजे, उसके साथ मैत्री रखो। हरि के नाम के बिना जीवन नमक जैसा कड़वा है।',
      explanation: 'From Guru Granth Sahib. Spiritual seekers are natural companions; without Divine remembrance, existence itself tastes bitter.',
      theme: 'Friendship',
      author: 'Guru Nanak',
      authorSlug: 'guru-nanak',
    },
    {
      id: 126,
      hindi: 'मके उप सूरज कैसा हाल है, धरनी धूप मल्हान।\nहरि के नाम के लागे, ताहि सुहावे साजी।।',
      english: 'The sun is the furnace, the earth the incense burner — such is the cosmic worship. Those attached to the Lord\'s Name are beautifully adorned.',
      meaning_hindi: 'सूर्य भट्टी है, पृथ्वी धूप की थाली — ऐसी है यज्ञ की व्यवस्था। हरि के नाम से जुड़े सुंदर सजते हैं।',
      explanation: 'From Aarti. Nature itself performs Divine worship — the sun and earth are sacred, not material objects to hoard.',
      theme: 'Wealth & Materialism',
      author: 'Guru Nanak',
      authorSlug: 'guru-nanak',
    },
    {
      id: 127,
      hindi: 'भांडा होए भाल तिन कउ जिनि एह भांडा धिआई।\nनानक तिन कउ सालाही, जे हरि लेखै पाई।।',
      english: 'Blessed is the vessel that meditates on the Creator. Nanak praises those who find acceptance in the Lord\'s account.',
      meaning_hindi: 'धन्य है वह भांडा जो सृष्टिकर्ता का ध्यान करे। नानक उनकी स्तुति करते हैं जो हरि की लेखा में स्वीकार हों।',
      explanation: 'From Asa di Vaar. Human life is a sacred vessel — its purpose is meditation on the Creator, not accumulation of worldly marks.',
      theme: 'Acceptance',
      author: 'Guru Nanak',
      authorSlug: 'guru-nanak',
    },
    {
      id: 128,
      hindi: 'घर की नार बहुत हितु, जा सिउ रचिआ राम।\nनानक तिन कउ सालाही, जे हरि लेखै पाई।।',
      english: 'The wife of the home is deeply loved — she through whom the Lord created all. Nanak praises those accepted in the Lord\'s account.',
      meaning_hindi: 'घर की नारी से गहरा प्रेम — जिसके द्वारा राम ने सब रचा। नानक उनकी स्तुति करते हैं जो हरि की लेखा में स्वीकार हों।',
      explanation: 'From Guru Granth Sahib. Honors the sacred role of women in creation and family life as expressions of Divine love.',
      theme: 'Love & Relationships',
      author: 'Guru Nanak',
      authorSlug: 'guru-nanak',
    },
    {
      id: 129,
      hindi: 'धौलु धरमि दया का पूतु, संतोखु थापि रखिआ।\nजिनि एहु रचि रखिआ, तिनि वेखि रखिआ।।',
      english: 'The earth is the bull of patience, born of compassion; contentment is the pole. Whoever understands this, truly understands.',
      meaning_hindi: 'पृथ्वी धैर्य का बैल, करुणा की संताति — संतोष खंभा। जो इसे समझे, वही सच में समझता है।',
      explanation: 'From Japji Sahib, Pauri 16. A cosmic metaphor — the universe rests on patience, compassion, and contentment, not force.',
      theme: 'Service',
      author: 'Guru Nanak',
      authorSlug: 'guru-nanak',
    },
    {
      id: 130,
      hindi: 'सगल संग हमरी बन आई।\nप्रभु अबिनासी सो प्रभु जाता।।',
      english: 'With all beings I am in harmony. I have known the Imperishable Lord.',
      meaning_hindi: 'सब प्राणियों के साथ मेरी मैत्री है। मैंने उस अविनाशी प्रभु को जान लिया है।',
      explanation: 'From Guru Granth Sahib. The realized soul lives in friendship with all creation, having recognized the eternal Divine within.',
      theme: 'Friendship',
      author: 'Guru Nanak',
      authorSlug: 'guru-nanak',
    },
  ],
}
