// This file contains Devanagari script — ensure UTF-8 encoding
import type { Writer } from '../types'

export const jaishankarPrasadWriter: Writer = {
  slug: 'jaishankar-prasad',
  name_english: 'Jaishankar Prasad',
  name_hindi: 'जयशंकर प्रसाद',
  era: '20th century (1890–1937)',
  language: 'Hindi',
  genre: 'Chhayavadi poetry, epic kavya, drama, philosophical verse',
  short_bio_english:
    'Pioneering Chhayavadi poet and author of Kamayani, Jaishankar Prasad wove Sanskrit elegance with modern Hindi to explore creation, desire, and the human soul.',
  short_bio_hindi:
    'छायावाद के अग्रणी कवि और कामायनी के रचयिता, जयशंकर प्रसाद ने संस्कृत की सौंदर्यता को आधुनिक हिंदी से मिलाकर सृष्टि, कामना और मानव आत्मा की खोज की।',
  biography: {
    introduction_english:
      'Jaishankar Prasad (1890–1937) was one of the four pillars of Chhayavadi Hindi poetry alongside Nirala, Pant, and Mahadevi Verma. Born in Varanasi into a prosperous merchant family that later fell on hard times, Prasad turned to literature after business failures. His magnum opus Kamayani — an epic on Manu and Shraddha after the great flood — ranks among the greatest works of Hindi literature. He also wrote plays like Skandagupta and Dhruvasvamini, and ghazals and lyrics of exquisite beauty. Prasad died young at 47, but his fusion of Vedic mythology, psychology, and lyrical Hindi reshaped modern poetry.',
    introduction_hindi:
      'जयशंकर प्रसाद (१८९०–१९३७) निराला, पंत और महादेवी वर्मा के साथ छायावादी हिंदी काव्य के चार स्तंभों में से एक थे। काशी में एक समृद्ध व्यापारी परिवार में जन्मे, व्यापार में असफलता के बाद प्रसाद ने साहित्य की ओर रुख किया। उनकी महाकाव्य कामायनी — महाप्रलय के बाद मनु और श्रद्धा की कथा — हिंदी साहित्य की महानतम कृतियों में गिनी जाती है। स्कंदगुप्त और ध्रुवस्वामिनी जैसे नाटक, और अत्यंत सुंदर ग़ज़लें भी उन्होंने लिखीं। ४७ वर्ष की छोटी आयु में निधन, पर वैदिक पौराणिकता, मनोविज्ञान और लयबद्ध हिंदी का उनका मेल आधुनिक काव्य को नया आकार दे गया।',
    timeline: [
      {
        year: '1890',
        title_english: 'Birth in Varanasi',
        title_hindi: 'वाराणसी में जन्म',
        content_english:
          'Prasad was born on 30 January 1890 in Varanasi (Kashi). His family was traditionally engaged in the perfume and grocery trade. Early exposure to Sanskrit learning and the cultural atmosphere of Kashi shaped his poetic sensibility.',
        content_hindi:
          '३० जनवरी १८९० को वाराणसी (काशी) में प्रसाद का जन्म हुआ। परिवार परंपरागत रूप से इत्र और किराना व्यापार में था। संस्कृत शिक्षा और काशी का सांस्कृतिक वातावरण ने उनकी काव्य संवेदना को आकार दिया।',
      },
      {
        year: '1910s–1920s',
        title_english: 'Turn to Literature',
        title_hindi: 'साहित्य की ओर रुख',
        content_english:
          'After family business collapsed, Prasad devoted himself to writing. He contributed to literary journals like Saraswati and became associated with the Chhayavadi movement — emphasizing beauty, symbolism, and inner experience over didactic nationalism.',
        content_hindi:
          'पारिवारिक व्यापार के पतन के बाद प्रसाद ने लेखन को समर्पित किया। सरस्वती जैसी साहित्यिक पत्रिकाओं में योगदान दिया और छायावादी आंदोलन से जुड़े — सीधे राष्ट्रवाद की जगह सौंदर्य, प्रतीक और अंतरंग अनुभव पर बल।',
      },
      {
        year: '1935',
        title_english: 'Kamayani Published',
        title_hindi: 'कामायनी का प्रकाशन',
        content_english:
          'Kamayani, Prasad\'s philosophical epic in 15 cantos, was published in 1935 after years of composition. It follows Manu\'s journey through love, contemplation, action, and renunciation after the deluge — a profound allegory of the human psyche.',
        content_hindi:
          '१५ सर्गों वाली दार्शनिक महाकाव्य कामायनी १९३५ में वर्षों की रचना के बाद प्रकाशित हुई। यह प्रलय के बाद मनु की प्रेम, चिंतन, कर्म और वैराग्य की यात्रा का चित्रण है — मानव मन की गहरी रूपक कथा।',
      },
      {
        year: '1930s',
        title_english: 'Drama and Lyric Mastery',
        title_hindi: 'नाट्य और गीत काव्य',
        content_english:
          'Prasad wrote historical plays Skandagupta and Chandragupta, and the lyrical drama Dhruvasvamini. His ghazals and songs — collected in works like Kanan Kusum — display a rare blend of Persian form and Hindi emotional depth.',
        content_hindi:
          'प्रसाद ने ऐतिहासिक नाटक स्कंदगुप्त और चंद्रगुप्त, और गीतात्मक नाटक ध्रुवस्वामिनी लिखे। उनकी ग़ज़लें और गीत — कानन कुसुम जैसी रचनाओं में — फारसी रूप और हिंदी भावगहराई का दुर्लभ मेल दिखाती हैं।',
      },
      {
        year: 'Legacy',
        title_english: 'Immortal Voice of Chhayavad',
        title_hindi: 'छायावाद की अमर आवाज़',
        content_english:
          'Prasad died on 15 November 1937 in Varanasi. Kamayani remains essential reading in Hindi literature. He is remembered as the poet who brought epic grandeur and psychological depth to modern Hindi — a bridge between Vedic vision and contemporary sensibility.',
        content_hindi:
          '१५ नवंबर १९३७ को वाराणसी में प्रसाद का निधन हुआ। कामायनी आज भी हिंदी साहित्य की अनिवार्य पठन सामग्री है। वे उस कवि के रूप में याद किए जाते हैं जिन्होंने आधुनिक हिंदी में महाकाव्य गरिमा और मनोवैज्ञानिक गहराई लाई — वैदिक दृष्टि और समकालीन संवेदना के सेतु।',
      },
    ],
    facts: {
      born: '30 January 1890 — Varanasi, Uttar Pradesh',
      died: '15 November 1937 — Varanasi (aged 47)',
      full_name_english: 'Jaishankar Prasad',
      full_name_hindi: 'जयशंकर प्रसाद',
      court: 'Chhayavadi literary circle; Saraswati journal; independent poet',
      works: [
        'Kamayani — philosophical epic in 15 cantos (1935)',
        'Skandagupta — historical play',
        'Chandragupta — historical play',
        'Dhruvasvamini — lyrical drama',
        'Jharnaa — poetry collection',
        'Kanan Kusum — ghazals and lyrics',
        'Lahar — poetry collection',
      ],
    },
  },
  dohe: [
    {
      id: 401,
      hindi: 'मन\nही सृष्टि का\nस्रोत है।',
      english: 'The mind alone is the source of creation.',
      meaning_hindi: 'मन ही सृष्टि का स्रोत है — बाहर जो दिखता है, भीतर से उगता है।',
      explanation: 'Central to Kamayani — Prasad explores how inner consciousness shapes outer reality, echoing Vedic ideas of mind as the ground of existence.',
      theme: 'Wisdom',
      author: 'Jaishankar Prasad',
      authorSlug: 'jaishankar-prasad',
      featured: true,
    },
    {
      id: 402,
      hindi: 'कामना\nजीवन की\nअग्नि है।',
      english: 'Desire is the fire that drives life — and must be understood, not denied.',
      meaning_hindi: 'कामना जीवन की अग्नि है — इसे नकारो नहीं, समझो।',
      explanation: 'The canto Kama in Kamayani treats desire not as sin but as a force to be integrated — Prasad\'s psychological sophistication was ahead of his time.',
      theme: 'Acceptance',
      author: 'Jaishankar Prasad',
      authorSlug: 'jaishankar-prasad',
    },
    {
      id: 403,
      hindi: 'प्रकृति\nमाँ की तरह\nपालती है।',
      english: 'Nature nurtures like a mother — in her lap all beings find rest.',
      meaning_hindi: 'प्रकृति माँ की तरह पालती है — उसकी गोद में सब विश्राम पाते हैं।',
      explanation: 'Prasad\'s Chhayavadi imagery constantly returns to forests, rivers, and seasons as symbols of renewal and the eternal feminine.',
      theme: 'Acceptance',
      author: 'Jaishankar Prasad',
      authorSlug: 'jaishankar-prasad',
    },
    {
      id: 404,
      hindi: 'श्रद्धा\nअंधकार में\nदीपक है।',
      english: 'Faith is the lamp in darkness — it guides when reason falters.',
      meaning_hindi: 'श्रद्धा अंधकार में दीपक है — तर्क थक जाए तब भी मार्ग दिखाती है।',
      explanation: 'Shraddha, the feminine principle in Kamayani, embodies faith that sustains Manu through catastrophe — Prasad\'s tribute to trusting devotion.',
      theme: 'Wisdom',
      author: 'Jaishankar Prasad',
      authorSlug: 'jaishankar-prasad',
      featured: true,
    },
    {
      id: 405,
      hindi: 'वैराग्य\nभागने का नाम\nनहीं।',
      english: 'Renunciation is not escape — it is mastery over attachment.',
      meaning_hindi: 'वैराग्य भागने का नाम नहीं — आसक्ति पर विजय है।',
      explanation: 'In Kamayani\'s final cantos, Prasad distinguishes true detachment from mere withdrawal — wisdom lies in engaged freedom.',
      theme: 'Character',
      author: 'Jaishankar Prasad',
      authorSlug: 'jaishankar-prasad',
    },
    {
      id: 406,
      hindi: 'कवि\nसमय का\nदर्पण है।',
      english: 'The poet mirrors the age — reflecting its beauty and its wounds.',
      meaning_hindi: 'कवि समय का दर्पण है — युग की सुंदरता और घाव दोनों दिखाता है।',
      explanation: 'Prasad saw the poet as seer — Chhayavad demanded that poetry capture the inner life of an era, not merely its political surface.',
      theme: 'Wisdom',
      author: 'Jaishankar Prasad',
      authorSlug: 'jaishankar-prasad',
    },
    {
      id: 407,
      hindi: 'प्रेम\nआत्मा को\nजोड़ता है।',
      english: 'Love binds souls across time and separation.',
      meaning_hindi: 'प्रेम आत्माओं को समय और विरह पार कर जोड़ता है।',
      explanation: 'From Kamayani to his ghazals, Prasad treated love as the thread connecting individual consciousness to the universal.',
      theme: 'Love & Relationships',
      author: 'Jaishankar Prasad',
      authorSlug: 'jaishankar-prasad',
    },
    {
      id: 408,
      hindi: 'संघर्ष\nही जीवन\nका नाम है।',
      english: 'Struggle is the very name of life — accept it with courage.',
      meaning_hindi: 'संघर्ष ही जीवन का नाम है — साहस से स्वीकार करो।',
      explanation: 'Manu\'s post-deluge journey mirrors Prasad\'s own battles with poverty and illness — suffering refined rather than defeated the spirit.',
      theme: 'Character',
      author: 'Jaishankar Prasad',
      authorSlug: 'jaishankar-prasad',
    },
    {
      id: 409,
      hindi: 'सौंदर्य\nसत्य का\nरूप है।',
      english: 'Beauty is truth made visible — the Chhayavadi creed.',
      meaning_hindi: 'सौंदर्य सत्य का दृश्य रूप है — छायावाद का मूल सिद्धांत।',
      explanation: 'Prasad and his Chhayavadi peers believed aesthetic experience reveals deeper reality — form and meaning are inseparable.',
      theme: 'Wisdom',
      author: 'Jaishankar Prasad',
      authorSlug: 'jaishankar-prasad',
      featured: true,
    },
    {
      id: 410,
      hindi: 'मित्र\nविपत्ति में\nपहचाने जाते हैं।',
      english: 'Friends reveal themselves in adversity, not in prosperity.',
      meaning_hindi: 'मित्र विपत्ति में पहचाने जाते हैं, सुख में नहीं।',
      explanation: 'Drawing on classical wisdom, Prasad applied the test of friendship to human relationships in both his epics and personal life.',
      theme: 'Friendship',
      author: 'Jaishankar Prasad',
      authorSlug: 'jaishankar-prasad',
    },
    {
      id: 411,
      hindi: 'धन\nसब कुछ\nनहीं है।',
      english: 'Wealth is not everything — the soul\'s riches exceed gold.',
      meaning_hindi: 'धन सब कुछ नहीं — आत्मा का धन सोने से बड़ा है।',
      explanation: 'After losing family fortune, Prasad knew materially that inner cultivation outlasts mercantile success.',
      theme: 'Wealth & Materialism',
      author: 'Jaishankar Prasad',
      authorSlug: 'jaishankar-prasad',
    },
    {
      id: 412,
      hindi: 'चिंतन\nमार्ग प्रशस्त\nकरता है।',
      english: 'Contemplation clears the path — stillness precedes action.',
      meaning_hindi: 'चिंतन मार्ग प्रशस्त करता है — कर्म से पहले मौन आवश्यक है।',
      explanation: 'The Chinta canto of Kamayani celebrates reflective thought as necessary counterpart to desire and deed.',
      theme: 'Wisdom',
      author: 'Jaishankar Prasad',
      authorSlug: 'jaishankar-prasad',
    },
    {
      id: 413,
      hindi: 'सेवा\nही उपासना\nकी पराकाष्ठा है।',
      english: 'Service is the highest worship — action dedicated to the good.',
      meaning_hindi: 'सेवा ही उपासना की पराकाष्ठा है — भलाई के लिए समर्पित कर्म।',
      explanation: 'Prasad\'s historical plays honor rulers who served the people — he linked political virtue to selfless duty.',
      theme: 'Service',
      author: 'Jaishankar Prasad',
      authorSlug: 'jaishankar-prasad',
    },
    {
      id: 414,
      hindi: 'विरह\nप्रेम की\nगहराई है।',
      english: 'Separation deepens love — absence teaches the heart its truth.',
      meaning_hindi: 'विरह प्रेम की गहराई है — अनुपस्थिति हृदय को उसका सत्य सिखाती है।',
      explanation: 'Prasad\'s ghazals master the aesthetics of longing — viraha is not loss but intensification of connection.',
      theme: 'Love & Relationships',
      author: 'Jaishankar Prasad',
      authorSlug: 'jaishankar-prasad',
    },
    {
      id: 415,
      hindi: 'मृत्यु\nअंत नहीं,\nरूपांतर है।',
      english: 'Death is not an end but transformation — life flows onward.',
      meaning_hindi: 'मृत्यु अंत नहीं, रूपांतर है — जीवन प्रवाह बना रहता है।',
      explanation: 'Prasad\'s Vedic outlook treats mortality as passage — Kamayani begins after destruction, affirming cyclical renewal.',
      theme: 'Acceptance',
      author: 'Jaishankar Prasad',
      authorSlug: 'jaishankar-prasad',
    },
  ],
}
