// This file contains Devanagari script — ensure UTF-8 encoding
import type { Writer } from '../types'

export const kalamWriter: Writer = {
  slug: 'kalam',
  name_english: 'A. P. J. Abdul Kalam',
  name_hindi: 'ए. पी. जे. अब्दुल कलाम',
  era: '20th–21st century (1931–2015)',
  language: 'Hindi / English',
  genre: 'Inspirational prose, scientific vision, youth philosophy',
  short_bio_english:
    'Missile Man of India and beloved President, Kalam transformed science into service and inspired millions of young minds to dream, build, and serve the nation.',
  short_bio_hindi:
    'भारत के मिसाइल मैन और प्रिय राष्ट्रपति, कलाम ने विज्ञान को सेवा में बदला और लाखों युवाओं को सपने देखने, निर्माण करने और राष्ट्र की सेवा करने के लिए प्रेरित किया।',
  biography: {
    introduction_english:
      'Avul Pakir Jainulabdeen Abdul Kalam (1931–2015) was one of India\'s most beloved scientists and statesmen. Born in Rameswaram, Tamil Nadu, to a humble boat-owner\'s family, he rose through ISRO and DRDO to lead India\'s missile and space programmes — earning the title "Missile Man of India." As the 11th President of India (2002–2007), he connected with children and youth across the country, urging them to dream big and work with integrity. His autobiography Wings of Fire and books like Ignited Minds became guiding texts for a generation. Kalam received the Bharat Ratna and remains a symbol of humility, hard work, and patriotic vision.',
    introduction_hindi:
      'अवुल पकीर जैनुलाब्दीन अब्दुल कलाम (१९३१–२०१५) भारत के सबसे प्रिय वैज्ञानिकों और राजनेताओं में से एक थे। तमिलनाडु के रामेश्वरम में एक साधारण नाविक परिवार में जन्मे, वे ISRO और DRDO से होते हुए भारत के मिसाइल और अंतरिक्ष कार्यक्रमों के नेतृत्व तक पहुँचे — "मिसाइल मैन ऑफ इंडिया" की उपाधि पाई। भारत के ११वें राष्ट्रपति (२००२–२००७) के रूप में उन्होंने देश भर के बच्चों और युवाओं से जुड़कर उन्हें बड़े सपने देखने और ईमानदारी से काम करने की प्रेरणा दी। उनकी आत्मकथा विंग्स ऑफ फायर और इग्नाइटेड माइंड्स जैसी पुस्तकें एक पीढ़ी के मार्गदर्शक बनीं। कलाम को भारत रत्न मिला और वे विनम्रता, परिश्रम और देशभक्त दृष्टि के प्रतीक बने।',
    timeline: [
      {
        year: '1931',
        title_english: 'Birth in Rameswaram',
        title_hindi: 'रामेश्वरम में जन्म',
        content_english:
          'Kalam was born on 15 October 1931 in Rameswaram, Tamil Nadu. His father Jainulabdeen was a boat owner; his mother Ashiamma sold household items. Poverty did not dim his hunger for learning — he distributed newspapers to fund his education and walked miles to school.',
        content_hindi:
          '१५ अक्टूबर १९३१ को तमिलनाडु के रामेश्वरम में कलाम का जन्म हुआ। उनके पिता जैनुलाब्दीन नाविक थे; माँ अशियम्मा घरेलू सामान बेचती थीं। गरीबी ने सीखने की लालसा कम नहीं की — उन्होंने अखबार बाँटकर पढ़ाई का खर्च उठाया और मीलों पैदल स्कूल जाते थे।',
      },
      {
        year: '1960s–1980s',
        title_english: 'ISRO, DRDO, and the Space Dream',
        title_hindi: 'ISRO, DRDO और अंतरिक्ष का सपना',
        content_english:
          'After graduating in aeronautical engineering from Madras Institute of Technology, Kalam joined DRDO and later ISRO. He played a pivotal role in India\'s first satellite launch vehicle SLV-3 and the Pokhran nuclear tests, building indigenous capability in rocketry and defence technology.',
        content_hindi:
          'मद्रास इंस्टीट्यूट ऑफ टेक्नोलॉजी से एयरोनॉटिकल इंजीनियरिंग करने के बाद कलाम DRDO और बाद में ISRO में शामिल हुए। भारत के पहले उपग्रह प्रक्षेपण यान SLV-3 और पोखरण परमाणु परीक्षणों में उनकी महत्वपूर्ण भूमिका रही — रॉकेटरी और रक्षा तकनीक में स्वदेशी क्षमता का निर्माण।',
      },
      {
        year: '1990s',
        title_english: 'Missile Man of India',
        title_hindi: 'मिसाइल मैन ऑफ इंडिया',
        content_english:
          'As chief of DRDO and scientific adviser to the Defence Minister, Kalam led the Integrated Guided Missile Development Programme — Agni, Prithvi, Akash, Trishul, Nag. India\'s self-reliance in strategic defence earned him nationwide admiration and the Bharat Ratna in 1997.',
        content_hindi:
          'DRDO के प्रमुख और रक्षा मंत्री के वैज्ञानिक सलाहकार के रूप में कलाम ने एकीकृत निर्देशित मिसाइल विकास कार्यक्रम — अग्नि, पृथ्वी, आकाश, त्रिशूल, नाग — का नेतृत्व किया। रणनीतिक रक्षा में भारत की आत्मनिर्भरता ने उन्हें देशव्यापी सम्मान और १९९७ में भारत रत्न दिलाया।',
      },
      {
        year: '2002–2007',
        title_english: 'President of India — People\'s President',
        title_hindi: 'भारत के राष्ट्रपति — जनता के राष्ट्रपति',
        content_english:
          'Elected the 11th President of India, Kalam visited schools and universities relentlessly, speaking to students about dreams, discipline, and national development. His warmth and accessibility earned him the affectionate title "People\'s President."',
        content_hindi:
          'भारत के ११वें राष्ट्रपति चुने गए, कलाम ने लगातार स्कूल-विश्वविद्यालयों का दौरा किया, छात्रों से सपनों, अनुशासन और राष्ट्रीय विकास पर बात की। उनकी सादगी और पहुँच ने "जनता के राष्ट्रपति" की उपाधि दिलाई।',
      },
      {
        year: 'Legacy',
        title_english: 'Igniting Minds Forever',
        title_hindi: 'मन प्रज्वलित — अमर प्रेरणा',
        content_english:
          'Kalam died on 27 July 2015 while delivering a lecture at IIM Shillong — teaching until his last breath. Wings of Fire, Ignited Minds, and India 2020 continue to inspire youth. He remains the scientist-statesman who proved that greatness grows from humble roots and honest work.',
        content_hindi:
          '२७ जुलाई २०१५ को IIM शिलांग में व्याख्यान देते हुए कलाम का निधन हुआ — अंतिम साँस तक शिक्षण। विंग्स ऑफ फायर, इग्नाइटेड माइंड्स और इंडिया २०२० युवाओं को प्रेरित करते रहते हैं। वे वैज्ञानिक-राजनेता हैं जिन्होंने साबित किया कि महानता साधारण जड़ों और ईमानदार परिश्रम से उगती है।',
      },
    ],
    facts: {
      born: '15 October 1931 — Rameswaram, Tamil Nadu',
      died: '27 July 2015 — Shillong, Meghalaya (aged 83)',
      full_name_english: 'Avul Pakir Jainulabdeen Abdul Kalam',
      full_name_hindi: 'अवुल पकीर जैनुलाब्दीन अब्दुल कलाम',
      court: 'ISRO; DRDO; 11th President of India (2002–2007)',
      works: [
        'Wings of Fire — autobiography (1999)',
        'Ignited Minds — vision for youth (2002)',
        'India 2020 — development roadmap',
        'Turning Points — presidential memoir',
        'My Journey — reflections on life',
        'Transcendence — spiritual reflections',
      ],
    },
  },
  dohe: [
    {
      id: 386,
      hindi: 'सपने वो नहीं जो\nनींद में आएँ।',
      english: 'Dreams are not those that come in sleep — they are the ones that keep you awake.',
      meaning_hindi: 'सपने वो नहीं जो नींद में आएँ — वो जो जगाए रखें, वही सच्चे सपने हैं।',
      explanation: 'Kalam\'s most quoted line urges youth to pursue visions so compelling they drive action — passive dreaming differs from purposeful aspiration.',
      theme: 'Wisdom',
      author: 'A. P. J. Abdul Kalam',
      authorSlug: 'kalam',
      featured: true,
    },
    {
      id: 387,
      hindi: 'कठिनाइयाँ\nअवसर का रूप हैं।',
      english: 'Difficulties are opportunities in disguise.',
      meaning_hindi: 'कठिनाइयाँ छिपे हुए अवसर हैं — उन्हें पहचानो और आगे बढ़ो।',
      explanation: 'From his own life of hardship in Rameswaram to leading missile programmes — Kalam saw obstacles as tests that forge capability.',
      theme: 'Character',
      author: 'A. P. J. Abdul Kalam',
      authorSlug: 'kalam',
    },
    {
      id: 388,
      hindi: 'ज्ञान\nसबसे बड़ा धन है।',
      english: 'Knowledge is the greatest wealth — no one can steal it from you.',
      meaning_hindi: 'ज्ञान सबसे बड़ा धन है — इसे कोई छीन नहीं सकता।',
      explanation: 'Kalam consistently told students that education outlasts material possessions — learning is the one asset that grows when shared.',
      theme: 'Wealth & Materialism',
      author: 'A. P. J. Abdul Kalam',
      authorSlug: 'kalam',
      featured: true,
    },
    {
      id: 389,
      hindi: 'विज्ञान\nमानवता की सेवा है।',
      english: 'Science is humanity\'s tool for service, not destruction.',
      meaning_hindi: 'विज्ञान मानवता की सेवा का साधन है, विनाश का नहीं।',
      explanation: 'As a defence scientist who championed peaceful applications, Kalam believed technology must uplift society and protect the vulnerable.',
      theme: 'Service',
      author: 'A. P. J. Abdul Kalam',
      authorSlug: 'kalam',
    },
    {
      id: 390,
      hindi: 'युवा\nराष्ट्र का भविष्य हैं।',
      english: 'Youth are the future of the nation — invest in them.',
      meaning_hindi: 'युवा राष्ट्र का भविष्य हैं — उनमें निवेश करो।',
      explanation: 'Kalam spent his presidency and beyond speaking directly to students — he saw nurturing young minds as India\'s highest national priority.',
      theme: 'Service',
      author: 'A. P. J. Abdul Kalam',
      authorSlug: 'kalam',
    },
    {
      id: 391,
      hindi: 'ईमानदारी\nसफलता की नींव है।',
      english: 'Integrity is the foundation of lasting success.',
      meaning_hindi: 'ईमानदारी स्थायी सफलता की नींव है — बिना चरित्र के कोई उपलब्धि टिकती नहीं।',
      explanation: 'Kalam refused corruption and shortcuts — his reputation for honesty was as celebrated as his scientific achievements.',
      theme: 'Character',
      author: 'A. P. J. Abdul Kalam',
      authorSlug: 'kalam',
    },
    {
      id: 392,
      hindi: 'अकेले\nकुछ नहीं, साथ\nसब कुछ।',
      english: 'Alone we can do little; together we can achieve everything.',
      meaning_hindi: 'अकेले थोड़ा, साथ मिलकर सब कुछ — टीमवर्क से ही महान कार्य होते हैं।',
      explanation: 'Kalam credited ISRO and DRDO teams for India\'s achievements — he knew collective effort transforms individual talent into national triumph.',
      theme: 'Friendship',
      author: 'A. P. J. Abdul Kalam',
      authorSlug: 'kalam',
    },
    {
      id: 393,
      hindi: 'विफलता\nसफलता की सीढ़ी है।',
      english: 'Failure is a stepping stone to success, not a dead end.',
      meaning_hindi: 'विफलता सफलता की सीढ़ी है, अंतिम मंजिल नहीं — सीखो और फिर उठो।',
      explanation: 'After early SLV-3 setbacks, Kalam persisted — he taught that every failed attempt carries lessons for the next launch.',
      theme: 'Acceptance',
      author: 'A. P. J. Abdul Kalam',
      authorSlug: 'kalam',
    },
    {
      id: 394,
      hindi: 'स्वदेशी\nस्वाभिमान की बात है।',
      english: 'Self-reliance is a matter of national self-respect.',
      meaning_hindi: 'आत्मनिर्भरता राष्ट्रीय स्वाभिमान की बात है — अपनी ताकत पर भरोसा करो।',
      explanation: 'The missile programme embodied Kalam\'s vision — India must build its own technology rather than depend on foreign powers for security.',
      theme: 'Character',
      author: 'A. P. J. Abdul Kalam',
      authorSlug: 'kalam',
      featured: true,
    },
    {
      id: 395,
      hindi: 'शिक्षक\nभविष्य बनाते हैं।',
      english: 'Teachers shape the future — they are nation-builders.',
      meaning_hindi: 'शिक्षक भविष्य बनाते हैं — वे राष्ट्र निर्माता हैं।',
      explanation: 'Kalam revered his teachers in Rameswaram and beyond — he often said a good teacher creates a thousand capable citizens.',
      theme: 'Service',
      author: 'A. P. J. Abdul Kalam',
      authorSlug: 'kalam',
    },
    {
      id: 396,
      hindi: 'विनम्रता\nमहानता की पहचान है।',
      english: 'Humility marks true greatness.',
      meaning_hindi: 'विनम्रता सच्ची महानता की पहचान है — अहंकार छोटा करता है।',
      explanation: 'Despite Bharat Ratna and the presidency, Kalam lived simply — his humility made him accessible to the poorest student and the richest industrialist alike.',
      theme: 'Character',
      author: 'A. P. J. Abdul Kalam',
      authorSlug: 'kalam',
    },
    {
      id: 397,
      hindi: 'प्रेम\nसबसे शक्तिशाली\nशक्ति है।',
      english: 'Love is the most powerful force — it transforms hearts and nations.',
      meaning_hindi: 'प्रेम सबसे शक्तिशाली शक्ति है — यह हृदय और राष्ट्र दोनों बदलता है।',
      explanation: 'Kalam spoke of love for the motherland, for learning, and for fellow citizens as the fuel that drives meaningful achievement.',
      theme: 'Love & Relationships',
      author: 'A. P. J. Abdul Kalam',
      authorSlug: 'kalam',
    },
    {
      id: 398,
      hindi: 'समय\nकभी वापस नहीं\nआता।',
      english: 'Time never returns — use every moment wisely.',
      meaning_hindi: 'समय कभी वापस नहीं आता — हर पल समझदारी से उपयोग करो।',
      explanation: 'Kalam\'s punishing schedule of lectures and mentoring reflected his belief that youth must not waste the irreplaceable gift of time.',
      theme: 'Wisdom',
      author: 'A. P. J. Abdul Kalam',
      authorSlug: 'kalam',
    },
    {
      id: 399,
      hindi: 'आत्मविश्वास\nसपनों को उड़ान देता है।',
      english: 'Self-confidence gives wings to dreams.',
      meaning_hindi: 'आत्मविश्वास सपनों को उड़ान देता है — पहले खुद पर विश्वास करो।',
      explanation: 'Kalam told countless students from small towns that their background does not limit their potential — belief precedes achievement.',
      theme: 'Wisdom',
      author: 'A. P. J. Abdul Kalam',
      authorSlug: 'kalam',
    },
    {
      id: 400,
      hindi: 'देश\nसबसे पहले।',
      english: 'The nation comes first — always.',
      meaning_hindi: 'देश सबसे पहले — हमेशा — व्यक्तिगत लाभ से ऊपर राष्ट्र हित।',
      explanation: 'Kalam\'s entire career was devoted to India\'s security and development — he asked every citizen to place national interest above personal gain.',
      theme: 'Service',
      author: 'A. P. J. Abdul Kalam',
      authorSlug: 'kalam',
    },
  ],
}
