// This file contains Devanagari script — ensure UTF-8 encoding
import type { Writer } from '../types'

export const maithiliSharanGuptWriter: Writer = {
  slug: 'maithili-sharan-gupt',
  name_english: 'Maithili Sharan Gupt',
  name_hindi: 'मैथिलीशरण गुप्त',
  era: '20th century (1886–1964)',
  language: 'Hindi (Khari Boli)',
  genre: 'Khari Boli poetry, nationalist verse, epic narrative, social reform poetry',
  short_bio_english:
    'Father of Khari Boli poetry and author of Bharat-Bharati, Maithili Sharan Gupt gave modern Hindi its voice of patriotism, dignity, and social conscience.',
  short_bio_hindi:
    'खड़ी बोली काव्य के जनक और भारत-भारती के रचयिता, मैथिलीशरण गुप्त ने आधुनिक हिंदी को देशभक्ति, गरिमा और सामाजिक चेतना की आवाज़ दी।',
  biography: {
    introduction_english:
      'Maithili Sharan Gupt (1886–1964) was the foremost poet of Khari Boli Hindi in the early 20th century and a pioneer of nationalist poetry. Born in Chirgaon, Jhansi, he wrote in the everyday Hindi of North India rather than the Braj or Sanskritized registers favored by earlier poets. His Bharat-Bharati (1912) stirred patriotic fervor during the freedom struggle; Saket retells the Ramayana from Urmila\'s perspective; Yashodhara explores the Buddha\'s wife. Gupt received the Padma Bhushan and was honored as Rashtrakavi. His accessible, moral, and emotionally direct verse made Hindi poetry the language of the people.',
    introduction_hindi:
      'मैथिलीशरण गुप्त (१८८६–१९६४) बीसवीं सदी की शुरुआत में खड़ी बोली हिंदी के प्रमुख कवि और राष्ट्रवादी काव्य के अग्रदूत थे। झांसी के चिरगाँव में जन्मे, उन्होंने पूर्व कवियों की ब्रज या संस्कृतनिष्ठ भाषा की जगह उत्तर भारत की रोज़मर्रा की हिंदी अपनाई। भारत-भारती (१९१२) ने स्वतंत्रता संग्राम में देशभक्ति की लहर छोड़ी; साकेत रामायण को उर्मिला के दृष्टिकोण से कहता है; यशोधरा बुद्ध की पत्नी की कथा है। गुप्त को पद्म भूषण मिला और राष्ट्रकवि की उपाधि दी गई। उनका सरल, नैतिक और भावप्रधान काव्य हिंदी को जन-भाषा बना गया।',
    timeline: [
      {
        year: '1886',
        title_english: 'Birth in Chirgaon, Jhansi',
        title_hindi: 'झांसी के चिरगाँव में जन्म',
        content_english:
          'Gupt was born on 3 August 1886 in Chirgaon near Jhansi. His father was a landlord; the family valued education and Sanskrit learning. Gupt studied privately and developed an early passion for poetry and Indian history.',
        content_hindi:
          '३ अगस्त १८८६ को झांसी के निकट चिरगाँव में गुप्त का जन्म हुआ। पिता जमींदार थे; परिवार शिक्षा और संस्कृत सीखने को महत्व देता था। गुप्त ने निजी रूप से पढ़ाई की और काव्य व भारतीय इतिहास के प्रति प्रारंभिक लगाव विकसित किया।',
      },
      {
        year: '1910s',
        title_english: 'Khari Boli and Bharat-Bharati',
        title_hindi: 'खड़ी बोली और भारत-भारती',
        content_english:
          'Gupt championed Khari Boli as the vehicle of modern Hindi poetry. Bharat-Bharati, published in 1912, invoked India\'s glorious past to inspire resistance to colonial rule. Its stirring verses were recited at nationalist gatherings across North India.',
        content_hindi:
          'गुप्त ने खड़ी बोली को आधुनिक हिंदी काव्य का माध्यम बनाया। १९१२ में प्रकाशित भारत-भारती ने भारत के गौरवशाली अतीत को विदेशी शासन के विरोध में प्रेरणा दी। इसकी उत्साहभरी पंक्तियाँ उत्तर भारत में राष्ट्रवादी सभाओं में सुनाई जाती थीं।',
      },
      {
        year: '1930s',
        title_english: 'Saket and Epic Retellings',
        title_hindi: 'साकेत और महाकाव्य पुनर्कथा',
        content_english:
          'Saket, published in 1931, reimagines the Ramayana through Urmila\'s silent sacrifice — giving voice to the overlooked heroine. Gupt also wrote Yashodhara on the Buddha\'s consort and Vishvarajya on Ashoka, blending epic form with humanist empathy.',
        content_hindi:
          '१९३१ में प्रकाशित साकेत ने रामायण को उर्मिला के मौन बलिदान से देखा — अनदेखी नायिका को आवाज़ दी। गुप्त ने बुद्ध की पत्नी पर यशोधरा और अशोक पर विश्वराज्य भी लिखा — महाकाव्य रूप में मानवतावादी संवेदना।',
      },
      {
        year: '1954',
        title_english: 'Padma Bhushan and Rashtrakavi',
        title_hindi: 'पद्म भूषण और राष्ट्रकवि',
        content_english:
          'Gupt received the Padma Bhushan in 1954 for his contribution to Hindi literature. He was widely honored as Rashtrakavi — a poet who spoke for the nation in language the common people understood and loved.',
        content_hindi:
          '१९५४ में हिंदी साहित्य में योगदान के लिए गुप्त को पद्म भूषण मिला। उन्हें व्यापक रूप से राष्ट्रकवि के रूप में सम्मानित किया गया — ऐसे कवि जिन्होंने राष्ट्र की बात आम जन की समझ और प्रेम की भाषा में कही।',
      },
      {
        year: 'Legacy',
        title_english: 'People\'s Poet of Hindi',
        title_hindi: 'हिंदी के जन-कवि',
        content_english:
          'Gupt died on 12 December 1964 in Varanasi. His poems remain staples of Hindi textbooks and public recitation. He is remembered as the poet who democratized Hindi verse — making patriotism, morality, and myth accessible to every reader.',
        content_hindi:
          '१२ दिसंबर १९६४ को वाराणसी में गुप्त का निधन हुआ। उनकी कविताएँ आज भी हिंदी पाठ्यक्रम और सार्वजनिक पाठ का अंग हैं। वे उस कवि के रूप में याद किए जाते हैं जिन्होंने हिंदी काव्य को जनतंत्री बनाया — देशभक्ति, नैतिकता और पौराणिकता को हर पाठक के लिए सुलभ किया।',
      },
    ],
    facts: {
      born: '3 August 1886 — Chirgaon, Jhansi, Uttar Pradesh',
      died: '12 December 1964 — Varanasi, Uttar Pradesh (aged 78)',
      full_name_english: 'Maithili Sharan Gupt',
      full_name_hindi: 'मैथिलीशरण गुप्त',
      court: 'Independent nationalist poet; Rashtrakavi (National Poet)',
      works: [
        'Bharat-Bharati — nationalist poetry (1912)',
        'Saket — Ramayana from Urmila\'s perspective (1931)',
        'Yashodhara — epic on the Buddha\'s wife',
        'Vishvarajya — epic on Emperor Ashoka',
        'Rang mein Bhang — social reform poetry',
        'Plassey ka Yuddha — historical narrative poem',
        'Dwapar — Mahabharata-era poetry',
      ],
    },
  },
  dohe: [
    {
      id: 416,
      hindi: 'भारत\nमाता की\nजय हो।',
      english: 'Victory to Mother India — the land that nourishes all.',
      meaning_hindi: 'भारत माता की जय — वह धरती जो सबको पालती है।',
      explanation: 'From Bharat-Bharati — Gupt\'s iconic invocation of the nation as mother became a rallying cry during the freedom struggle.',
      theme: 'Service',
      author: 'Maithili Sharan Gupt',
      authorSlug: 'maithili-sharan-gupt',
      featured: true,
    },
    {
      id: 417,
      hindi: 'नारी\nसम्मान\nसभ्यता की\nपहचान है।',
      english: 'Honoring women marks a civilized society.',
      meaning_hindi: 'नारी का सम्मान सभ्यता की पहचान है — जहाँ स्त्री अपमानित, वहाँ संस्कृति नहीं।',
      explanation: 'Gupt was a progressive voice for women\'s dignity — Saket and Yashodhara center female experience long ignored by epic tradition.',
      theme: 'Character',
      author: 'Maithili Sharan Gupt',
      authorSlug: 'maithili-sharan-gupt',
    },
    {
      id: 418,
      hindi: 'सत्य\nकभी पराजित\nनहीं होता।',
      english: 'Truth is never defeated — it may be delayed, never destroyed.',
      meaning_hindi: 'सत्य कभी पराजित नहीं होता — विलंबित हो सकता है, नष्ट नहीं।',
      explanation: 'A recurring Gupt theme in nationalist and moral verse — justice and honesty prevail despite temporary oppression.',
      theme: 'Wisdom',
      author: 'Maithili Sharan Gupt',
      authorSlug: 'maithili-sharan-gupt',
      featured: true,
    },
    {
      id: 419,
      hindi: 'बलिदान\nप्रेम की\nपराकाष्ठा है।',
      english: 'Sacrifice is love\'s highest expression — silent and selfless.',
      meaning_hindi: 'बलिदान प्रेम की पराकाष्ठा है — मौन और निःस्वार्थ।',
      explanation: 'Urmila in Saket embodies this truth — Gupt celebrated those who serve without recognition or reward.',
      theme: 'Love & Relationships',
      author: 'Maithili Sharan Gupt',
      authorSlug: 'maithili-sharan-gupt',
    },
    {
      id: 420,
      hindi: 'गरीब\nका दुख\nराष्ट्र का\nदुख है।',
      english: 'The poor man\'s suffering is the nation\'s suffering.',
      meaning_hindi: 'गरीब का दुख राष्ट्र का दुख है — जब तक कोई भूखा, कोई भी समृद्ध नहीं।',
      explanation: 'Gupt\'s social conscience ran deep — he linked national freedom to economic justice and care for the marginalized.',
      theme: 'Service',
      author: 'Maithili Sharan Gupt',
      authorSlug: 'maithili-sharan-gupt',
    },
    {
      id: 421,
      hindi: 'अतीत\nसे सीखो,\nभविष्य\nबनाओ।',
      english: 'Learn from the past to build the future.',
      meaning_hindi: 'अतीत से सीखो, भविष्य बनाओ — इतिहास प्रेरणा है, बोझ नहीं।',
      explanation: 'Bharat-Bharati drew on India\'s ancient glory not for nostalgia but to inspire contemporary renewal and self-respect.',
      theme: 'Wisdom',
      author: 'Maithili Sharan Gupt',
      authorSlug: 'maithili-sharan-gupt',
    },
    {
      id: 422,
      hindi: 'सादगी\nसौंदर्य\nसे बढ़कर\nहै।',
      english: 'Simplicity surpasses ornament — plain truth moves the heart.',
      meaning_hindi: 'सादगी सौंदर्य से बढ़कर है — सीधा सत्य हृदय छूता है।',
      explanation: 'Gupt deliberately chose Khari Boli\'s directness over ornate Sanskritized Hindi — accessibility was his aesthetic and moral choice.',
      theme: 'Character',
      author: 'Maithili Sharan Gupt',
      authorSlug: 'maithili-sharan-gupt',
    },
    {
      id: 423,
      hindi: 'मित्र\nविश्वास\nकी नींव\nपर टिकते\nहैं।',
      english: 'Friendships stand on trust — without it, bonds crumble.',
      meaning_hindi: 'मित्रता विश्वास की नींव पर टिकती है — बिना इसके रिश्ते टूट जाते हैं।',
      explanation: 'Gupt\'s narrative poems explore loyalty and betrayal — he valued steadfast companionship as a pillar of character.',
      theme: 'Friendship',
      author: 'Maithili Sharan Gupt',
      authorSlug: 'maithili-sharan-gupt',
    },
    {
      id: 424,
      hindi: 'धन\nसेवा\nके लिए\nजमा करो।',
      english: 'Accumulate wealth only to serve others.',
      meaning_hindi: 'धन सेवा के लिए जमा करो — संपत्ति का मूल्य उपयोगिता में है।',
      explanation: 'Echoing Rahim and classical wisdom, Gupt urged that riches gain meaning through generosity, not hoarding.',
      theme: 'Wealth & Materialism',
      author: 'Maithili Sharan Gupt',
      authorSlug: 'maithili-sharan-gupt',
    },
    {
      id: 425,
      hindi: 'स्वतंत्रता\nअमूल्य\nवरदान है।',
      english: 'Freedom is a priceless gift — guard it with vigilance.',
      meaning_hindi: 'स्वतंत्रता अमूल्य वरदान है — सजगता से इसकी रक्षा करो।',
      explanation: 'Written during colonial rule, Gupt\'s nationalist verse treated liberty as sacred — political freedom and moral autonomy intertwined.',
      theme: 'Character',
      author: 'Maithili Sharan Gupt',
      authorSlug: 'maithili-sharan-gupt',
      featured: true,
    },
    {
      id: 426,
      hindi: 'जो\nदेता है\nवही\nपाता है।',
      english: 'One who gives receives — generosity returns multiplied.',
      meaning_hindi: 'जो देता है वही पाता है — उदारता कई गुना लौटती है।',
      explanation: 'Gupt\'s moral poetry consistently rewards selflessness — giving time, care, or resources enriches the giver\'s soul.',
      theme: 'Service',
      author: 'Maithili Sharan Gupt',
      authorSlug: 'maithili-sharan-gupt',
    },
    {
      id: 427,
      hindi: 'धैर्य\nविजय की\nकुंजी है।',
      english: 'Patience is the key to victory — haste breaks what endurance builds.',
      meaning_hindi: 'धैर्य विजय की कुंजी है — जल्दबाजी वही तोड़ती है जो सहनशीलता बनाती है।',
      explanation: 'In his epics, Gupt\'s heroes prevail through steadfast waiting — Urmila\'s long vigil exemplifies quiet perseverance.',
      theme: 'Acceptance',
      author: 'Maithili Sharan Gupt',
      authorSlug: 'maithili-sharan-gupt',
    },
    {
      id: 428,
      hindi: 'ज्ञान\nअंधकार\nमें दीपक\nहै।',
      english: 'Knowledge is the lamp in darkness — education liberates.',
      meaning_hindi: 'ज्ञान अंधकार में दीपक है — शिक्षा से ही मुक्ति मिलती है।',
      explanation: 'Gupt championed literacy and learning as tools of national and personal emancipation — ignorance was the enemy of progress.',
      theme: 'Wisdom',
      author: 'Maithili Sharan Gupt',
      authorSlug: 'maithili-sharan-gupt',
    },
    {
      id: 429,
      hindi: 'एकता\nमें\nशक्ति है।',
      english: 'In unity lies strength — division weakens the nation.',
      meaning_hindi: 'एकता में शक्ति है — विभाजन राष्ट्र को कमज़ोर करता है।',
      explanation: 'Gupt\'s nationalist vision called for harmony across regions and communities — a united India was his recurring dream.',
      theme: 'Friendship',
      author: 'Maithili Sharan Gupt',
      authorSlug: 'maithili-sharan-gupt',
    },
    {
      id: 430,
      hindi: 'कर्तव्य\nधर्म\nसे ऊपर\nनहीं।',
      english: 'Duty is inseparable from dharma — perform it without fail.',
      meaning_hindi: 'कर्तव्य धर्म से ऊपर नहीं — इसे निभाओ, चाहे कुछ भी हो।',
      explanation: 'From Ramayana retellings to nationalist verse, Gupt honored those who fulfill obligation despite personal cost.',
      theme: 'Character',
      author: 'Maithili Sharan Gupt',
      authorSlug: 'maithili-sharan-gupt',
    },
  ],
}
