// This file contains Devanagari script — ensure UTF-8 encoding
import type { Writer } from '../types'

export const mirabaiWriter: Writer = {
  slug: 'mirabai',
  name_english: 'Mirabai (Meera Bai)',
  name_hindi: 'मीराबाई',
  era: '16th century (c. 1498–1546)',
  language: 'Hindi / Rajasthani / Braj Bhasha',
  genre: 'Bhakti poetry, Krishna padas and dohas',
  short_bio_english:
    'Rajput princess turned saint-poet, Mirabai surrendered royal life for devotion to Krishna — her padas of love, defiance, and surrender are sung across India still.',
  short_bio_hindi:
    'राजपूत राजकुमारी से संत-कवि बनी, मीराबाई ने राज-जीवन त्याग कर कृष्ण भक्ति अपनाई — उनके प्रेम, विरोध और समर्पण के पद आज भी गाये जाते हैं।',
  biography: {
    introduction_english:
      'Mirabai (c. 1498–1546) was a Rajput princess of Merta who became one of the greatest saint-poets of the Bhakti movement. Married into the royal house of Mewar, she refused to accept worldly rank above her devotion to Lord Krishna, composing hundreds of padas expressing ecstatic love, longing, and surrender. Persecuted by her in-laws yet undeterred, Mira wandered as a devotee, singing in temples and among common people. Her verses, preserved in oral and written tradition, transcend sect and region — she remains the emblem of fearless, personal devotion in Indian spirituality.',
    introduction_hindi:
      'मीराबाई (लगभग १४९८–१५४६) मेरता की राजपूत राजकुमारी थी जो भक्ति आंदोलन की महानतम संत-कवियों में से एक बन गई। मेवाड़ के राजघराने में विवाह के बावजूद भी उन्होंने सांसारिक पद को भगवान कृष्ण भक्ति से उपर नहीं माना और उत्कृष्ट प्रेम, विरह और समर्पण के सैकडों पद रचे। ससुराल के अत्याचार के बावजूद भी अविचल, मीरा भक्त के रूप में मंदिरों और जन-समूह में गाती रही। उनके पद मौखिक और लिखित दोनों परंपराओं में सुरक्षित हैं — वे भारतीय आध्यात्मिकता में निड़र व्यक्तिगत भक्ति की प्रतीक हैं।',
    timeline: [
      {
        year: 'c. 1498',
        title_english: 'Birth in Kudki, Rajasthan',
        title_hindi: 'कुडकी, राजस्थान में जन्म',
        content_english:
          'Mira was born into the Rathore Rajput family at Kudki near Merta in Marwar. Legend says she showed devotion to Krishna from childhood — a doll idol she worshipped became the symbol of her lifelong love.',
        content_hindi:
          'मीरा का जन्म मारवाड़ के मेरता के निकट कुडकी में राठौड़ राजपूत परिवार में हुआ। कथा के अनुसार बचपन से ही उनकी कृष्ण के प्रति भक्ति थी — जिस पुतली मूर्ति की पूजा उन्होंने की, वही उनके जीवनप्रेम का प्रतीक बनी।',
      },
      {
        year: 'c. 1516',
        title_english: 'Marriage to Bhoj Raj of Mewar',
        title_hindi: 'मेवाड़ के भोज राज से विवाह',
        content_english:
          'Mira was married to Bhoj Raj, crown prince of Mewar, in a political alliance. She continued her Krishna devotion openly, refusing court protocol that demanded she honor mortal rulers above the divine.',
        content_hindi:
          'मीरा का विवाह मेवाड़ के युवराज भोज राज से राजनीतिक गठबंधन में हुआ। उन्होंने खुले रूप से कृष्ण भक्ति जारी रखी और आने दरबारी रीति को अस्वीकार किया जो नृप को इश्वर से उपर मानती थी।',
      },
      {
        year: 'c. 1521–1530s',
        title_english: 'Persecution and Defiance',
        title_hindi: 'उत्पीड़न और विरोध',
        content_english:
          'After Bhoj Raj\'s death, Mira faced hostility from the Mewar court — attempts on her life including a poisoned cup and a bed of nails, according to legend. She emerged unharmed, singing that Krishna alone was her protector.',
        content_hindi:
          'भोज राज की मृत्यु के बाद मीरा को मेवाड़ दरबार से शत्रुता का सामना करना पड़ा — कथा के अनुसार जहर का प्याला और कीलों का बिछाँना भी भेजा गया। वह अकेषत निकली और गाती रही कि कृष्ण ही उनके रक्षक हैं।',
      },
      {
        year: 'c. 1530s–1546',
        title_english: 'Wandering Saint-Poet',
        title_hindi: 'भ्रमण करने वाली संत-कवि',
        content_english:
          'Mira left royal life and traveled through Rajasthan and Gujarat, singing in temples and among saints. She is associated with Vrindavan, Dwarka, and Nathdwara — her padas spread through oral tradition.',
        content_hindi:
          'मीरा ने राजय-त्याग किया और राजस्थान-गुजरात में मंदिरों और संतों के बीच गाती रही। उनका संबंध वृन्दावन, द्वारका और नाथद्वारा से जोड़ा जाता है — उनके पद मौखिक परंपरा से फैलते रहे।',
      },
      {
        year: 'Legacy',
        title_english: 'Immortal Voice of Bhakti',
        title_hindi: 'भक्ति की अमर आवाज़',
        content_english:
          'Mirabai\'s padas are sung in classical and folk music across India. She inspired poets, reformers, and women who chose spiritual freedom over social constraint. "Mira" became synonymous with total surrender to divine love.',
        content_hindi:
          'मीराबाई के पद भारत भर में शास्त्रीय और लोक संगीत में गाये जाते हैं। उन्होंने उन कवियों, सुधारकों और महिलाओं को प्रेरित किया जिन्होंने सामाजिक बंधन से अधिक आध्यात्मिक स्वतंत्रता चुनी। "मीरा" पूर्ण समर्पण का प्रतीक बन गई।',
      },
    ],
    facts: {
      born: 'c. 1498 — Kudki, near Merta, Rajasthan',
      died: 'c. 1546 — Dwarka, Gujarat (tradition)',
      full_name_english: 'Mirabai (Meera Bai)',
      full_name_hindi: 'मीराबाई',
      court: 'Princess of Merta; married into Mewar royal house; independent bhakti saint',
      works: [
        'Mirabai ke Pad — devotional songs to Krishna',
        'Pada and doha collections in oral tradition',
        'Bhajans preserved in Rajasthani and Braj folk song',
        'Influence on later Bhakti poets and classical musicians',
      ],
    },
  },
  dohe: [
    {
      id: 206,
      hindi: 'मेरे तो गिरधर गोपाल,\nदूसरो न कोई।',
      english: 'Giridhar Gopal alone is mine — I have no other lord.',
      meaning_hindi: 'मेरे लिए तो गिरधर गोपाल ही सब कुछ हैं — दूसरा कोई नहीं।',
      explanation: 'Among Mira\'s most beloved lines — total exclusive devotion to Krishna as the only master of her heart and life.',
      theme: 'Love & Relationships',
      author: 'Mirabai (Meera Bai)',
      authorSlug: 'mirabai',
      featured: true,
    },
    {
      id: 207,
      hindi: 'विष का प्याला\nरानाजी ने भेजा।',
      english: 'The king sent a cup of poison — I drank it as prasad.',
      meaning_hindi: 'राना ने जहर का प्याला भेजा — मीरा ने उसे प्रसाद मान कर पिया।',
      explanation: 'Legend says Mira drank poison sent by her in-laws unharmed, seeing Krishna\'s grace in every ordeal — emblem of fearless faith.',
      theme: 'Character',
      author: 'Mirabai (Meera Bai)',
      authorSlug: 'mirabai',
      featured: true,
    },
    {
      id: 208,
      hindi: 'पाग घुंघरू\nबांध मीरा नाची।',
      english: 'Mira tied anklets to her feet and danced for her Lord.',
      meaning_hindi: 'मीरा ने पाक्रमें घुंघरू बांध कर अपने स्वामी के लिए नाची।',
      explanation: 'Mira\'s ecstatic dance before Krishna scandalized the court but expressed pure bhakti — body and soul offered in joy.',
      theme: 'Acceptance',
      author: 'Mirabai (Meera Bai)',
      authorSlug: 'mirabai',
    },
    {
      id: 209,
      hindi: 'छाड़ मात पिता\nससुर एक न मानूं।',
      english: 'I renounced parents and in-laws — none I obey but my Lord.',
      meaning_hindi: 'मीरा ने माता-पिता और ससुराल को छोड़ दिया — वह सिर्फ अपने इश्वर को मानती हैं।',
      explanation: 'Mira chose divine love over familial and social duty — a radical act of spiritual autonomy for a Rajput princess.',
      theme: 'Character',
      author: 'Mirabai (Meera Bai)',
      authorSlug: 'mirabai',
    },
    {
      id: 210,
      hindi: 'प्रेम गली अति सांकरी,\nता में दो न समाहीं।',
      english: 'The path of love is very narrow — two cannot walk it together.',
      meaning_hindi: 'प्रेम का रास्ता बहुत पतला है — उस पर दो लोग एक साथ नहीं चल सकते।',
      explanation: 'Exclusive devotion requires singleness of heart — for Mira, no worldly attachment could share the road to Krishna.',
      theme: 'Love & Relationships',
      author: 'Mirabai (Meera Bai)',
      authorSlug: 'mirabai',
      featured: true,
    },
    {
      id: 211,
      hindi: 'मैं तो प्रेम दिवानी,\nमेरा दर्द न जाने कोई।',
      english: 'I am mad with love — no one knows my pain.',
      meaning_hindi: 'मैं प्रेम में दिवानी हूं — मेरा दर्द कोई नहीं समजाता।',
      explanation: 'The loneliness of intense devotion — Mira\'s ecstatic love was misunderstood by the world around her.',
      theme: 'Love & Relationships',
      author: 'Mirabai (Meera Bai)',
      authorSlug: 'mirabai',
    },
    {
      id: 212,
      hindi: 'आज रंग महा रंग है,\nमैं तो प्रेम के रंग में रंगी।',
      english: 'Today is the great festival of color — I am dyed in the color of love.',
      meaning_hindi: 'आज बड़ा रंग का त्योहार है — मैं तो प्रेम के रंग में रंग चुकी हूँ।',
      explanation: 'Mira transforms Holi\'s external colors into inner dye of divine love — celebration becomes spiritual intoxication.',
      theme: 'Acceptance',
      author: 'Mirabai (Meera Bai)',
      authorSlug: 'mirabai',
    },
    {
      id: 213,
      hindi: 'मोको कहां ढूंढे रे बंदे,\nमैं तो तेरे पास में।',
      english: 'Where do you search for me, O devotee? I am right beside you.',
      meaning_hindi: 'हे बंदे तू मुजे कहां ढूंढ़ता है — मैं तो तेरे पास ही हूँ (कृष्ण का संदेश)।',
      explanation: 'Krishna speaks through Mira — the divine is not distant but present in every moment of sincere seeking.',
      theme: 'Wisdom',
      author: 'Mirabai (Meera Bai)',
      authorSlug: 'mirabai',
    },
    {
      id: 214,
      hindi: 'संत जन कर\nसेवा करो।',
      english: 'Serve the saints — therein lies the path to God.',
      meaning_hindi: 'संतों की सेवा करो — इसी में भगवान का मार्ग है।',
      explanation: 'Mira honored fellow devotees and saints — service to the holy was service to Krishna himself.',
      theme: 'Service',
      author: 'Mirabai (Meera Bai)',
      authorSlug: 'mirabai',
    },
    {
      id: 215,
      hindi: 'धन धान सब छोड़ दिया,\nनाम के लिए।',
      english: 'She abandoned wealth and grain — all for the Name.',
      meaning_hindi: 'मीरा ने धन-दौलत सब छोड़ दिया — सिर्फ नाम के लिए।',
      explanation: 'Renunciation of royal riches for the divine name — Mira\'s life rejected material security for spiritual wealth.',
      theme: 'Wealth & Materialism',
      author: 'Mirabai (Meera Bai)',
      authorSlug: 'mirabai',
    },
    {
      id: 216,
      hindi: 'सखी री मेरा मन\nमधुर बचन सुन को तरसे।',
      english: 'O friend, my heart thirsts to hear his sweet words.',
      meaning_hindi: 'सखी, मेरा मन उसके मीठे बोल सुनने को तरस्ता है।',
      explanation: 'Virah-bhakti — separation intensifies longing; Mira\'s heart aches for the sound of Krishna\'s voice.',
      theme: 'Love & Relationships',
      author: 'Mirabai (Meera Bai)',
      authorSlug: 'mirabai',
    },
    {
      id: 217,
      hindi: 'जो प्रेम की राजधानी,\nसो जाने कौन।',
      english: 'Who can know the capital city of love?',
      meaning_hindi: 'प्रेम की राजधानी को कौन जान सकता है — वह अनुभव से ही समझी जाती है।',
      explanation: 'Love\'s domain cannot be mapped by intellect — only those who enter it through devotion understand its geography.',
      theme: 'Wisdom',
      author: 'Mirabai (Meera Bai)',
      authorSlug: 'mirabai',
    },
    {
      id: 218,
      hindi: 'मित्र वो जो\nसच बोलता है।',
      english: 'A true friend speaks truth even when it wounds.',
      meaning_hindi: 'सच्चा मित्र वही जो सच बोलता है — चाहे दुःख हो।',
      explanation: 'Among Mira\'s simpler ethical verses — honest friendship, like honest devotion, requires courage and sincerity.',
      theme: 'Friendship',
      author: 'Mirabai (Meera Bai)',
      authorSlug: 'mirabai',
    },
    {
      id: 219,
      hindi: 'जिस दिन से श्याम\nमिले हैं।',
      english: 'Since the day Shyam met me, nothing else satisfies.',
      meaning_hindi: 'जिस दिन से श्याम मिले, तब से कुछ और सुख नहीं।',
      explanation: 'Union with Krishna fills every desire — worldly pleasures pale once divine love is tasted.',
      theme: 'Acceptance',
      author: 'Mirabai (Meera Bai)',
      authorSlug: 'mirabai',
    },
    {
      id: 220,
      hindi: 'मीरा के प्रभु\nगिरधर नगर।',
      english: 'Mira\'s Lord is Giridhar — holder of the mountain.',
      meaning_hindi: 'मीरा के स्वामी गिरधर हैं — जो गोवरधन उठाए।',
      explanation: 'Mira\'s signature closing line in many padas — affirming Krishna as Giridhar, the protector who lifts the mountain for his devotees.',
      theme: 'Love & Relationships',
      author: 'Mirabai (Meera Bai)',
      authorSlug: 'mirabai',
    },
  ],
}
