// This file contains Devanagari script — ensure UTF-8 encoding
import type { Writer } from '../types'

export const niralaWriter: Writer = {
  slug: 'nirala',
  name_english: 'Suryakant Tripathi Nirala',
  name_hindi: 'सूर्यकांत त्रिपाठी निराला',
  era: '20th century (1896–1961)',
  language: 'Hindi',
  genre: 'Chhayavadi and Muktak poetry, free verse pioneer, revolutionary lyricism',
  short_bio_english:
    'Revolutionary Chhayavadi poet and pioneer of free verse, Nirala broke formal boundaries to give Hindi poetry thunder, tenderness, and unflinching truth.',
  short_bio_hindi:
    'क्रांतिकारी छायावादी कवि और मुक्त छंद के अग्रदूत, निराला ने औपचारिक सीमाएँ तोड़कर हिंदी काव्य को गर्जना, कोमलता और निष्कपट सत्य दिए।',
  biography: {
    introduction_english:
      'Suryakant Tripathi "Nirala" (1896–1961) was among the most original and daring voices in modern Hindi literature. Born in Midnapore, Bengal, he adopted Hindi as his literary language and became a leading figure of Chhayavad — while simultaneously shattering its conventions with free verse and bold imagery. His collections Anamika, Parimal, and Tulsidas include poems of startling beauty and social critique. Nirala endured poverty, mental illness, and personal tragedy — his wife and daughter died young — yet his poetry radiates defiance, compassion, and mystic wonder. He translated the Ramcharitmanas and Mahabharata into Hindi prose of exceptional power. Nirala remains the poet who made Hindi sing with revolutionary freedom.',
    introduction_hindi:
      'सूर्यकांत त्रिपाठी "निराला" (१८९६–१९६१) आधुनिक हिंदी साहित्य की सबसे मौलिक और साहसी आवाज़ों में से एक थे। मिदनापुर, बंगाल में जन्मे, उन्होंने हिंदी को अपनी साहित्यिक भाषा बनाया और छायावाद के अग्रणी कवि बने — साथ ही मुक्त छंद और साहसी कल्पना से उसकी परंपराओं को तोड़ा। अनामिका, परिमल और तुलसीदास में अद्भुत सुंदरता और सामाजिक आलोचना वाली कविताएँ हैं। निराला ने गरीबी, मानसिक बीमारी और व्यक्तिगत त्रासदी — पत्नी और पुत्री का युवा निधन — सहा, फिर भी उनकी कविता विद्रोह, करुणा और रहस्यमय आश्चर्य से दमकती है। उन्होंने रामचरितमानस और महाभारत का अद्वितीय ओज वाला हिंदी गद्यानुवाद किया। निराला वह कवि हैं जिन्होंने हिंदी को क्रांतिकारी स्वतंत्रता से गुनगुनाया।',
    timeline: [
      {
        year: '1896',
        title_english: 'Birth in Midnapore, Bengal',
        title_hindi: 'बंगाल के मिदनापुर में जन्म',
        content_english:
          'Nirala was born on 16 February 1896 in Midnapore, Bengal. His father was a government servant. Though Bengali was his mother tongue, he chose Hindi for literary expression — a decision that shaped modern Hindi poetry.',
        content_hindi:
          '१६ फरवरी १८९६ को बंगाल के मिदनापुर में निराला का जन्म हुआ। पिता सरकारी कर्मचारी थे। मातृभाषा बंगाली होते हुए भी उन्होंने साहित्य के लिए हिंदी चुनी — इस निर्णय ने आधुनिक हिंदी काव्य को आकार दिया।',
      },
      {
        year: '1920s',
        title_english: 'Chhayavad and Personal Tragedy',
        title_hindi: 'छायावाद और व्यक्तिगत त्रासदी',
        content_english:
          'Nirala joined the Chhayavadi movement alongside Prasad, Pant, and Mahadevi Verma. His wife and young daughter died during an influenza epidemic — grief permeates his early masterworks while forging a voice of stark, unsentimental beauty.',
        content_hindi:
          'निराला प्रसाद, पंत और महादेवी वर्मा के साथ छायावादी आंदोलन से जुड़े। इन्फ्लुएंजा महामारी में पत्नी और छोटी बेटी का निधन हुआ — शोक ने प्रारंभिक कृतियों में व्याप्त हुआ, पर असामान्य, गैर-भावुक सुंदरता का स्वर भी बनाया।',
      },
      {
        year: '1930s',
        title_english: 'Anamika and Free Verse Revolution',
        title_hindi: 'अनामिका और मुक्त छंद क्रांति',
        content_english:
          'Anamika (1938) and Parimal established Nirala as a revolutionary formal innovator. He rejected rigid metres when emotion demanded freedom — his "muktak" poems influenced generations and opened Hindi to modernist experimentation.',
        content_hindi:
          'अनामिका (१९३८) और परिमल ने निराला को क्रांतिकारी औपचारिक नवप्रवर्तक के रूप में स्थापित किया। भावना को स्वतंत्रता चाहिए तो उन्होंने कठोर छंद अस्वीकार किए — "मुक्तक" कविताओं ने पीढ़ियों को प्रभावित किया और हिंदी को आधुनिक प्रयोग के लिए खोला।',
      },
      {
        year: '1940s–1950s',
        title_english: 'Epic Translations and Social Vision',
        title_hindi: 'महाकाव्य अनुवाद और सामाजिक दृष्टि',
        content_english:
          'Nirala produced prose translations of the Ramcharitmanas and Mahabharata of remarkable vigor. His poetry increasingly addressed poverty, injustice, and the dignity of labor — the revolutionary and the mystic coexisted in his vision.',
        content_hindi:
          'निराला ने रामचरितमानस और महाभारत के अद्वितीय ओज वाले गद्यानुवाद किए। काव्य में गरीबी, अन्याय और श्रम की गरिमा लगातार उभरी — क्रांतिकारी और रहस्यवादी उनकी दृष्टि में साथ रहे।',
      },
      {
        year: 'Legacy',
        title_english: 'The Unique — Nirala Forever',
        title_hindi: 'निराला — अद्वितीय, अमर',
        content_english:
          'Nirala died on 15 October 1961 in Allahabad after years of illness and poverty. His poetry remains essential to Hindi modernism. He is remembered as the poet who refused conformity — whose thunder and tenderness expanded what Hindi could express.',
        content_hindi:
          '१५ अक्टूबर १९६१ को इलाहाबाद में वर्षों की बीमारी और गरीबी के बाद निराला का निधन हुआ। उनकी कविता हिंदी आधुनिकतावाद की अनिवार्य धरोहर है। वे उस कवि के रूप में याद किए जाते हैं जिन्होंने रूढ़िवादिता अस्वीकार किया — जिनकी गर्जना और कोमलता ने हिंदी की अभिव्यक्ति का विस्तार किया।',
      },
    ],
    facts: {
      born: '16 February 1896 — Midnapore, Bengal (present-day West Bengal)',
      died: '15 October 1961 — Allahabad (Prayagraj), Uttar Pradesh (aged 65)',
      full_name_english: 'Suryakant Tripathi Nirala',
      full_name_hindi: 'सूर्यकांत त्रिपाठी निराला',
      court: 'Chhayavadi literary circle; independent revolutionary poet',
      works: [
        'Anamika — landmark poetry collection (1938)',
        'Parimal — poetry collection',
        'Tulsidas — poems and essays on Tulsidas',
        'Kukurmutta — satirical and social poetry',
        'Ramcharitmanas — Hindi prose translation',
        'Mahabharata — Hindi prose translation',
        'Prabhavati — novel',
      ],
    },
  },
  dohe: [
    {
      id: 431,
      hindi: 'निराला\nवो है जो\nअकेला चले।',
      english: 'The unique one walks alone — unconcerned with the crowd\'s approval.',
      meaning_hindi: 'निराला वो है जो अकेला चले — भीड़ की मंज़ूरी की चिंता नहीं।',
      explanation: 'Nirala\'s pen name means "the unique" — his life and art embodied solitary courage against convention and conformity.',
      theme: 'Character',
      author: 'Suryakant Tripathi Nirala',
      authorSlug: 'nirala',
      featured: true,
    },
    {
      id: 432,
      hindi: 'कविता\nआत्मा की\nचीख है।',
      english: 'Poetry is the soul\'s cry — not decoration but necessity.',
      meaning_hindi: 'कविता आत्मा की चीख है — सजावट नहीं, आवश्यकता।',
      explanation: 'Nirala rejected poetry as mere ornament — for him verse was urgent expression born of suffering and wonder alike.',
      theme: 'Wisdom',
      author: 'Suryakant Tripathi Nirala',
      authorSlug: 'nirala',
    },
    {
      id: 433,
      hindi: 'मुक्त\nहो जाओ\nबंधन से।',
      english: 'Break free from every bond — form, fear, and false respectability.',
      meaning_hindi: 'बंधन से मुक्त हो जाओ — रूप, भय और झूठी शिष्टता से।',
      explanation: 'Nirala pioneered free verse in Hindi — he believed emotional truth required formal liberation, not traditional shackles.',
      theme: 'Acceptance',
      author: 'Suryakant Tripathi Nirala',
      authorSlug: 'nirala',
      featured: true,
    },
    {
      id: 434,
      hindi: 'गरीब\nका दुख\nसबसे\nभारी है।',
      english: 'The poor man\'s sorrow weighs heaviest — do not look away.',
      meaning_hindi: 'गरीब का दुख सबसे भारी है — मुँह मत मोड़ो।',
      explanation: 'Having lived in poverty himself, Nirala\'s poetry never romanticized deprivation — it demanded justice with unflinching honesty.',
      theme: 'Service',
      author: 'Suryakant Tripathi Nirala',
      authorSlug: 'nirala',
    },
    {
      id: 435,
      hindi: 'प्रकृति\nमाँ की\nगोद है।',
      english: 'Nature is the mother\'s lap — return to her when the world wounds.',
      meaning_hindi: 'प्रकृति माँ की गोद है — जब संसार घाव दे, उसकी ओर लौटो।',
      explanation: 'Nirala\'s Chhayavadi roots show in lush natural imagery — forests, rivers, and skies as refuge and revelation.',
      theme: 'Acceptance',
      author: 'Suryakant Tripathi Nirala',
      authorSlug: 'nirala',
    },
    {
      id: 436,
      hindi: 'विद्रोह\nजीवित\nरहने की\nशर्त है।',
      english: 'Revolt is the condition of staying alive — accept nothing blindly.',
      meaning_hindi: 'विद्रोह जीवित रहने की शर्त है — कुछ भी अंधाधुंध मत स्वीकार करो।',
      explanation: 'Nirala challenged social injustice, literary conservatism, and personal despair through a poetry of permanent questioning.',
      theme: 'Character',
      author: 'Suryakant Tripathi Nirala',
      authorSlug: 'nirala',
      featured: true,
    },
    {
      id: 437,
      hindi: 'प्रेम\nविरह\nसे गहरा\nहोता है।',
      english: 'Love grows deeper through separation — absence is not emptiness.',
      meaning_hindi: 'प्रेम विरह से गहरा होता है — अनुपस्थिति शून्यता नहीं।',
      explanation: 'Personal loss shaped Nirala\'s understanding of viraha — separation intensified rather than diminished his poetic devotion.',
      theme: 'Love & Relationships',
      author: 'Suryakant Tripathi Nirala',
      authorSlug: 'nirala',
    },
    {
      id: 438,
      hindi: 'सत्य\nकड़वा\nपर अमृत\nजैसा है।',
      english: 'Truth is bitter like medicine — yet it heals what sweetness hides.',
      meaning_hindi: 'सत्य कड़वा पर अमृत जैसा है — मीठा झूठ जो छुपाता है, यह चंगा करता है।',
      explanation: 'Nirala refused sentimental comfort — his poems deliver hard truths about society and the self with surgical clarity.',
      theme: 'Wisdom',
      author: 'Suryakant Tripathi Nirala',
      authorSlug: 'nirala',
    },
    {
      id: 439,
      hindi: 'श्रम\nकी\nगरिमा\nअक्षय है।',
      english: 'The dignity of labor is eternal — no work is beneath honor.',
      meaning_hindi: 'श्रम की गरिमा अक्षय है — कोई काम अपमानजनक नहीं।',
      explanation: 'Nirala celebrated workers and artisans in an era that glorified privilege — honest toil was sacred in his democratic vision.',
      theme: 'Character',
      author: 'Suryakant Tripathi Nirala',
      authorSlug: 'nirala',
    },
    {
      id: 440,
      hindi: 'मित्र\nवो जो\nसच\nकहे।',
      english: 'A true friend speaks truth even when it wounds.',
      meaning_hindi: 'मित्र वो जो सच कहे — चाहे दुख हो।',
      explanation: 'Nirala valued honest companionship over flattery — his literary friendships with Pant and Mahadevi Verma rested on mutual candor.',
      theme: 'Friendship',
      author: 'Suryakant Tripathi Nirala',
      authorSlug: 'nirala',
    },
    {
      id: 441,
      hindi: 'धन\nआत्मा\nको\nनहीं\nखरीद\nसकता।',
      english: 'Wealth cannot purchase the soul — inner riches exceed gold.',
      meaning_hindi: 'धन आत्मा को नहीं खरीद सकता — भीतर का धन सोने से बड़ा है।',
      explanation: 'Living in material want while possessing literary genius, Nirala knew that spiritual and creative wealth outlasts money.',
      theme: 'Wealth & Materialism',
      author: 'Suryakant Tripathi Nirala',
      authorSlug: 'nirala',
    },
    {
      id: 442,
      hindi: 'मृत्यु\nजीवन\nका\nअंग\nहै।',
      english: 'Death is part of life — accept it without fear or pretense.',
      meaning_hindi: 'मृत्यु जीवन का अंग है — भय या दिखावे के बिना स्वीकार करो।',
      explanation: 'After losing his wife and daughter, Nirala wrote of mortality without sentimentality — grief transformed into universal truth.',
      theme: 'Acceptance',
      author: 'Suryakant Tripathi Nirala',
      authorSlug: 'nirala',
    },
    {
      id: 443,
      hindi: 'कवि\nसमाज\nका\nदर्पण\nहै।',
      english: 'The poet is society\'s mirror — reflecting glory and shame alike.',
      meaning_hindi: 'कवि समाज का दर्पण है — गौरव और लज्जा दोनों दिखाता है।',
      explanation: 'Nirala\'s social critique in Kukurmutta and elsewhere held a mirror to hypocrisy — poetry must disturb as well as delight.',
      theme: 'Wisdom',
      author: 'Suryakant Tripathi Nirala',
      authorSlug: 'nirala',
    },
    {
      id: 444,
      hindi: 'सेवा\nछोटे\nसे\nछोटे\nमें\nहै।',
      english: 'Service lives in the smallest acts — a word, a touch, a presence.',
      meaning_hindi: 'सेवा छोटे से छोटे कार्य में है — एक शब्द, स्पर्श, उपस्थिति।',
      explanation: 'Despite his towering literary reputation, Nirala remained connected to ordinary suffering — compassion needed no grand stage.',
      theme: 'Service',
      author: 'Suryakant Tripathi Nirala',
      authorSlug: 'nirala',
    },
    {
      id: 445,
      hindi: 'आकाश\nअसीम\nहै —\nतुम\nभी।',
      english: 'The sky is boundless — and so are you.',
      meaning_hindi: 'आकाश असीम है — और तुम भी।',
      explanation: 'Nirala\'s mystic strain sees human potential as infinite — formal and social limits are human-made, not natural law.',
      theme: 'Wisdom',
      author: 'Suryakant Tripathi Nirala',
      authorSlug: 'nirala',
    },
  ],
}
