// This file contains Devanagari script — ensure UTF-8 encoding
import type { Writer } from '../types'

export const rahimWriter: Writer = {
  slug: 'rahim',
  name_english: 'Abdul Rahim Khan-i-Khana (Rahim)',
  name_hindi: 'अब्दुल रहीम खान-ए-खाना',
  era: 'Mughal era (1556–1627)',
  language: 'Hindi / Braj Bhasha',
  genre: 'Niti doha, Bhakti poetry',
  short_bio_english:
    'One of Akbar\'s Navaratnas, Rahim composed timeless Hindi dohas on love, friendship, and wisdom.',
  short_bio_hindi:
    'अकबर के नवरत्नों में से एक, रहीम ने प्रेम, मित्रता और जीवन-ज्ञान पर अमर दोहे लिखे।',
  biography: {
  introduction_english:
    'Abdul Rahim Khan-i-Khanan (1556–1627) was one of the most extraordinary figures of the Mughal era — a brilliant military commander, a polyglot scholar, and above all, a poet whose wisdom transcends centuries. Born in Lahore to Bairam Khan, the trusted guardian of Emperor Akbar, Rahim rose to become one of the Navaratnas — the Nine Gems of Akbar\'s court. His Hindi dohas, composed in the language of the common people rather than the Persian of the nobility, carry timeless lessons on love, friendship, virtue, and the human condition.',

  introduction_hindi:
    'अब्दुल रहीम खान-ए-खाना (1556–1627) मुगल युग के सबसे असाधारण व्यक्तित्वों में से एक थे — एक प्रतिभाशाली सैन्य सेनापति, बहुभाषी विद्वान और सबसे बढ़कर एक ऐसे कवि, जिनकी बुद्धिमत्ता सदियों को पार करती है। लाहौर में बैरम खान के घर जन्मे रहीम, अकबर के दरबार के नवरत्नों में से एक बने। उन्होंने अपने दोहे फारसी की जगह आम जनता की हिंदी भाषा में लिखे, जिनमें प्रेम, मित्रता, गुण और मानव स्वभाव के शाश्वत पाठ हैं।',

  timeline: [
    {
      year: '1556',
      title_english: 'Birth in Lahore',
      title_hindi: 'लाहौर में जन्म',
      content_english:
        'Abdul Rahim Khan-i-Khanan was born on December 17, 1556, in Lahore. His father, Bairam Khan, was the most powerful nobleman of the Mughal Empire and the guardian-regent of the young Emperor Akbar. When Bairam Khan was assassinated in 1561 while traveling to Mecca, the four-year-old Rahim was taken under the protection of Emperor Akbar himself.',
      content_hindi:
        'अब्दुल रहीम खान-ए-खाना का जन्म 17 दिसंबर 1556 को लाहौर में हुआ। उनके पिता बैरम खान मुगल साम्राज्य के सबसे शक्तिशाली सरदार और युवा सम्राट अकबर के संरक्षक-रीजेंट थे। 1561 में मक्का जाते समय बैरम खान की हत्या हो गई। चार वर्षीय रहीम को तब स्वयं सम्राट अकबर ने अपनी सुरक्षा में ले लिया।',
    },
    {
      year: '1570s',
      title_english: 'Rising Star at Akbar\'s Court',
      title_hindi: 'अकबर के दरबार में उत्कर्ष',
      content_english:
        'Rahim grew up in Akbar\'s court, mastering Persian, Arabic, Sanskrit, Braj, and Hindi. His exceptional talents in poetry, scholarship, and administration quickly made him one of the most respected figures around the Emperor.',
      content_hindi:
        'रहीम अकबर के दरबार में बड़े हुए और फारसी, अरबी, संस्कृत, ब्रज और हिंदी में निपुण हो गए। कविता, विद्वत्ता और प्रशासन में उनकी असाधारण प्रतिभा ने उन्हें सम्राट के सबसे आदरणीय दरबारियों में से एक बना दिया।',
    },
    {
      year: '1584',
      title_english: 'Khan-i-Khanan — Khan of Khans',
      title_hindi: 'खान-ए-खाना — खानों का खान',
      content_english:
        'In 1584, at just 28, Rahim was dispatched to suppress a major rebellion in Gujarat. His brilliant tactical genius delivered a crushing defeat to rebel forces. Emperor Akbar bestowed upon him the title: Khan-i-Khanan — "Khan of Khans".',
      content_hindi:
        'सन 1584 में मात्र 28 वर्ष की आयु में रहीम को गुजरात में बड़े विद्रोह को दबाने के लिए भेजा गया। उनकी रणनीतिक कुशलता ने विद्रोहियों को करारी हार दी। अकबर ने उन्हें खान-ए-खाना की उपाधि दी।',
    },
    {
      year: '1590s',
      title_english: 'Navaratna — One of the Nine Gems',
      title_hindi: 'नवरत्न — नौ रत्नों में से एक',
      content_english:
        'At the peak of his power, Rahim was counted among Akbar\'s legendary Navaratnas. He translated the Baburnama from Chagatai to Persian and composed Sanskrit texts on astrology. His personal library held approximately 24,000 manuscript volumes.',
      content_hindi:
        'अपनी शक्ति के शिखर पर रहीम अकबर के प्रसिद्ध नवरत्नों में गिने जाते थे। उन्होंने बाबरनामा का फारसी में अनुवाद किया और ज्योतिष पर संस्कृत ग्रंथ लिखे।',
    },
    {
      year: '1627',
      title_english: 'Legacy — A Poet for the Ages',
      title_hindi: 'विरासत — युगों का कवि',
      content_english:
        'Rahim died in Agra on October 1, 1627. His dohas have been memorised, recited and cherished across India for over 400 years, taught in schools, and alive in everyday speech.',
      content_hindi:
        'रहीम का निधन 1 अक्टूबर 1627 को आगरा में हुआ। उनके दोहे 400 से अधिक वर्षों से भारत में याद किए, सुनाए और संजोए जाते हैं।',
    },
  ],

  facts: {
    born: 'December 17, 1556 — Lahore',
    died: 'October 1, 1627 — Agra (aged 70)',
    full_name_english: 'Abdul Rahim Khan-i-Khanan',
    full_name_hindi: 'अब्दुल रहीम खान-ए-खाना',
    court: 'One of Akbar\'s Navaratnas (Nine Gems)',
    works: [
      'Rahim ke Dohe — 500+ Hindi couplets',
      'Baburnama Translation (Chagatai → Persian, 1589–90)',
      'Khetakautukam — Sanskrit astrology text',
      'Dwatrimshadyogavali — Sanskrit astrology text',
      'Madanastak — Sanskrit verse',
    ],
  },
},
  dohe: [
  {
    id: 1,
    hindi: 'रहिमन धागा प्रेम का, मत तोरो चटकाय।\nटूटे पे फिर न जुरे, जुरे गाँठ परी जाय।।',
    english: 'Do not snap the thread of love abruptly. Once broken, it cannot be properly joined — even if joined, a permanent knot remains.',
    meaning_hindi: 'प्रेम का रिश्ता बहुत नाज़ुक होता है। इसे अचानक मत तोड़ो। एक बार टूटने के बाद ठीक से नहीं जुड़ता, और जुड़े तो गाँठ पड़ जाती है।',
    explanation: 'This doha emphasizes the delicate nature of love and relationships. Once trust is broken, relationships cannot be fully restored — even repaired bonds carry the mark of damage.',
    theme: 'Love & Relationships',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
    featured: true,
  },
  {
    id: 2,
    hindi: 'रूठे सुजन मनाइए, जो रूठे सौ बार।\nरहिमन फिरि फिरि पोइए, टूटे मुक्ता हार।।',
    english: 'Endeavor to appease a good person even if they grow angry a hundred times. Keep reconciling — like restringing a broken pearl necklace again and again.',
    meaning_hindi: 'भले इंसान से सौ बार रूठने पर भी मनाते रहो। जैसे टूटी मोती की माला को बार-बार पिरोते हैं।',
    explanation: 'Good friends are like precious pearls — no matter how many times the relationship breaks, it is worth repairing and reconciling.',
    theme: 'Friendship',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
  },
  {
    id: 3,
    hindi: 'जो रहीम उत्तम प्रकृति, का करी सकत कुसंग।\nचन्दन विष व्यापत नहीं, लिपटे रहत भुजंग।।',
    english: 'A person of excellent nature cannot be corrupted by bad company. Poison cannot affect sandalwood, even when a serpent wraps around it.',
    meaning_hindi: 'अच्छे स्वभाव वाला व्यक्ति बुरी संगति से नष्ट नहीं हो सकता। चंदन पर सांप लिपटे रहने पर भी विष का असर नहीं होता।',
    explanation: 'Inherent good character is resilient against negative influences. Noble individuals maintain their virtue regardless of bad company.',
    theme: 'Character',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
  },
  {
    id: 4,
    hindi: 'रहिमन निज मन की बिथा, मन ही राखो गोय।\nसुनी इठलैहैं लोग सब, बांटी न लेंहैं कोय।।',
    english: 'Keep your heart\'s sorrow secret within yourself. Others will only laugh upon hearing your pain — no one will truly share your burden.',
    meaning_hindi: 'अपने मन का दर्द अपने ही मन में रखो। लोग सुनकर सिर्फ हँसेंगे, तुम्हारी पीड़ा में भागीदार नहीं बनेंगे।',
    explanation: 'Personal sorrows are best kept private. The world often mocks pain rather than helps — it is wiser to bear troubles silently.',
    theme: 'Wisdom',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
  },
  {
    id: 5,
    hindi: 'रहिमन विपदा हू भली, जो थोरे दिन होय।\nहित अनहित या जगत में, जान परत सब कोय।।',
    english: 'Adversity of a few days is actually good — it reveals who is a true friend and who is a foe in this world.',
    meaning_hindi: 'अगर विपत्ति थोड़े समय की हो तो वह अच्छी है। इससे दुनिया में हित और अनहित का पता चल जाता है।',
    explanation: 'Temporary hardship acts as a litmus test for relationships — true friends reveal themselves in difficult times.',
    theme: 'Wisdom',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
  },
  {
    id: 6,
    hindi: 'समय पाय फल होत है, समय पाय झरी जात।\nसदा रहे नहिं एक सी, का रहीम पछितात।।',
    english: 'Everything happens at its appointed time — fruit ripens in its season, flowers fall in theirs. Circumstances are never constant, so why regret?',
    meaning_hindi: 'सब कुछ अपने समय पर होता है। फल लगते हैं, झरते हैं। सब कुछ हमेशा एक जैसा नहीं रहता, तो पछताने से क्या?',
    explanation: 'Life has natural cycles of joy and sorrow. Understanding this eternal truth prevents unnecessary regret and worry.',
    theme: 'Acceptance',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
  },
  {
    id: 7,
    hindi: 'रहिमन देख बड़ेन को, लघु न दीजिये डारि।\nजहाँ काम आवै सुई, कहा करै तलवारि।।',
    english: 'Do not discard smaller things upon gaining access to great ones. Where you need a needle, a sword — however mighty — is of no use.',
    meaning_hindi: 'बड़ों को देखकर छोटों को मत भूलो। जहाँ सुई काम आए, वहाँ तलवार किस काम की?',
    explanation: 'Small things and humble people have irreplaceable value in the right context. Never abandon old, smaller friendships for new, important ones.',
    theme: 'Wisdom',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
    featured: true,
  },
  {
    id: 8,
    hindi: 'दोनों रहिमन एक से, जों लों बोलत नाहिं।\nजान परत हैं काक पिक, रितु बसंत के माहिं।।',
    english: 'Two people may seem identical until they speak. Only through their words can you distinguish the crow from the cuckoo — especially in spring.',
    meaning_hindi: 'दोनों एक जैसे लगते हैं जब तक बोलते नहीं। काग और कोयल की पहचान वसंत में उनकी बोली से होती है।',
    explanation: 'True character is revealed through speech and behavior. The crow and cuckoo look alike — only their voices distinguish them.',
    theme: 'Character',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
  },
  {
    id: 9,
    hindi: 'बिगरी बात बने नहीं, लाख करो किन कोय।\nरहिमन फाटे दूध को, मथे न माखन होय।।',
    english: 'Once something is spoiled, no amount of effort can restore it. Curdled milk cannot be churned back into butter, no matter how hard you try.',
    meaning_hindi: 'एक बार बिगड़ी बात लाख कोशिश से भी नहीं बनती। खट्टा दूध कितना भी मथो, मक्खन नहीं निकलता।',
    explanation: 'Some mistakes, once made, cannot be undone. Be careful and thoughtful — not all consequences can be reversed.',
    theme: 'Wisdom',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
  },
  {
    id: 10,
    hindi: 'बानी ऐसी बोलिये, मन का आपा खोय।\nऔरन को सीतल करै, आपहु सीतल होय।।',
    english: 'Speak in such a gentle manner that you lose all ego. Your words should bring peace to others — and in doing so, you will find peace yourself.',
    meaning_hindi: 'ऐसे बोलो जिससे अहंकार खो जाए। जो दूसरों को शीतल करे, वह तुम्हें भी शीतल करेगा।',
    explanation: 'Humble and pleasant speech brings comfort to others and inner tranquility to oneself. Ego-free words cool every temper.',
    theme: 'Character',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
  },
  {
    id: 11,
    hindi: 'वृक्ष कबहूँ नहीं फल भखैं, नदी न संचै नीर।\nपरमारथ के कारने, साधुन धरा सरीर।।',
    english: 'Trees do not eat their own fruit; rivers do not hoard their water. Virtuous people take birth only to serve others and work for the welfare of all.',
    meaning_hindi: 'वृक्ष अपने फल नहीं खाते, नदियाँ अपना पानी नहीं रोकतीं। साधु लोग दूसरों की सेवा के लिए ही जन्म लेते हैं।',
    explanation: 'Like trees and rivers that exist for others\' benefit, virtuous people dedicate their lives to helping humanity rather than personal gain.',
    theme: 'Service',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
  },
  {
    id: 12,
    hindi: 'रहिमन पानी राखिए, बिन पानी सब सून।\nपानी गए न ऊबरे, मोती मानुष चून।।',
    english: 'Preserve humility and honour — without them everything is barren. Once gone, neither pearl, nor person, nor grain can be saved.',
    meaning_hindi: 'मान और विनम्रता को सँभालो। बिना इनके सब सूना है। पानी जाने पर न मोती, न मनुष्य, न अनाज बचता है।',
    explanation: 'Water is used as a metaphor for humility and honour. Without these qualities, even the most valuable things become worthless.',
    theme: 'Character',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
  },
  {
    id: 13,
    hindi: 'जैसी परे सो सहि रहे, करहु न किछु ग्लानि।\nरहिमन मिट्टी ही खेल है, आपु भी मिट्टी जानि।।',
    english: 'Accept whatever comes without grief. Remember — this entire world is but earth and dust, and you too shall become dust one day.',
    meaning_hindi: 'जो कुछ आए उसे सहन करो, ग्लानि मत करो। यह दुनिया मिट्टी का खेल है और तुम भी मिट्टी हो।',
    explanation: 'Equanimity and acceptance of life\'s circumstances come from recognising the temporary nature of everything — including ourselves.',
    theme: 'Acceptance',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
    featured: true,
  },
  {
    id: 14,
    hindi: 'एकै साधे सब सधै, सब साधे सब जाय।\nरहिमन मुख्य मुख्य विधि, साधन सकल उपाय।।',
    english: 'Perfect one fundamental thing and everything falls into place. Chase everything and you lose all. Focus on what is essential first.',
    meaning_hindi: 'एक को साध लो तो सब सध जाता है। सब को साधने की कोशिश में सब कुछ खो जाता है।',
    explanation: 'By perfecting one essential skill or virtue, you create a foundation for success everywhere. Scattered effort leads to failure.',
    theme: 'Wisdom',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
  },
  {
    id: 15,
    hindi: 'खीर पकाइ खिलाइ के, अपनै मुख न खाय।\nरहिमन परमारथी नर, बिरिद बढ़ायत जाय।।',
    english: 'One who cooks delicious pudding and feeds it to others without tasting it themselves is truly selfless. Such noble souls grow in glory through serving others.',
    meaning_hindi: 'जो खीर बनाकर दूसरों को खिलाए पर खुद न खाए, वह परोपकारी है। ऐसे लोग अपनी यश बढ़ाते जाते हैं।',
    explanation: 'Absolute selflessness — finding joy in serving others without expecting anything in return — is the mark of true nobility.',
    theme: 'Service',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
  },
  {
    id: 16,
    hindi: 'रहिमन छिमा बड़न को, चाहिये बिना दोष।\nछोट न छिमा काहू को, वरन कोटिन कलोष।।',
    english: 'Elders should forgive readily, even without fault — for forgiveness adorns the great. The small cannot afford to withhold it, lest their misdeeds multiply manifold.',
    meaning_hindi: 'बड़ों को बिना कारण भी क्षमा करना चाहिए। छोटों को क्षमा न करने से उनके दोष कई गुना बढ़ जाते हैं।',
    explanation: 'Forgiveness is a mark of greatness. Those in positions of power should forgive readily; ordinary people cannot afford to hold grudges.',
    theme: 'Character',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
  },
  {
    id: 17,
    hindi: 'निंदक नियरे राखिए, आँगन कुटी छवाय।\nबिन पानी साबुन बिना, निर्मल करै सुभाय।।',
    english: 'Keep your critics close — even build them a hut in your courtyard. Without water or soap, they cleanse your character through honest feedback.',
    meaning_hindi: 'आलोचकों को पास रखो। बिना पानी और साबुन के, वे तुम्हारे स्वभाव को शुद्ध कर देते हैं।',
    explanation: 'Constructive criticism is like a mirror showing our faults. Unlike flatterers, sincere critics help us improve through honest feedback.',
    theme: 'Wisdom',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
  },
  {
    id: 18,
    hindi: 'रहिमन ओछे नरन सो, बैर भलो न प्रीति।\nकाटे चाटे स्वान के, दोऊ भाँति विपरीति।।',
    english: 'Neither friendship nor enmity is good with petty people. A dog\'s bite and a dog\'s lick are both unpleasant — both are harmful in their own way.',
    meaning_hindi: 'ओछे लोगों से न दोस्ती अच्छी, न दुश्मनी। कुत्ते के काटने और चाटने दोनों से नुकसान है।',
    explanation: 'Small-minded people are best avoided entirely. Both their friendship and their enmity bring problems.',
    theme: 'Friendship',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
  },
  {
    id: 19,
    hindi: 'रहिमन कहत सुनत कठिन, रहिबो कठिन सनेह।\nचंदन होय तो बाँधिए, नहीं त छोड़ो नेह।।',
    english: 'Love is hard to speak of, hard to hear, and hard to maintain. Tie it firmly if it is true as sandalwood — otherwise, let it go.',
    meaning_hindi: 'प्यार कहना, सुनना और निभाना तीनों कठिन हैं। अगर सच्चा हो तो चंदन की तरह बाँध लो, नहीं तो छोड़ दो।',
    explanation: 'True love requires commitment and effort. It should be held firmly if genuine, but released if it is not authentic.',
    theme: 'Love & Relationships',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
  },
  {
    id: 20,
    hindi: 'धनि रहीम जल पंक को, लघु जिय पिअत अघाय।\nउदधि बड़ाई कौन है, जगत पिआसो जाय।।',
    english: 'Blessed is the muddy pool water, which quenches the thirst of tiny creatures. What greatness does the ocean possess, if the world walks away thirsty?',
    meaning_hindi: 'धन्य है वह कीचड़ का पानी जो छोटे जीवों की प्यास बुझाए। उस समुद्र की बड़ाई क्या जिससे दुनिया प्यासी लौट जाए?',
    explanation: 'True value lies in being useful to others. A small muddy pool that quenches thirst is more worthy than a vast ocean that no one can drink.',
    theme: 'Wealth & Materialism',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
    featured: true,
  },
  {
    id: 21,
    hindi: 'रहिमन वे नर मर गये, जे कछु माँगन जाहिं।\nउनते पहले वे मुये, जिन मुख निकसत नाहिं।।',
    english: 'Those who go begging are as good as dead. But even more dead are those from whose lips the word "no" never escapes when someone needs help.',
    meaning_hindi: 'जो माँगने जाते हैं वे मर गये। उनसे पहले वे मरे जो माँगने पर "नहीं" कहते हैं।',
    explanation: 'This couplet critiques both needless dependency and stinginess. Refusing help to the needy is a greater moral death than seeking help.',
    theme: 'Wealth & Materialism',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
  },
  {
    id: 22,
    hindi: 'तरुवर फल नहिं खात है, सरवर पियत न पान।\nकहि रहीम पर काज हित, संपति सँचहिं सुजान।।',
    english: 'Trees do not eat their own fruit; lakes do not drink their own water. Wise people accumulate wealth for the benefit of others.',
    meaning_hindi: 'पेड़ अपने फल नहीं खाते, तालाब अपना पानी नहीं पीते। समझदार लोग दूसरों के काम के लिए ही संपत्ति जोड़ते हैं।',
    explanation: 'Wealth and resources have meaning only when they serve others. True wisdom lies in accumulation for a greater purpose.',
    theme: 'Wealth & Materialism',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
  },
  {
    id: 23,
    hindi: 'कहि रहीम संपति सगे, बनत बहुत बहु रीति।\nविपति कसौटी जे कसे, तेई साँचे मीत।।',
    english: 'In times of prosperity, many come forward as relatives and friends through various means. But only those who stand by you in adversity are truly genuine friends.',
    meaning_hindi: 'संपत्ति में बहुत लोग मित्र बनते हैं। पर विपत्ति की कसौटी पर जो खरे उतरें, वही सच्चे मित्र हैं।',
    explanation: 'Fair-weather friends are plenty but true friends are rare. Adversity is the only real test of genuine friendship.',
    theme: 'Friendship',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
  },
  {
    id: 24,
    hindi: 'माँगे मुकरि जो देत है, सो रहीम घटि जात।\nदेनहार कोई और है, भेजत सो दिन रात।।',
    english: 'One who gives but later denies — that person diminishes. The true giver is someone else; He sends gifts day and night without end.',
    meaning_hindi: 'जो देकर मुकर जाए वह घटिया है। असली देने वाला कोई और है जो दिन-रात भेजता रहता है।',
    explanation: 'True generosity comes from the divine. Human givers who later boast or deny their gifts miss the spiritual dimension of charity.',
    theme: 'Service',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
  },
  {
    id: 25,
    hindi: 'रहिमन धन संचय करो, बिन धन जग में नाहिं।\nपर यह धन सतसंग का, और धन किस काम आहिं।।',
    english: 'Do accumulate wealth — without wealth there is nothing in this world. But the true wealth is the company of good people; all other wealth is of little use.',
    meaning_hindi: 'धन जरूर जमा करो, बिना धन के दुनिया में कुछ नहीं। पर सबसे बड़ा धन सत्संग का है, बाकी धन किस काम का?',
    explanation: 'Material wealth is necessary but not sufficient. The company of wise and good people is the greatest wealth one can possess.',
    theme: 'Wealth & Materialism',
    author: 'Abdul Rahim Khan-i-Khana (Rahim)',
    authorSlug: 'rahim',
  },
],
}
