// This file contains Devanagari script — ensure UTF-8 encoding
import type { Writer } from '../types'

export const ravidasWriter: Writer = {
  slug: 'ravidas',
  name_english: 'Sant Ravidas',
  name_hindi: 'संत रविदास',
  era: '15th century (Bhakti movement)',
  language: 'Hindi / Braj Bhasha / Awadhi',
  genre: 'Bhakti poetry, Nirgun pad',
  short_bio_english:
    'A cobbler-saint of Varanasi who challenged caste hierarchy, Ravidas sang of divine love and equality — his verses live in the Guru Granth Sahib.',
  short_bio_hindi:
    'काशी के चर्मकार-संत रविदास ने जाति-पाति का विरोध करते हुए प्रेम और समता का संदेश गाया — उनके पद गुरु ग्रंथ साहिब में संरक्षित हैं।',
  biography: {
    introduction_english:
      'Sant Ravidas (c. 1450–1520) was a revolutionary Bhakti saint, poet, and social reformer born in Varanasi into a family of leather workers — a community considered untouchable. Defying caste orthodoxy, he proclaimed that devotion to the formless God (Nirgun Brahman) was open to all. His pads blend mystical love, social protest, and practical wisdom. Forty-one of his compositions are enshrined in the Guru Granth Sahib, making him one of the few non-Sikh saints honored in Sikh scripture.',
    introduction_hindi:
      'संत रविदास (लगभग १४५०–१५२०) एक क्रांतिकारी भक्ति संत और कवि थे, जिन्होंने समाज में समानता का संदेश दिया। जाति-कठोरता का विरोध करते हुए उन्होंने घोषित किया कि निर्गुण ब्रह्म की भक्ति सभी के लिए खुली है। उनके पदों में रहस्यमय प्रेम, सामाजिक विरोध और व्यावहारिक बुद्धि का संगम है। उनकी इकतालीस रचनाएँ गुरु ग्रंथ साहिब में संरक्षित हैं।',
    timeline: [
      {
        year: 'c. 1450',
        title_english: 'Birth in Varanasi',
        title_hindi: 'काशी में जन्म',
        content_english:
          'Ravidas was born in Seer Goverdhanpur, a locality of Varanasi, into a family of chamars (leather workers). From childhood he showed spiritual inclination and rejected the notion that caste determined worth before God.',
        content_hindi:
          'रविदास का जन्म वाराणसी के सीर गोवर्धनपुर में चमार परिवार में हुआ। बचपन से ही उनमें आध्यात्मिक झुकाव था और वे मानते थे कि जाति ईश्वर के समक्ष मूल्य नहीं तय करती।',
      },
      {
        year: '15th century',
        title_english: 'Spiritual Awakening',
        title_hindi: 'आध्यात्मिक जागृति',
        content_english:
          'Tradition holds that Ravidas received initiation from the saint Ramananda, though this is debated. He spent his days in devotion and his nights composing pads that spoke of inner purity over outer ritual.',
        content_hindi:
          'परंपरा में रविदास को संत रामानंद से दीक्षा मिली — हालाँकि इस पर विवाद है। वे दिन भर भक्ति में और रात पद रचना में व्यतीत करते, जिनमें बाहरी कर्मकांड से अधिक आंतरिक पवित्रता पर बल दिया।',
      },
      {
        year: 'c. 1480–1520',
        title_english: 'Poetic Ministry',
        title_hindi: 'काव्य और उपदेश',
        content_english:
          'Ravidas composed hundreds of pads in Braj and Awadhi, addressing kings, Brahmins, and common people alike. He used the metaphor of his humble occupation to illustrate humility before the Divine.',
        content_hindi:
          'रविदास ने ब्रज और अवधी में सैकड़ों पद रचे, जो राजा, ब्राह्मण और आम जन सभी को संदेश देते हैं। उन्होंने अपने नीच कहे जाने वाले व्यवसाय को ईश्वर के समक्ष विनम्रता का प्रतीक बनाया।',
      },
      {
        year: 'c. 1520',
        title_english: 'Meeting with Mirabai',
        title_hindi: 'मीराबाई से मिलन',
        content_english:
          'Legend records that the Rajput princess-saint Mirabai accepted Ravidas as her guru, a powerful symbol of his spiritual authority transcending caste and gender barriers in medieval India.',
        content_hindi:
          'किंवदंती है कि मीराबाई ने रविदास को अपना गुरु स्वीकार किया — यह मध्यकालीन भारत में जाति और लिंग भेद पार करने वाली उनकी आध्यात्मिक शक्ति का प्रतीक है।',
      },
      {
        year: 'Legacy',
        title_english: 'Place in Scripture and Memory',
        title_hindi: 'ग्रंथ में स्थान और विरासत',
        content_english:
          'Ravidas is venerated across North India. His birth anniversary (Magh Purnima) draws millions of followers. The Ravidassia tradition and Ambedkarite movements have drawn deeply on his message of dignity and equality.',
        content_hindi:
          'रविदास का पूरे उत्तर भारत में सम्मान है। माघ पूर्णिमा पर उनकी जयन्ती मनाई जाती है और लाखों श्रद्धालु इकट्ठा होते हैं। रविदासिया परंपरा और अंबेडकर-प्रेरित आंदोलनों ने समानता और गरिमा के उनके संदेश को गहराई से अपनाया है।',
      },
    ],
    facts: {
      born: 'c. 1450 — Seer Goverdhanpur, Varanasi',
      died: 'c. 1520 — Varanasi (aged ~70)',
      full_name_english: 'Sant Ravidas (Raidas)',
      full_name_hindi: 'संत रविदास (रैदास)',
      court: 'Independent saint-poet; Bhakti and Nirgun traditions',
      works: [
        'Ravidas ke Pad — 41 hymns in Guru Granth Sahib',
        'Nirgun Bhakti poetry in Braj and Awadhi',
        'Social reform hymns on caste equality',
        'Mystical love poetry to the formless Lord (Hari)',
      ],
    },
  },
  dohe: [
    {
      id: 101,
      hindi: 'मन चंगा तो कठौती में गंगा।\nजो चित ना भावै, सो चित ना भावै,\nसो कौन सी गंगा की।।',
      english: 'If the mind is pure, the Ganga flows in the palm of your hand. What use is any outer river if the mind itself is not pure?',
      meaning_hindi: 'मन पवित्र हो तो हथेली की कठौती में ही गंगा है। जब अंतःकरण शुद्ध न हो, बाहर की नदी का क्या लाभ?',
      explanation: 'From Guru Granth Sahib. One of Ravidas\'s most famous verses, emphasizing inner purity over external ritual bathing. Widely quoted across India.',
      theme: 'Character',
      author: 'Sant Ravidas',
      authorSlug: 'ravidas',
      featured: true,
    },
    {
      id: 102,
      hindi: 'जाति-जाति में जाति है, जो केतन के पात।\nनहि अपने पापों के संग, साधु की संगति।।',
      english: 'Caste is found in every leaf of the ketan tree — but the saint\'s company does not carry the stain of one\'s own sins.',
      meaning_hindi: 'केतन के पत्तों में भी जाति दिखती है, पर साधु की संगति अपने पापों का बोझ नहीं लेती।',
      explanation: 'From Guru Granth Sahib. A bold critique of caste consciousness, arguing that true spiritual fellowship transcends birth and social stigma.',
      theme: 'Wisdom',
      author: 'Sant Ravidas',
      authorSlug: 'ravidas',
      featured: true,
    },
    {
      id: 103,
      hindi: 'कहै रैदास सब जग एक, वासुरा से पहिचान।\nजो कछु करै सोई करै, हम नहि करत ज्ञान।।',
      english: 'Says Ravidas: the whole world is one — recognize it through the Lord. Whatever happens, He alone does; I claim no separate knowledge.',
      meaning_hindi: 'रैदास कहते हैं — सारा जग एक है, वासुदेव से पहचानो। जो कुछ होता है, वह वही करता है; मैं अलग ज्ञान का दावा नहीं करता।',
      explanation: 'From Guru Granth Sahib. Expresses non-dual vision — all creation is one in the Divine, and the ego\'s claim to separate agency is illusion.',
      theme: 'Acceptance',
      author: 'Sant Ravidas',
      authorSlug: 'ravidas',
      featured: true,
    },
    {
      id: 104,
      hindi: 'अब मोहि भला राम तुम्हारो।\nजो नर दुख पावै, जो सुख पावै, सो तुम्हारो।।',
      english: 'Now I am devoted only to You, O Ram. Whoever suffers or rejoices — all belong to You alone.',
      meaning_hindi: 'अब मैं केवल तुम्हारा हूँ, हे राम। जो दुख पाता है, जो सुख पाता है — सब कुछ तुम्हारा है।',
      explanation: 'From Guru Granth Sahib. A pad of total surrender and mystical love, offering joy and sorrow alike to the Beloved Lord.',
      theme: 'Love & Relationships',
      author: 'Sant Ravidas',
      authorSlug: 'ravidas',
    },
    {
      id: 105,
      hindi: 'पिया परही चारे द्वारे, हम परहि एक नार।\nजब लग पिया घर नहीं आवै, तब लग कैसे धार।।',
      english: 'My Beloved watches all four directions; I watch only one door. As long as He does not come home, how can I sustain myself?',
      meaning_hindi: 'प्रियतम चारों द्वार देखते हैं, मैं एक ही द्वार। जब तक वे घर न आएं, मैं कैसे धीरज धारूँ?',
      explanation: 'From Guru Granth Sahib. A classic viraha (separation) pad expressing the soul\'s longing for the Divine Beloved who seems absent.',
      theme: 'Love & Relationships',
      author: 'Sant Ravidas',
      authorSlug: 'ravidas',
    },
    {
      id: 106,
      hindi: 'आरे सु निंता तजि जल जाओ, मन कछु नहीं बिचार।\nजो कछु करै सोई करै, हम नहि करत ज्ञान।।',
      english: 'O friend, abandon worry and go forth — do not overthink. Whatever happens, He alone does; I claim no separate knowledge.',
      meaning_hindi: 'हे सुहाग! चिंता छोड़कर चलो, मन में अधिक विचार मत करो। जो होता है, वह वही करता है; मैं अलग ज्ञान का दावा नहीं करता।',
      explanation: 'From Guru Granth Sahib. Counsel to a fellow seeker: release anxiety and trust in the Divine will rather than the restless mind.',
      theme: 'Friendship',
      author: 'Sant Ravidas',
      authorSlug: 'ravidas',
    },
    {
      id: 107,
      hindi: 'नाम तेरा आसनो, नाम तेरा उरसा।\nनाम तेरा केसरो, ले छिटकरी नामसा।।',
      english: 'Your Name is my seat, Your Name is my bed. Your Name is my saffron — I scatter only Your Name.',
      meaning_hindi: 'तेरा नाम मेरी आसन, तेरा नाम मेरा बिस्तर। तेरा नाम मेरा केसर — मैं केवल तेरा नाम बिखेरता हूँ।',
      explanation: 'From Guru Granth Sahib. Every aspect of daily life is consecrated to the Divine Name — a pad of total devotional service.',
      theme: 'Service',
      author: 'Sant Ravidas',
      authorSlug: 'ravidas',
    },
    {
      id: 108,
      hindi: 'अंध कूप महँ परिओ, संत न बाहर काढ़ै।\nबाहर काढ़ै तो ना काढ़ै, बाहन बिरद न समाढ़ै।।',
      english: 'I have fallen into a blind well — the saint does not pull me out. If he pulled me out, he would not; his vow does not permit it.',
      meaning_hindi: 'मैं अंधे कुएँ में गिर पड़ा — संत बाहर नहीं निकालते। निकालें तो निकाल नहीं सकते, उनका व्रत ऐसा नहीं समझता।',
      explanation: 'From Guru Granth Sahib. A paradoxical pad about grace — the saint\'s compassion works in mysterious ways beyond human expectation.',
      theme: 'Wisdom',
      author: 'Sant Ravidas',
      authorSlug: 'ravidas',
    },
    {
      id: 109,
      hindi: 'धन्ना धन्न जन औदासी, जो नहि चाहै दुनिया।\nजो चाहै सो मिलै, जो न चाहै सो जिया।।',
      english: 'Blessed, blessed is the detached soul who desires nothing of the world. Whoever desires, finds; whoever does not desire, lives freely.',
      meaning_hindi: 'धन्य है वह औदासी जन जो दुनिया नहीं चाहता। जो चाहता है, वह पाता है; जो नहीं चाहता, वह स्वतंत्र जीता है।',
      explanation: 'From Guru Granth Sahib. Celebrates spiritual detachment — freedom comes from releasing worldly craving rather than accumulating more.',
      theme: 'Acceptance',
      author: 'Sant Ravidas',
      authorSlug: 'ravidas',
    },
    {
      id: 110,
      hindi: 'घूँघट का पट खोल, तो पीछे पर्दा न होय।\nजब लग घूँघट रहे, तब लग मिलन न होय।।',
      english: 'Lift the veil of the ghunghat — then no curtain remains behind. As long as the veil stays, union cannot happen.',
      meaning_hindi: 'घूँघट का पर्दा हटाओ — तब पीछे कोई आड़ न रहे। जब तक घूँघट बना रहे, मिलन नहीं हो सकता।',
      explanation: 'From Guru Granth Sahib. The veil is both social and spiritual — remove inner obscurity and false modesty to meet the Divine directly.',
      theme: 'Character',
      author: 'Sant Ravidas',
      authorSlug: 'ravidas',
    },
    {
      id: 111,
      hindi: 'रैदास गर्वस न रहै, कोऊ न पूछै जाति।\nजो पूछै तो कहै, रैदास चर्मकार की जाति।।',
      english: 'Ravidas feels no pride — no one asks his caste. If anyone asks, he says: Ravidas is of the cobbler caste.',
      meaning_hindi: 'रैदास को गर्व नहीं — कोई जाति नहीं पूछता। पूछे तो कहता है — रैदास चर्मकार की जाति का है।',
      explanation: 'From Guru Granth Sahib. Radical humility — Ravidas openly declares his low caste without shame, challenging society\'s hierarchy of birth.',
      theme: 'Wealth & Materialism',
      author: 'Sant Ravidas',
      authorSlug: 'ravidas',
    },
    {
      id: 112,
      hindi: 'जो दिसै, सो तेरी रूप।\nजो सुनै, सो तेरी ज्ञान।\nजो कहै, सो तेरी बानी।\nजो करै, सो तेरी काम।।',
      english: 'Whatever is seen is Your form. Whatever is heard is Your knowledge. Whatever is spoken is Your word. Whatever is done is Your action.',
      meaning_hindi: 'जो दिखता है, वह तेरी रूप है। जो सुनता है, वह तेरी ज्ञान। जो कहता है, वह तेरी वाणी। जो करता है, वह तेरी कर्म।',
      explanation: 'From Guru Granth Sahib. A vision of divine immanence — every sense and action is an expression of the One Lord.',
      theme: 'Wisdom',
      author: 'Sant Ravidas',
      authorSlug: 'ravidas',
    },
    {
      id: 113,
      hindi: 'राम हमारो हृदय बसै, राम हमारो मन।\nराम हमारो तन बसै, राम हमारो प्रान।।',
      english: 'Ram dwells in our heart, Ram in our mind. Ram dwells in our body, Ram in our very breath.',
      meaning_hindi: 'राम हमारे हृदय में बसे, राम हमारे मन में। राम हमारे तन में बसे, राम हमारी प्राण में।',
      explanation: 'From Guru Granth Sahib. The Lord is not distant but pervades every layer of being — heart, mind, body, and breath.',
      theme: 'Love & Relationships',
      author: 'Sant Ravidas',
      authorSlug: 'ravidas',
    },
    {
      id: 114,
      hindi: 'सतगुरु पुरख मिला, तब सब दुख गए।\nजब लग गुरु न मिला, तब लग दुख न जाए।।',
      english: 'When the True Guru was found, all sorrows departed. As long as the Guru was not met, sorrow would not leave.',
      meaning_hindi: 'जब सतगुरु मिले, सब दुख चले गए। जब तक गुरु न मिले, दुख जाता ही नहीं था।',
      explanation: 'From Guru Granth Sahib. The spiritual guide is the key to liberation — noble friendship with the Guru ends the cycle of suffering.',
      theme: 'Friendship',
      author: 'Sant Ravidas',
      authorSlug: 'ravidas',
    },
    {
      id: 115,
      hindi: 'करे मुक्ति नहीं अंतर, जब लग मन में मान।\nजब लग मान न छूटै, तब लग बंधन जान।।',
      english: 'There is no liberation within as long as pride dwells in the mind. Until pride is released, know that bondage remains.',
      meaning_hindi: 'जब तक मन में अभिमान है, अंतर मुक्ति नहीं। जब तक मान न छूटे, बंधन बना रहता है।',
      explanation: 'From Guru Granth Sahib. True service to the Divine requires shedding ego-pride — humility is the gateway to inner freedom.',
      theme: 'Service',
      author: 'Sant Ravidas',
      authorSlug: 'ravidas',
    },
  ],
}
