// This file contains Devanagari script — ensure UTF-8 encoding
import type { Writer } from '../types'

export const tukaramWriter: Writer = {
  slug: 'tukaram',
  name_english: 'Sant Tukaram',
  name_hindi: 'संत तुकाराम',
  era: '17th century (1608–1650)',
  language: 'Marathi / Hindi (Abhang tradition)',
  genre: 'Bhakti abhang, Varkari poetry',
  short_bio_english:
    'A grocer-saint of Dehu who sang abhangs to Lord Vitthala, Tukaram taught that devotion, humility, and honest living matter more than ritual or caste.',
  short_bio_hindi:
    'देहू के किराना-संत तुकाराम ने विठ्ठल की भक्ति में अभंग गाए — उन्होंने कहा कि सच्ची भक्ति, विनम्रता और ईमानदार जीवन ही मार्ग है, न कि दिखावा।',
  biography: {
    introduction_english:
      'Sant Tukaram (1608–1650) was one of the greatest saint-poets of the Varkari tradition in Maharashtra. Born in Dehu near Pune into a family of traders, he endured early poverty, the loss of his first wife and son, and social scorn before turning fully to devotion of Lord Vitthala (Panduranga). His abhangs — spontaneous devotional songs in Marathi — reject empty ritual, praise the name of God, and insist that the divine dwells in every honest heart. Tukaram\'s verses were compiled in the Tukaram Gatha and remain central to the annual Pandharpur pilgrimage and to Marathi spiritual life.',
    introduction_hindi:
      'संत तुकाराम (१६०८–१६५०) महाराष्ट्र की वारकरी परंपरा के महानतम संत-कवियों में से एक थे। पुणे के निकट देहू में व्यापारी परिवार में जन्मे तुकाराम ने प्रारंभिक गरीबी, पत्नी और पुत्र के निधन तथा सामाजिक तिरस्कार झेला, फिर पूर्णतः विठ्ठल-भक्ति में लग गए। उनके अभंग — मराठी में स्वाभाविक भक्ति गीत — खोखले कर्मकांड को अस्वीकार करते हैं, नाम-जप की महिमा गाते हैं और कहते हैं कि ईश्वर हर ईमानदार हृदय में निवास करता है। तुकाराम की रचनाएँ तुकाराम गाथा में संकलित हैं और आज भी पंढरपुर की वारी तथा मराठी आध्यात्मिक जीवन का केंद्र हैं।',
    timeline: [
      {
        year: '1608',
        title_english: 'Birth in Dehu',
        title_hindi: 'देहू में जन्म',
        content_english:
          'Tukaram was born in Dehu, a village on the banks of the Indrayani river near Pune, into a family belonging to the Kunbi (Shudra) trading community. His parents, Bolhoba and Kanakai, were devotees of Vitthala, and the young Tukaram grew up hearing the names of saints like Namdev and Dnyaneshwar.',
        content_hindi:
          'तुकाराम का जन्म पुणे के निकट इंद्रायणी नदी के तट पर बसे देहू गाँव में व्यापारी परिवार में हुआ। उनके माता-पिता बोल्होबा और कनकाई विठ्ठल के भक्त थे। बचपन से ही तुकाराम ने संत नामदेव और ज्ञानेश्वर के नाम सुने।',
      },
      {
        year: '1620s',
        title_english: 'Tragedy and Turning Point',
        title_hindi: 'त्रासदी और मोड़',
        content_english:
          'After his father\'s death, Tukaram took over the family grain business but suffered heavy losses. His first wife Rakhumabai and son died during a famine. These griefs shattered his worldly ambitions and pushed him toward intense prayer, fasting, and composition of abhangs.',
        content_hindi:
          'पिता के निधन के बाद तुकाराम ने परिवार का अनाज व्यापार संभाला, पर भारी नुकसान हुआ। पहली पत्नी रखुमाबाई और पुत्र अकाल में चल बसे। ये दुख उनके सांसारिक लक्ष्य तोड़कर प्रार्थना, उपवास और अभंग रचना की ओर ले गए।',
      },
      {
        year: '1630s–1640s',
        title_english: 'Poet of Vitthala',
        title_hindi: 'विठ्ठल के कवि',
        content_english:
          'Tukaram composed thousands of abhangs celebrating Vitthala, denouncing hypocrisy, and teaching that God accepts devotees regardless of birth. Orthodox Brahmins challenged his authority to compose scripture, but his sincerity and popular following prevailed.',
        content_hindi:
          'तुकाराम ने हज़ारों अभंग रचे — विठ्ठल की स्तुति, पाखंड की निंदा और यह शिक्षा कि ईश्वर जन्म से नहीं, भक्ति से स्वीकार करता है। कुछ कठोर ब्राह्मणों ने उनके अधिकार पर सवाल उठाया, पर उनकी सच्चाई और जन-प्रेम विजयी रहे।',
      },
      {
        year: '1649',
        title_english: 'Visit to Pandharpur',
        title_hindi: 'पंढरपुर की यात्रा',
        content_english:
          'Tradition records Tukaram\'s final pilgrimage to Pandharpur, the sacred seat of Vitthala. There he is said to have entered the sanctum in a state of ecstasy and was not seen again — a symbol of his complete union with the divine.',
        content_hindi:
          'परंपरा कहती है कि तुकाराम की अंतिम यात्रा पंढरपुर — विठ्ठल के पवित्र स्थान — की थी। वहाँ वे भाव-विभोर होकर गर्भगृह में गए और फिर नहीं लौटे — यह दिव्य-मिलन का प्रतीक माना जाता है।',
      },
      {
        year: 'Legacy',
        title_english: 'Gatha and Varkari Tradition',
        title_hindi: 'गाथा और वारकरी परंपरा',
        content_english:
          'Tukaram\'s abhangs were preserved in the Tukaram Gatha and became essential reading for Varkari pilgrims. Alongside Dnyaneshwar, Namdev, and Eknath, he defines Maharashtra\'s Bhakti heritage. His message of nama-japa and equality continues to inspire millions.',
        content_hindi:
          'तुकाराम के अभंग तुकाराम गाथा में संरक्षित हुए और वारकरी यात्रियों के लिए अनिवार्य बने। ज्ञानेश्वर, नामदेव और एकनाथ के साथ वे महाराष्ट्र की भक्ति विरासत के आधार हैं। नाम-जप और समानता का उनका संदेश आज भी लाखों को प्रेरित करता है।',
      },
    ],
    facts: {
      born: '1608 — Dehu, near Pune, Maharashtra',
      died: 'c. 1650 — Pandharpur (tradition)',
      full_name_english: 'Sant Tukaram (Tukoba)',
      full_name_hindi: 'संत तुकाराम (तुकोबा)',
      court: 'Varkari Bhakti tradition; devotee of Lord Vitthala',
      works: [
        'Tukaram Gatha — collected abhangs',
        'Abhangs on Vitthala and nama-smaran',
        'Devotional songs of the Varkari sampradaya',
        'Social and moral abhangs on humility and truth',
      ],
    },
  },

  dohe: [
    {
      id: 221,
      hindi: 'विठ्ठल राखा सर्वांगी, नाम घेतां सुख होय।\nनामाशिवाय काही नाही, तुका म्हणे सोय।।',
      english: 'Vitthala fills every limb — chanting His name brings joy. Without the Name, nothing remains, says Tuka — that alone is the way.',
      meaning_hindi: 'विठ्ठल हर अंग में बसे हैं — नाम जपने से सुख मिलता है। नाम के बिना कुछ नहीं, तुका कहते हैं — यही मार्ग है।',
      explanation: 'Among Tukaram\'s most central teachings. Constant remembrance of God\'s name (nama-japa) is the heart of Varkari devotion — simpler and deeper than any external ritual.',
      theme: 'Love & Relationships',
      author: 'Sant Tukaram',
      authorSlug: 'tukaram',
      featured: true,
    },
    {
      id: 222,
      hindi: 'जो म्हणे तो सांगो, मी करी करि राहून।\nसर्व अंगी बसला, पंडुरंग माझ्या जीव्हे।।',
      english: 'Tell me what to do — I shall do it and wait. Panduranga dwells in every limb and on my tongue.',
      meaning_hindi: 'जो कहो वह बताओ, मैं करके रहूँगा। पंडुरंग मेरे हर अंग और जीभ पर बसे हैं।',
      explanation: 'Tukaram offers complete surrender to the divine will. God is not distant but present in the devotee\'s very body and speech.',
      theme: 'Acceptance',
      author: 'Sant Tukaram',
      authorSlug: 'tukaram',
    },
    {
      id: 223,
      hindi: 'धन धान्य देणारा, तोचि विठ्ठल राया।\nदेणारा घेणारा, तोचि माझा माया।।',
      english: 'He who gives grain and wealth — that very one is King Vitthala. The giver and receiver — that alone is my beloved Maya (Lord).',
      meaning_hindi: 'जो धन-अन्न देता है, वही विठ्ठल राजा है। देने वाला और लेने वाला — वही मेरा प्रभु है।',
      explanation: 'Tukaram sees God in every act of giving and receiving. The Lord manifests through daily sustenance and human exchange, not only in temples.',
      theme: 'Service',
      author: 'Sant Tukaram',
      authorSlug: 'tukaram',
    },
    {
      id: 224,
      hindi: 'अभिमानाचा झाड, मुळापासून तोड।\nविनविणारा व्हा, तुका म्हणे मोठ।।',
      english: 'Cut down the tree of pride from its very root. Become one who asks humbly — that is great, says Tuka.',
      meaning_hindi: 'अहंकार के वृक्ष को जड़ से काटो। विनती करने वाला बनो — तुका कहते हैं, यही बड़ाई है।',
      explanation: 'Pride blocks the path to God. Tukaram insists that true greatness lies in humility and the willingness to seek grace.',
      theme: 'Character',
      author: 'Sant Tukaram',
      authorSlug: 'tukaram',
    },
    {
      id: 225,
      hindi: 'काय रे बोलू नको, झूठे बोलू नको।\nसत्य बोल, सत्य चाल, तुका म्हणे सुख।।',
      english: 'Why speak at all if you must speak falsely? Speak truth, walk in truth — that alone brings peace, says Tuka.',
      meaning_hindi: 'झूठ बोलना छोड़ो — सत्य बोलो, सत्य चलो। तुका कहते हैं, यही शांति है।',
      explanation: 'Honesty in word and deed is inseparable from devotion in Tukaram\'s teaching. A devotee\'s life must mirror the truth they praise in God.',
      theme: 'Character',
      author: 'Sant Tukaram',
      authorSlug: 'tukaram',
    },
    {
      id: 226,
      hindi: 'जात पात विचारू नका, नाम घ्या विठोबाचे।\nजेथे नाम तेथे सुख, तुका म्हणे साचे।।',
      english: 'Do not dwell on caste and birth — take the name of Vitthoba. Where the Name is, there is joy — that is true, says Tuka.',
      meaning_hindi: 'जात-पात मत सोचो — विठोबा का नाम लो। जहाँ नाम है, वहीं सुख है — तुका कहते हैं, यह सच है।',
      explanation: 'Like other Bhakti saints, Tukaram rejected caste barriers. Divine love is open to all who chant the sacred name with sincerity.',
      theme: 'Acceptance',
      author: 'Sant Tukaram',
      authorSlug: 'tukaram',
      featured: true,
    },
    {
      id: 227,
      hindi: 'संसार सागर आहे, नाम होय बोट।\nधरून नाव चाल, तुका म्हणे मोठ।।',
      english: 'The world is an ocean — the Name is the boat. Hold the oar of devotion and cross over — that is the great way, says Tuka.',
      meaning_hindi: 'संसार समुद्र है — नाम नाव है। भक्ति की चप्पू पकड़कर पार हो — तुका कहते हैं, यही महान मार्ग है।',
      explanation: 'A classic Varkari metaphor. Worldly life is perilous like the sea; constant remembrance of God is the vessel that carries the soul safely across.',
      theme: 'Wisdom',
      author: 'Sant Tukaram',
      authorSlug: 'tukaram',
    },
    {
      id: 228,
      hindi: 'माझे मन तुझे पायी, ठेविले अर्पण।\nतूचि गुरु तूचि विठ्ठल, तुका म्हणे धरण।।',
      english: 'I have placed my mind at Your feet as offering. You alone are Guru, You alone Vitthala — hold me, says Tuka.',
      meaning_hindi: 'मैंने अपना मन तुम्हारे चरणों में अर्पण किया। तुम ही गुरु, तुम ही विठ्ठल — मुझे थाम लो, तुका कहते हैं।',
      explanation: 'Complete self-offering (arpan) defines Tukaram\'s relationship with the divine. Guru and God merge in the devotee\'s experience of Vitthala.',
      theme: 'Love & Relationships',
      author: 'Sant Tukaram',
      authorSlug: 'tukaram',
    },
    {
      id: 229,
      hindi: 'देवघरी जाऊ नको, मनात घ्या विठ्ठल।\nघरच घर देवालय, तुका म्हणे खर।।',
      english: 'Do not rush to temples alone — keep Vitthala in your heart. Every home is a shrine — that is true, says Tuka.',
      meaning_hindi: 'केवल मंदिर मत जाओ — मन में विठ्ठल रखो। हर घर मंदिर है — तुका कहते हैं, यह सच है।',
      explanation: 'Tukaram criticises ritual without inner devotion. The true temple is the heart that constantly remembers God.',
      theme: 'Wisdom',
      author: 'Sant Tukaram',
      authorSlug: 'tukaram',
    },
    {
      id: 230,
      hindi: 'दु:ख आलें तरी नाम, सुख आलें तरी नाम।\nनामाशिवाय काही नाही, तुका म्हणे गुण।।',
      english: 'In sorrow, the Name; in joy, the Name. Without the Name, nothing has worth — that is the virtue, says Tuka.',
      meaning_hindi: 'दुख में नाम, सुख में नाम। नाम के बिना कुछ मूल्य नहीं — तुका कहते हैं, यही गुण है।',
      explanation: 'Steadfast nama-smaran through all circumstances is Tukaram\'s prescription. Neither pleasure nor pain should interrupt remembrance of God.',
      theme: 'Acceptance',
      author: 'Sant Tukaram',
      authorSlug: 'tukaram',
    },
    {
      id: 231,
      hindi: 'जे खरे भक्त ते, दीन आणि दु:खी।\nत्यांच्या हृदयात विठ्ठल, तुका म्हणे साचे।।',
      english: 'True devotees are humble and bear suffering patiently. Vitthala dwells in their hearts — that is true, says Tuka.',
      meaning_hindi: 'सच्चे भक्त विनम्र और दुख सहन करने वाले होते हैं। उनके हृदय में विठ्ठल बसते हैं — तुका कहते हैं, यह सच है।',
      explanation: 'Tukaram links devotion with compassion and endurance. God chooses the lowly and suffering heart as His dwelling place.',
      theme: 'Service',
      author: 'Sant Tukaram',
      authorSlug: 'tukaram',
    },
    {
      id: 232,
      hindi: 'मोह माया सोड, नाम घे विठोबाचे।\nमोक्ष मिळेल लवकर, तुका म्हणे साचे।।',
      english: 'Leave attachment and illusion — take Vitthoba\'s name. Liberation will come swiftly — that is true, says Tuka.',
      meaning_hindi: 'मोह-माया छोड़ो — विठोबा का नाम लो। मोक्ष शीघ्र मिलेगा — तुका कहते हैं, यह सच है।',
      explanation: 'Freedom from worldly entanglement comes not through ascetic escape alone but through sustained devotion to the divine name.',
      theme: 'Wealth & Materialism',
      author: 'Sant Tukaram',
      authorSlug: 'tukaram',
    },
    {
      id: 233,
      hindi: 'गुरु नसेल तर, नामही व्यर्थ।\nगुरु आणि नाम एक, तुका म्हणे अर्थ।।',
      english: 'Without a Guru, even the Name may fail. Guru and Name are one — that is the meaning, says Tuka.',
      meaning_hindi: 'गुरु न हो तो नाम भी व्यर्थ हो सकता है। गुरु और नाम एक हैं — तुका कहते हैं, यही अर्थ है।',
      explanation: 'Tukaram honours the living spiritual guide. The Guru opens the heart to make nama-japa truly effective.',
      theme: 'Friendship',
      author: 'Sant Tukaram',
      authorSlug: 'tukaram',
    },
    {
      id: 234,
      hindi: 'जगी सर्व सुख, नामातचि आहे।\nनाम घेतां मोकळे, तुका म्हणे जाण।।',
      english: 'All joy in the world rests in the Name. Chanting it, one becomes free — know this, says Tuka.',
      meaning_hindi: 'संसार का सारा सुख नाम में है। नाम जपते ही मुक्ति — तुका कहते हैं, यह जानो।',
      explanation: 'The abhang compresses Tukaram\'s gospel: ultimate happiness and liberation are found in continuous remembrance of Vitthala.',
      theme: 'Wisdom',
      author: 'Sant Tukaram',
      authorSlug: 'tukaram',
      featured: true,
    },
    {
      id: 235,
      hindi: 'तुका म्हणे आता, ऐक रे मना।\nविठ्ठलाचे नाम, हेचि तारण।।',
      english: 'Tuka says now — listen, O mind! The name of Vitthala alone is your deliverance.',
      meaning_hindi: 'तुका अब कहते हैं — सुन, हे मन! विठ्ठल का नाम ही तारण है।',
      explanation: 'A closing exhortation in Tukaram\'s direct voice. The mind must turn from distraction and anchor itself in the saving name of God.',
      theme: 'Love & Relationships',
      author: 'Sant Tukaram',
      authorSlug: 'tukaram',
    },
  ],
}
