// This file contains Devanagari script — ensure UTF-8 encoding
import type { Writer } from '../types'

export const valmikiWriter: Writer = {
  slug: 'valmiki',
  name_english: 'Valmiki',
  name_hindi: 'वाल्मीकि',
  era: 'Ancient (traditionally c. 500 BCE)',
  language: 'Sanskrit / Hindi',
  genre: 'Epic poetry, Ramayana, spiritual sloka',
  short_bio_english:
    'The adi-kavi (first poet) of Sanskrit literature, Valmiki composed the Ramayana — the epic of Rama\'s dharma that has shaped Indian ethics for millennia.',
  short_bio_hindi:
    'संस्कृत साहित्य के आदि-कवि वाल्मीकि ने रामायण की रचना की — राम के धर्म की वह महाकाव्य कथा सहस्त्राब्दियों से भारतीय नैतिकता को आकार देती रही है।',
  biography: {
    introduction_english:
      'Valmiki, revered as the Adi Kavi (First Poet) of Sanskrit literature, is the legendary sage-author of the Ramayana — one of the two great epics of India. Tradition holds that he was born as Ratnakara, a hunter who transformed into a sage through penance and received the divine inspiration to compose Rama\'s story in shloka metre. The Ramayana of Valmiki, with its 24,000 verses across seven kandas, establishes ideals of dharma, filial duty, marital fidelity, and righteous kingship. Valmiki also sheltered Sita during her exile and taught her twin sons Lava and Kusha, who first recited the epic before Rama himself.',
    introduction_hindi:
      'वाल्मीकि, संस्कृत साहित्य के आदि कवि, रामायण — भारत के दो महान महाकाव्यों में से एक — के पौराणिक ऋषि-लेखक हैं। परंपरा कहती है कि वे रत्नाकर नाम के शिकारी थे, जिन्होंने तप से ऋषि बनकर राम की कथा श्लोक छंद में रचने का दिव्य प्रेरणा पाया। वाल्मीकि रामायण, सात काण्डों में २४,००० श्लोकों के साथ, धर्म, पुत्र-धर्म, पति-पत्नी की निष्ठा और राज-धर्म के आदर्श स्थापित करता है। वाल्मीकि ने सीता को वनवास में आश्रय दिया और लव-कुश को शिक्षा दी, जिन्होंने सर्वप्रथम यह काव्य राम के समक्ष सुनाया।',
    timeline: [
      {
        year: 'Ancient era',
        title_english: 'Birth as Ratnakara the Hunter',
        title_hindi: 'शिकारी रत्नाकर के रूप में जन्म',
        content_english:
          'Legend describes Valmiki\'s early life as Ratnakara, a robber who supported his family by looting travelers. When the sage Narada asked him to consider whether his family would share his sins, Ratnakara was shaken and undertook severe penance, repeating the mantra "Mara" until it became "Rama."',
        content_hindi:
          'कथा के अनुसार वाल्मीकि का प्रारंभिक जीवन लुटेरे रत्नाकर के रूप में था, जो यात्रियों को लूटकर परिवार का पालन करता था। नारद के प्रश्न — क्या तुम्हारे परिवार वाले तुम्हारे पाप साझा करेंगे — ने उसे हिला दिया और उसने कठोर तप किया, "मara" मंत्र जपते-जपते "राम" बन गया।',
      },
      {
        year: 'c. 500 BCE (tradition)',
        title_english: 'Transformation into Adi Kavi',
        title_hindi: 'आदि कवि का रूप धारण',
        content_english:
          'After years of meditation, an anthill (valmika) grew around the ascetic — giving him the name Valmiki. Brahma himself is said to have commanded him to compose the Ramayana in the same poetic metre that would become the foundation of classical Sanskrit verse.',
        content_hindi:
          'वर्षों की साधना के बाद एक वल्मीक (चींटी-पहाड़) उसके चारों ओर बन गया — इसी से नाम वाल्मीकि पड़ा। कहा जाता है कि ब्रह्मा ने स्वयं उन्हें रामायण रचने का आदेश दिया, जिस छंद ने शास्त्रीय संस्कृत काव्य की नींव रखी।',
      },
      {
        year: 'Ramayana period',
        title_english: 'Composition of the Ramayana',
        title_hindi: 'रामायण की रचना',
        content_english:
          'Valmiki composed the epic in seven books (kandas): Bala, Ayodhya, Aranya, Kishkindha, Sundara, Yuddha, and Uttara. The opening shloka — born when he witnessed a hunter kill one of a bird pair — set the tone of compassion that runs through the entire work.',
        content_hindi:
          'वाल्मीकि ने सात काण्डों में महाकाव्य रचा: बाल, अयोध्या, अरण्य, किष्किंधा, सुंदर, युद्ध और उत्तर। प्रारंभिक श्लोक — जब उन्होंने शिकारी को पक्षी-युगल में से एक को मारते देखा — करुणा की वह धारा स्थापित की जो पूरे ग्रंथ में बहती है।',
      },
      {
        year: 'Post-Rama era (tradition)',
        title_english: 'Shelter for Sita and Lava-Kusha',
        title_hindi: 'सीता और लव-कुश को आश्रय',
        content_english:
          'When Sita was banished from Ayodhya, Valmiki\'s ashram became her refuge. There she gave birth to twins Lava and Kusha, whom the sage trained in music and the recitation of the Ramayana — leading to the famous assembly where Rama heard his own story sung.',
        content_hindi:
          'जब सीता को अयोध्या से निर्वासित किया गया, वाल्मीकि का आश्रम उनका सहारा बना। वहाँ लव-कुश का जन्म हुआ; ऋषि ने उन्हें संगीत और रामायण-पाठ की शिक्षा दी — जिससे वह प्रसिद्ध सभा हुई जहाँ राम ने अपनी कथा सुनी।',
      },
      {
        year: 'Legacy',
        title_english: 'Foundation of Indian Epic Tradition',
        title_hindi: 'भारतीय महाकाव्य परंपरा की नींव',
        content_english:
          'Valmiki\'s Ramayana has been translated into every major Indian language and retold in countless regional versions. The ideals of Rama as maryada purushottam and the moral framework of the epic continue to guide literature, theatre, and ethical discourse across South and Southeast Asia.',
        content_hindi:
          'वाल्मीकि रामायण का अनुवाद हर प्रमुख भारतीय भाषा में हुआ और अनगिनत क्षेत्रीय रूपों में कही गई। मर्यादा पुरुषोत्तम राम के आदर्श और महाकाव्य का नैतिक ढाँचा आज भी दक्षिण और दक्षिण-पूर्व एशिया में साहित्य, रंगमंच और नैतिक चर्चा को दिशा देते हैं।',
      },
    ],
    facts: {
      born: 'Ancient era — tradition: hunter Ratnakara, later Valmiki',
      died: 'Unknown — immortal through the Ramayana',
      full_name_english: 'Valmiki (Maharshi Valmiki)',
      full_name_hindi: 'वाल्मीकि (महर्षि वाल्मीकि)',
      court: 'Independent sage; author of the Adi Ramayana',
      works: [
        'Valmiki Ramayana — 24,000 shlokas in seven kandas',
        'Yoga Vasishtha (attributed in some traditions)',
        'Foundational shloka metre of Sanskrit poetry',
        'Ashram tradition at Chitrakoot (tradition)',
      ],
    },
  },

  dohe: [
    {
      id: 236,
      hindi: 'मा निषाद प्रतिष्ठां त्वम् अगमः शाश्वतीः समाः।\nयत् क्रौञ्चमिथुनादेकम् अवधीः काममोहितम्।।',
      english: 'O hunter, you shall find no rest for endless ages, since you killed one of a pair of Krauncha birds lost in love.',
      meaning_hindi: 'हे निषाद, तूने प्रेम में मग्न क्रौंच-युगल के एक पक्षी को मारा — इसलिए तुझे अनंत काल तक विश्राम नहीं मिलेगा।',
      explanation: 'The very first shloka of Sanskrit literature, born from Valmiki\'s grief at witnessing violence against a loving pair. It establishes compassion as the epic\'s moral foundation.',
      theme: 'Love & Relationships',
      author: 'Valmiki',
      authorSlug: 'valmiki',
      featured: true,
    },
    {
      id: 237,
      hindi: 'धर्मो रक्षति रक्षितः।\nसत्यं वद, धर्मं चर।।',
      english: 'Righteousness protects those who protect it. Speak truth and walk the path of dharma.',
      meaning_hindi: 'धर्म उसकी रक्षा करता है जो धर्म की रक्षा करता है। सत्य बोलो और धर्म का पालन करो।',
      explanation: 'A core maxim from the Ramayana tradition attributed to Valmiki\'s ethical vision. Dharma is not passive doctrine but an active covenant — upheld, it upholds the upholder.',
      theme: 'Character',
      author: 'Valmiki',
      authorSlug: 'valmiki',
    },
    {
      id: 238,
      hindi: 'रामो विग्रहवान् धर्मः।\nसदा सत्य पराक्रमः।।',
      english: 'Rama is dharma incarnate — forever valorous in truth.',
      meaning_hindi: 'राम धर्म के साकार रूप हैं — सदा सत्य में पराक्रमी।',
      explanation: 'Valmiki presents Rama not merely as a hero but as the living embodiment of righteous conduct. The epic teaches through character rather than abstract sermon alone.',
      theme: 'Wisdom',
      author: 'Valmiki',
      authorSlug: 'valmiki',
      featured: true,
    },
    {
      id: 239,
      hindi: 'मातृदेवो भव, पितृदेवो भव।\nआचार्यदेवो भव, अतिथिदेवो भव।।',
      english: 'Revere your mother as God, your father as God. Revere your teacher as God, and the guest as God.',
      meaning_hindi: 'माता को देव समान मानो, पिता को देव समान। गुरु को देव समान और अतिथि को देव समान।',
      explanation: 'From the Taittiriya Upanishad tradition echoed throughout the Ramayana\'s household ethics. Valmiki\'s epic constantly illustrates reverence for parents, teachers, and guests.',
      theme: 'Service',
      author: 'Valmiki',
      authorSlug: 'valmiki',
    },
    {
      id: 240,
      hindi: 'एकपत्नी व्रता नारी, सती सर्वगुणान्विता।\nपति वै सम्मतं यस्य, सा सती सत्यवादिनी।।',
      english: 'A woman devoted to one husband, endowed with all virtues — she is a sati whose conduct aligns with her husband\'s truth.',
      meaning_hindi: 'एक पति के प्रति समर्पित, सभी गुणों से युक्त नारी — वह सती है जिसका आचरण पति के सत्य से मेल खाता है।',
      explanation: 'Valmiki\'s portrayal of Sita embodies steadfast loyalty and inner strength. The Ramayana explores her trials as the supreme test of character under injustice.',
      theme: 'Love & Relationships',
      author: 'Valmiki',
      authorSlug: 'valmiki',
    },
    {
      id: 241,
      hindi: 'संचितो धर्मो हि लोके जयते।\nअधर्मो विनश्यति।।',
      english: 'Righteousness gathered and practiced triumphs in the world; unrighteousness perishes.',
      meaning_hindi: 'संचित और पालित धर्म संसार में विजयी होता है; अधर्म नष्ट हो जाता है।',
      explanation: 'The Ramayana\'s narrative arc confirms this principle: Ravana\'s power, however vast, collapses before dharma upheld by Rama and his allies.',
      theme: 'Wisdom',
      author: 'Valmiki',
      authorSlug: 'valmiki',
    },
    {
      id: 242,
      hindi: 'सत्यं ब्रूयात्, प्रियं ब्रूयात्, न ब्रूयात् सत्यमप्रियम्।\nप्रियं च नानृतं ब्रूयात्, एष धर्मः सनातनः।।',
      english: 'Speak truth, speak kindly — do not speak truth that is unkind. Do not speak pleasant falsehoods; this is the eternal dharma.',
      meaning_hindi: 'सत्य बोलो, प्रिय बोलो — अप्रिय सत्य मत बोलो। प्रिय असत्य भी मत बोलो; यही सनातन धर्म है।',
      explanation: 'Valmiki\'s world balances honesty with compassion. Truth must be tempered by care for others\' feelings — a nuanced ethic the epic demonstrates repeatedly.',
      theme: 'Character',
      author: 'Valmiki',
      authorSlug: 'valmiki',
    },
    {
      id: 243,
      hindi: 'राजा परमो धर्मः, राजा परमो तपः।\nराजा हि परमं दैवम्, राजा धर्मस्य कारणम्।।',
      english: 'The king is the highest dharma, the highest austerity. The king is the supreme divinity — the cause of righteousness itself.',
      meaning_hindi: 'राजा सर्वोच्च धर्म है, सर्वोच्च तप है। राजा ही परम दैव है — धर्म का कारण।',
      explanation: 'Valmiki\'s ideal of raj-dharma holds the ruler accountable for the moral health of the entire kingdom. Rama\'s reign (Rama Rajya) becomes the benchmark of just governance.',
      theme: 'Service',
      author: 'Valmiki',
      authorSlug: 'valmiki',
    },
    {
      id: 244,
      hindi: 'अहिंसा परमो धर्मः।\nसर्वभूतानि मैत्रय।।',
      english: 'Non-violence is the highest dharma — friendship toward all beings.',
      meaning_hindi: 'अहिंसा परम धर्म है — सभी प्राणियों के प्रति मैत्री।',
      explanation: 'Though the Ramayana includes necessary war, Valmiki consistently elevates ahimsa and compassion. Rama grieves even for enemies who uphold honor.',
      theme: 'Acceptance',
      author: 'Valmiki',
      authorSlug: 'valmiki',
    },
    {
      id: 245,
      hindi: 'शृण्वन्तु लोकः सर्वो, यथा वर्तन्ति वानराः।\nरामो राजा, सीता पत्नी — धर्मं पश्यत।।',
      english: 'Let the whole world hear how the monkeys and bears served — Rama is king, Sita is queen; behold their dharma.',
      meaning_hindi: 'सारा संसार सुने कि वानरों ने कैसे सेवा की — राम राजा, सीता रानी; उनका धर्म देखो।',
      explanation: 'The epic celebrates collective service across species and rank. Hanuman\'s devotion and the allies\' loyalty illustrate that dharma binds all who serve a righteous cause.',
      theme: 'Friendship',
      author: 'Valmiki',
      authorSlug: 'valmiki',
    },
    {
      id: 246,
      hindi: 'विनाशकाले विपरीत बुद्धिः।\nपापस्यान्ते दुःखम् एव हि।।',
      english: 'At the hour of destruction, understanding turns upside down — the wicked meet only sorrow in the end.',
      meaning_hindi: 'विनाश के समय बुद्धि विपरीत हो जाती है — पापी का अंत केवल दुख ही है।',
      explanation: 'Valmiki charts Ravana\'s decline as wisdom departs from the proud. The epic warns that power without humility leads inevitably to ruin.',
      theme: 'Wisdom',
      author: 'Valmiki',
      authorSlug: 'valmiki',
    },
    {
      id: 247,
      hindi: 'गुरुर्देवो महेश्वरः।\nगुरुरेव परा गतिः।।',
      english: 'The Guru is the great Lord himself — the Guru alone is the supreme refuge.',
      meaning_hindi: 'गुरु महेश्वर स्वरूप हैं — गुरु ही परम गति हैं।',
      explanation: 'Valmiki as Guru to Lava-Kusha embodies this principle. The transmission of sacred knowledge from teacher to disciple is central to the epic\'s closing books.',
      theme: 'Friendship',
      author: 'Valmiki',
      authorSlug: 'valmiki',
    },
    {
      id: 248,
      hindi: 'त्यजेदेकं कुलस्यार्थे, ग्रामस्यार्थे कुलं त्यजेत्।\nग्रामं जनपदस्यार्थे, आत्मार्थे सर्वमुत्सृजेत्।।',
      english: 'Sacrifice one for the family, the family for the village, the village for the nation — for the Self, sacrifice all.',
      meaning_hindi: 'कुल के लिए एक त्यागो, ग्राम के लिए कुल, राष्ट्र के लिए ग्राम — आत्म-ज्ञान के लिए सब त्यागो।',
      explanation: 'A hierarchical ethic of sacrifice familiar from the Mahabharata and Ramayana traditions. Valmiki\'s Rama repeatedly subordinates personal desire to duty.',
      theme: 'Acceptance',
      author: 'Valmiki',
      authorSlug: 'valmiki',
    },
    {
      id: 249,
      hindi: 'यथा धर्मं तथा जयः।\nसत्यमेव जयते नानृतम्।।',
      english: 'As is dharma, so is victory — truth alone triumphs, not falsehood.',
      meaning_hindi: 'जैसा धर्म, वैसी विजय — सत्य की ही जीत है, असत्य की नहीं।',
      explanation: 'The Ramayana\'s moral conclusion: Rama\'s victory is not mere military success but the triumph of truth and righteous order over arrogance and injustice.',
      theme: 'Character',
      author: 'Valmiki',
      authorSlug: 'valmiki',
      featured: true,
    },
    {
      id: 250,
      hindi: 'रामायणमनाद्यं च, पुराणमिति शुश्रुम।\nवाल्मीकेः कथितं पवित्रम्, शृण्वन्तु सदा बुधाः।।',
      english: 'We have heard that the Ramayana is ancient and sacred — told by Valmiki. Let the wise always listen to this pure tale.',
      meaning_hindi: 'हमने सुना है कि रामायण अनादि और पवित्र कथा है — वाल्मीकि द्वारा कही। बुद्धिमान सदा इसे सुनें।',
      explanation: 'A closing invocation in the spirit of Valmiki\'s epic. The Ramayana is not mere history but eternal instruction — meant to be heard, recited, and lived.',
      theme: 'Wisdom',
      author: 'Valmiki',
      authorSlug: 'valmiki',
    },
  ],
}
