// This file contains Devanagari script — ensure UTF-8 encoding
import type { Writer } from '../types'

export const vivekanandaWriter: Writer = {
  slug: 'vivekananda',
  name_english: 'Swami Vivekananda',
  name_hindi: 'स्वामी विवेकानंद',
  era: '19th century (1863–1902)',
  language: 'Hindi / Bengali / English / Sanskrit',
  genre: 'Spiritual philosophy, Vedanta, inspirational teachings',
  short_bio_english:
    'Disciple of Ramakrishna and voice of Vedanta to the West, Vivekananda awakened India to its spiritual strength and taught fearlessness, service, and self-realization.',
  short_bio_hindi:
    'रामकृष्ण के शिष्य और वेदांत के विश्व-प्रवक्ता, विवेकानंद ने भारत को उसकी आध्यात्मिक शक्ति से जगाया और निडरता, सेवा और आत्म-साक्षात्कार का उपदेश दिया।',
  biography: {
    introduction_english:
      'Swami Vivekananda (1863–1902), born Narendranath Datta in Calcutta, was a monk, philosopher, and orator who introduced Hindu philosophy to the Western world and rekindled national pride in India. A chief disciple of Sri Ramakrishna Paramahamsa, he founded the Ramakrishna Mission and represented Hinduism at the 1893 Parliament of the World\'s Religions in Chicago. His teachings on the divinity of the soul, unity of religions, and service to humanity remain among the most influential spiritual messages of modern India.',
    introduction_hindi:
      'स्वामी विवेकानंद (१८६३–१९०२), जिनका जन्म कलकत्ता में नरेंद्रनाथ दत्त के रूप में हुआ, एक संन्यासी, दार्शनिक और वक्ता थे जिन्होंने हिंदू दर्शन को पश्चिम से परिचित कराया और भारत में राष्ट्रीय गौरव को पुनर्जीवित किया। श्री रामकृष्ण परमहंस के प्रमुख शिष्य, उन्होंने रामकृष्ण मिशन की स्थापना की और १८९३ में शिकागो में विश्व धर्म संसद में हिंदू धर्म का प्रतिनिधित्व किया। आत्मा की दिव्यता, धर्मों की एकता और मानव सेवा पर उनके उपदेश आधुनिक भारत के सबसे प्रभावशाली आध्यात्मिक संदेशों में हैं।',
    timeline: [
      {
        year: '1863',
        title_english: 'Birth in Calcutta',
        title_hindi: 'कलकत्ता में जन्म',
        content_english:
          'Narendranath Datta was born on 12 January 1863 into an affluent Kayastha family in Shimla Pally, Calcutta. His father Vishwanath was a successful attorney; his mother Bhuvaneshwari was deeply devout. The boy showed early brilliance, skepticism, and a hunger for truth.',
        content_hindi:
          '१२ जनवरी १८६३ को कलकत्ता के शिमला पल्ली में एक समृद्ध कायस्थ परिवार में नरेंद्रनाथ दत्त का जन्म हुआ। पिता विश्वनाथ सफल वकील थे; माता भुवनेश्वरी अत्यंत भक्त थीं। बालक में प्रतिभा, संशय और सत्य की प्यास प्रारंभ से दिखी।',
      },
      {
        year: '1881–1886',
        title_english: 'Meeting Ramakrishna',
        title_hindi: 'रामकृष्ण से मिलन',
        content_english:
          'As a college student troubled by doubts about God, Narendra visited Dakshineswar and met Sri Ramakrishna. The master\'s direct spiritual experience and love transformed the skeptical youth into a devoted disciple who would carry his message to the world.',
        content_hindi:
          'ईश्वर के प्रति संशय से व्याकुल कॉलेज छात्र के रूप में नरेंद्र दक्षिणेश्वर गए और श्री रामकृष्ण से मिले। गुरु के प्रत्यक्ष आध्यात्मिक अनुभव और प्रेम ने संशयवादी युवक को ऐसा शिष्य बना दिया जो उनका संदेश संसार तक पहुँचाएगा।',
      },
      {
        year: '1893',
        title_english: 'Chicago Parliament of Religions',
        title_hindi: 'शिकागो धर्म संसद',
        content_english:
          'Vivekananda addressed the Parliament of the World\'s Religions in Chicago with the opening words "Sisters and Brothers of America," winning standing ovations. He spoke on Vedanta, tolerance, and the universality of religion, becoming an instant global figure.',
        content_hindi:
          'विवेकानंद ने शिकागो में विश्व धर्म संसद में "Sisters and Brothers of America" कहकर भाषण शुरू किया और तालियों से सम्मानित हुए। उन्होंने वेदांत, सहिष्णुता और धर्म की सार्वभौमिकता पर बोला और तुरंत विश्व-स्तरीय व्यक्तित्व बन गए।',
      },
      {
        year: '1897–1902',
        title_english: 'Ramakrishna Mission and Final Years',
        title_hindi: 'रामकृष्ण मिशन और अंतिम वर्ष',
        content_english:
          'Returning to India, Vivekananda founded the Ramakrishna Math and Mission, emphasizing practical Vedanta — education, relief work, and spiritual practice. He traveled across India inspiring youth before passing away at Belur Math on 4 July 1902 at age 39.',
        content_hindi:
          'भारत लौटकर विवेकानंद ने रामकृष्ण मठ और मिशन की स्थापना की, जिसमें व्यावहारिक वेदांत — शिक्षा, सेवा और साधना — पर बल दिया। वे भारत भ्रमण कर युवाओं को प्रेरित करते रहे और ४ जुलाई १९०२ को बेलूर मठ में ३९ वर्ष की आयु में महासमाधि ली।',
      },
      {
        year: 'Legacy',
        title_english: 'Awakener of Modern India',
        title_hindi: 'आधुनिक भारत के जगाने वाले',
        content_english:
          'Vivekananda\'s birthday is celebrated as National Youth Day in India. His Complete Works span philosophy, yoga, and social reform. "Arise, awake, and stop not till the goal is reached" remains the rallying cry of generations.',
        content_hindi:
          'विवेकानंद का जन्मदिन भारत में राष्ट्रीय युवा दिवस के रूप में मनाया जाता है। उनके संपूर्ण कार्य दर्शन, योग और समाज सुधार को कवर करते हैं। "उठो, जागो और तब तक न रुको जब तक लक्ष्य प्राप्त न हो" पीढ़ियों का आह्वान बना हुआ है।',
      },
    ],
    facts: {
      born: '12 January 1863 — Calcutta (Kolkata)',
      died: '4 July 1902 — Belur Math, West Bengal (aged 39)',
      full_name_english: 'Narendranath Datta (Swami Vivekananda)',
      full_name_hindi: 'नरेंद्रनाथ दत्त (स्वामी विवेकानंद)',
      court: 'Disciple of Sri Ramakrishna; founder of Ramakrishna Mission',
      works: [
        'Raja Yoga — practical guide to meditation and mind control',
        'Karma Yoga — philosophy of selfless action',
        'Bhakti Yoga — path of devotion',
        'Jnana Yoga — path of knowledge',
        'Complete Works of Swami Vivekananda — 9 volumes',
        'Lectures from Colombo to Almora — Indian tour addresses',
      ],
    },
  },
  dohe: [
    {
      id: 146,
      hindi: 'उठो, जागो और तब तक\nन रुको जब तक लक्ष्य प्राप्त न हो।',
      english: 'Arise, awake, and stop not till the goal is reached.',
      meaning_hindi: 'उठो, जागो और अपने लक्ष्य की प्राप्ति तक कभी मत रुको — यही सफलता का मार्ग है।',
      explanation: 'From the Katha Upanishad, popularized by Vivekananda as a call to relentless self-effort. It became the motto of his mission to awaken India\'s youth.',
      theme: 'Wisdom',
      author: 'Swami Vivekananda',
      authorSlug: 'vivekananda',
      featured: true,
    },
    {
      id: 147,
      hindi: 'जो तुम्हें डराता है,\nवही तुम्हारा शत्रु है।',
      english: 'That which frightens you is your enemy.',
      meaning_hindi: 'जो चीज़ तुम्हें भयभीत करती है, वही तुम्हारा वास्तविक शत्रु है — उसका सामना करो।',
      explanation: 'Vivekananda taught that fear limits human potential. Courage comes from confronting what we dread, not from avoiding it.',
      theme: 'Character',
      author: 'Swami Vivekananda',
      authorSlug: 'vivekananda',
      featured: true,
    },
    {
      id: 148,
      hindi: 'हर आत्मा\nपूर्णतः दिव्य है।',
      english: 'Every soul is potentially divine.',
      meaning_hindi: 'प्रत्येक आत्मा में दिव्यता का अंश है — यह वेदांत का मूल सिद्धांत है।',
      explanation: 'The cornerstone of Vivekananda\'s Vedanta — divinity is not reserved for saints alone but is the birthright of every human being.',
      theme: 'Wisdom',
      author: 'Swami Vivekananda',
      authorSlug: 'vivekananda',
      featured: true,
    },
    {
      id: 149,
      hindi: 'शक्ति जीवन में है,\nभय में मृत्यु।',
      english: 'Strength is life; weakness is death.',
      meaning_hindi: 'शक्ति ही जीवन है, कमजोरी मृत्यु के समान है — निडर बनो।',
      explanation: 'Vivekananda rejected timidity as spiritual death. He urged Indians to reclaim physical, mental, and moral strength.',
      theme: 'Character',
      author: 'Swami Vivekananda',
      authorSlug: 'vivekananda',
    },
    {
      id: 150,
      hindi: 'सेवा ही\nसच्ची उपासना है।',
      english: 'Service to humanity is the highest worship.',
      meaning_hindi: 'मानवता की सेवा ही सच्ची पूजा है — ईश्वर सेवा में ही मिलता है।',
      explanation: 'Practical Vedanta for Vivekananda meant serving the poor and suffering as worship of the divine in all beings.',
      theme: 'Service',
      author: 'Swami Vivekananda',
      authorSlug: 'vivekananda',
    },
    {
      id: 151,
      hindi: 'ज्ञान ही\nसबसे बड़ा बल है।',
      english: 'Knowledge is the greatest power.',
      meaning_hindi: 'ज्ञान ही सबसे बड़ी शक्ति है — अज्ञान से मुक्ति असंभव है।',
      explanation: 'Vivekananda championed education as liberation. He believed ignorance, not poverty alone, keeps nations in bondage.',
      theme: 'Wisdom',
      author: 'Swami Vivekananda',
      authorSlug: 'vivekananda',
    },
    {
      id: 152,
      hindi: 'धर्म सार्वभौमिक है,\nसीमाओं में नहीं।',
      english: 'Religion is universal — it knows no boundaries.',
      meaning_hindi: 'धर्म सार्वभौमिक है — यह जात, देश या मज़हब की सीमा नहीं मानता।',
      explanation: 'At Chicago he proclaimed that truth is one though sages call it by many names — the basis of his interfaith vision.',
      theme: 'Acceptance',
      author: 'Swami Vivekananda',
      authorSlug: 'vivekananda',
    },
    {
      id: 153,
      hindi: 'मन ही\nसब कुछ है।',
      english: 'The mind is everything — what you think, you become.',
      meaning_hindi: 'मन ही सब कुछ है — जैसा सोचोगे, वैसा बन जाओगे।',
      explanation: 'Drawing on yoga psychology, Vivekananda taught that mastering the mind is the key to both worldly success and spiritual realization.',
      theme: 'Wisdom',
      author: 'Swami Vivekananda',
      authorSlug: 'vivekananda',
    },
    {
      id: 154,
      hindi: 'कर्म करो,\nफल की चिंता मत करो।',
      english: 'Work without attachment to results.',
      meaning_hindi: 'कर्म करो, परिणाम की चिंता छोड़ दो — यही कर्म योग है।',
      explanation: 'Vivekananda\'s Karma Yoga interprets the Gita\'s teaching for modern life — duty performed with dedication, not anxiety over reward.',
      theme: 'Acceptance',
      author: 'Swami Vivekananda',
      authorSlug: 'vivekananda',
    },
    {
      id: 155,
      hindi: 'विश्वास\nसब कुछ बदल देता है।',
      english: 'Faith can move mountains.',
      meaning_hindi: 'विश्वास पहाड़ भी हिला सकता है — आत्म-विश्वास ही शक्ति का स्रोत है।',
      explanation: 'Vivekananda insisted that self-confidence rooted in the soul\'s divinity enables ordinary people to achieve extraordinary things.',
      theme: 'Character',
      author: 'Swami Vivekananda',
      authorSlug: 'vivekananda',
    },
    {
      id: 156,
      hindi: 'सत्य को\nकभी डर नहीं लगता।',
      english: 'Truth never fears examination.',
      meaning_hindi: 'सत्य को कभी परीक्षा से डर नहीं लगता — सत्य सदा विजयी रहता है।',
      explanation: 'He welcomed scientific inquiry and debate, believing that genuine spirituality withstands all scrutiny.',
      theme: 'Wisdom',
      author: 'Swami Vivekananda',
      authorSlug: 'vivekananda',
    },
    {
      id: 157,
      hindi: 'प्रेम ही\nसबसे शुद्ध धर्म है।',
      english: 'Love is the purest religion.',
      meaning_hindi: 'प्रेम ही सबसे शुद्ध धर्म है — बिना प्रेम के कोई साधना पूर्ण नहीं।',
      explanation: 'Influenced by Ramakrishna\'s universal love, Vivekananda taught that devotion without compassion for all is incomplete.',
      theme: 'Love & Relationships',
      author: 'Swami Vivekananda',
      authorSlug: 'vivekananda',
    },
    {
      id: 158,
      hindi: 'युवा ही\nदेश का भविष्य हैं।',
      english: 'The youth are the hope of the nation.',
      meaning_hindi: 'युवा ही देश का भविष्य हैं — उनमें शक्ति, साहस और आदर्श जगाओ।',
      explanation: 'Vivekananda placed immense faith in young Indians, urging them to combine spirituality with muscular energy and social service.',
      theme: 'Service',
      author: 'Swami Vivekananda',
      authorSlug: 'vivekananda',
    },
    {
      id: 159,
      hindi: 'संसार\nएक विशाल विद्यालय है।',
      english: 'The world is a great school of experience.',
      meaning_hindi: 'संसार एक विशाल विद्यालय है — हर अनुभव सिखाता है।',
      explanation: 'Life\'s joys and sorrows are lessons for the soul\'s evolution, Vivekananda taught — nothing is wasted in the cosmic curriculum.',
      theme: 'Acceptance',
      author: 'Swami Vivekananda',
      authorSlug: 'vivekananda',
    },
    {
      id: 160,
      hindi: 'अपने आप पर\nविश्वास रखो।',
      english: 'Have faith in yourself before all else.',
      meaning_hindi: 'सबसे पहले अपने आप पर विश्वास रखो — आत्म-विश्वास ही मुक्ति का द्वार है।',
      explanation: 'His final message to India: we are children of immortal bliss — self-doubt is the only real bondage.',
      theme: 'Character',
      author: 'Swami Vivekananda',
      authorSlug: 'vivekananda',
    },
  ],
}
